import { describe, expect, it } from 'vitest';
import { parseDeliveryBinding, renderTransientInvoiceLink, requireImmediateInvoiceDelivery, invoicePublicOriginReady } from './binding.ts';
const id='11111111-1111-4111-8111-111111111111';
const binding={operation_id:id,message_id:id,tenant_id:id,invoice_id:id,client_id:id,actor_user_id:id,issued_snapshot_version:2,document_digest:'a'.repeat(64),content_digest:'b'.repeat(64),recipient:'billing@example.test',connector_id:id,subject:'Invoice',body_html:'<p>{{PAIGE_INVOICE_LINK}}</p>',state:'prepared',eligible:true};
describe('immutable invoice delivery binding',()=>{
 it('refuses malformed, foreign, changed or ineligible bindings',()=>{expect(parseDeliveryBinding(binding,id,id)?.recipient).toBe(binding.recipient);for(const patch of [{eligible:false},{tenant_id:'22222222-2222-4222-8222-222222222222'},{message_id:'22222222-2222-4222-8222-222222222222'},{issued_snapshot_version:0},{document_digest:'fake'},{body_html:'<p>No link marker</p>'},{state:'unknown'}])expect(parseDeliveryBinding({...binding,...patch},id,id)).toBeNull()});
 it('renders only fixed origin token link without changing durable HTML',()=>{const html=binding.body_html;expect(renderTransientInvoiceLink(binding,'https://paigeagent.ai','a'.repeat(64))).toContain('https://paigeagent.ai/invoice?token=');expect(binding.body_html).toBe(html);expect(()=>renderTransientInvoiceLink(binding,'http://attacker.test','a'.repeat(64))).toThrow();expect(()=>renderTransientInvoiceLink(binding,'https://paigeagent.ai','bad')).toThrow()});
 it('refuses explicit schedules and automatic quiet-hours queue without external dispatch',()=>{expect(requireImmediateInvoiceDelivery(null,'proceed')).toBe(true);expect(requireImmediateInvoiceDelivery('2027-01-01','proceed')).toBe(false);expect(requireImmediateInvoiceDelivery(null,'queued_quiet_hours')).toBe(false)});
 it('fails origin readiness closed before eligibility for missing, insecure and credential/path origins',()=>{expect(invoicePublicOriginReady('https://paigeagent.ai')).toBe(true);for(const origin of ['', 'not a URL','http://paigeagent.ai','https://user:password@paigeagent.ai','https://paigeagent.ai/foreign','https://paigeagent.ai?token=x'])expect(invoicePublicOriginReady(origin)).toBe(false)});
});
