import { commsProviderExecutionAllowed, COMMS_PROVIDER_EXECUTION_DISABLED } from "../comms-provider-boundary.ts";
import {collectInvoiceLedger} from '../sales-invoice-ledger.ts';
import {renderSalesInvoiceDocument} from '../sales-invoice-document.ts';
import {pdfEmailAttachment} from '../email-attachments.ts';
import { PAIGE_APP_ORIGIN } from "../canonical-app-url.ts";
import {readFileSync} from 'node:fs';
import {transpileModule,ModuleKind,ScriptTarget} from 'typescript';
import {describe,it,expect} from 'vitest';
import {parseDeliveryBinding,renderTransientInvoiceLink,renderTransientInvoiceText} from './binding.ts';
const id='11111111-1111-4111-8111-111111111111',token='c'.repeat(64);
const emailBinding={operation_id:id,message_id:id,tenant_id:id,invoice_id:id,client_id:id,actor_user_id:id,issued_snapshot_version:2,expected_lifecycle_version:3,document_digest:'a'.repeat(64),content_digest:'b'.repeat(64),recipient:'billing@example.test',connector_id:id,subject:'Invoice',body_html:'<a href="{{PAIGE_INVOICE_LINK}}">Invoice</a>',state:'prepared',eligible:true};
const raw=readFileSync('supabase/functions/send-message/index.ts','utf8').replace(/^import[\s\S]*?;\r?\n/gm,'');
const compiled=transpileModule(raw,{compilerOptions:{module:ModuleKind.None,target:ScriptTarget.ES2022}}).outputText;
function setup(options:{providerAllowed?:boolean;boundaryError?:boolean;failure?:boolean;queue?:boolean;claimFailure?:boolean;sms?:boolean;pdfFailure?:boolean;stalePdf?:boolean}={}){
 const binding=options.sms?{...emailBinding,channel:'sms',recipient:'+12025550123',connector_id:null,body_html:'View invoice {{PAIGE_INVOICE_LINK}}'}:emailBinding;
 const writes:unknown[]=[],logs:unknown[]=[],providerBodies:string[]=[],rpcCalls:string[]=[],attachments:unknown[]=[];
 let handler:(req:Request)=>Promise<Response>;
 const admin={from:(table:string)=>{let update=false;const b:Record<string,(...args:unknown[])=>unknown>={};for(const method of ['eq','is','in','not','neq'])b[method]=()=>b;b.select=()=>b;b.insert=(v:unknown)=>{writes.push({table,value:v});return b};b.upsert=b.insert;b.update=(v:unknown)=>{update=true;writes.push({table,value:v});return b};const result=()=>({data:table==='messages'?update?{id}:{tenant_id:id,status:'draft',connector_id:binding.connector_id,contact_id:id,channel_type:options.sms?'sms':'email',meta:{sales_invoice_binding:binding}}:table==='clients'?{tenant_id:id}:table==='channel_connectors'?{tenant_id:id,status:'active',active:true,channel_type:'email',provider:'resend',from_address:'business@example.test'}:{id},error:null});b.maybeSingle=async()=>result();b.single=b.maybeSingle;b.then=(resolve:(value:unknown)=>unknown,reject:(reason:unknown)=>unknown)=>Promise.resolve(result()).then(resolve,reject);return b},rpc:async(name:string,args:Record<string,unknown>)=>{rpcCalls.push(name);if(name==='comms_provider_execution_allowed')return{data:options.providerAllowed??true,error:options.boundaryError?{message:'boundary unavailable'}:null};if(name==='read_sales_invoice_delivery_binding')return{data:binding,error:null};if(name==='claim_sales_invoice_delivery')return options.claimFailure?{data:null,error:{code:'conflict'}}:{data:{state:'dispatching'},error:null};if(name==='_sales_invoice_read')return{data:{version:options.stalePdf?4:3,status:'issued'},error:null};if(name==='read_public_sales_invoice_payment_ledger')return{data:{invoice_id:id,version:3,current_invoice_number:'INV-0042',document_input_digest:'a'.repeat(64),document:{renderer_version:'paige-invoice-html-v1',invoice_number:'INV-0042',currency:'usd',issuer_name:'Example Studio',client_name:'Example Customer',total_cents:1000,snapshot:{items:[{item:'Service',description:'',quantity:1,unit_minor:1000}],due_now_minor:1000,remainder_minor:0,due_date:'2026-10-10'}},manual_recorded_cents:0,remaining_cents:1000,payment_ledger:{rows:[],count:0,receipt_total_cents:0,reversal_total_cents:0,as_of:'2026-10-04T12:00:00Z',complete:true},has_more:false},error:null};if(name==='finalize_sales_invoice_delivery')return{data:{outcome:args._outcome},error:null};return{data:{from_address:'business@example.test'},error:null}}};
 const scope={commsProviderExecutionAllowed,COMMS_PROVIDER_EXECUTION_DISABLED,collectInvoiceLedger,renderSalesInvoiceDocument,pdfEmailAttachment,renderDocumentPdf:async()=>{if(options.pdfFailure)throw Error('PDF_UNAVAILABLE');return new TextEncoder().encode('%PDF-test');},readInvoiceDeliveryReadiness:async()=>({eligible:true}),PAIGE_APP_ORIGIN,Deno:{env:{get:(key:string)=>key==='SUPABASE_SERVICE_ROLE_KEY'?'internal':'configured'},serve:(fn:typeof handler)=>{handler=fn}},createClient:()=>admin,registerOutboundAdapter:()=>{},buildListUnsubscribeHeaders:()=>({}),getOutboundAdapter:()=>({send:async(msg:{body_html?:string;body_text?:string},ctx:{serverAttachments?:unknown[]})=>{attachments.push(...ctx.serverAttachments??[]);providerBodies.push(msg.body_text??msg.body_html??'');if(options.failure)throw Error(`provider echoed ${msg.body_text??msg.body_html}`);return{ok:true,provider_message_id:'provider-receipt'}}}),runPreSend:async()=>({proceed:!options.queue,outcome:options.queue?'queued_quiet_hours':'proceed'}),CLIENT_CONTACT_METHODS_EMBED:'client_contact_methods',clientAddresses:()=>({emails:[],phones:[]}),mintSignerToken:()=>token,sha256Hex:async()=> 'd'.repeat(64),parseDeliveryBinding,renderTransientInvoiceLink,renderTransientInvoiceText,console:{warn:(...v:unknown[])=>logs.push(v),error:(...v:unknown[])=>logs.push(v),log:(...v:unknown[])=>logs.push(v)}};
 new Function(...Object.keys(scope),compiled)(...Object.values(scope));
 return{writes,logs,providerBodies,rpcCalls,attachments,request:async(extra={})=>{const r=await handler!(new Request('https://example.test/send-message',{method:'POST',headers:{Authorization:'Bearer internal'},body:JSON.stringify({channel:options.sms?'sms':'email',to:binding.recipient,contact_id:id,connector_id:binding.connector_id,message_id:id,subject:binding.subject,body:binding.body_html,invoice_delivery_operation_id:id,...extra})}));return{status:r.status,body:await r.json()}}};
}
describe('actual send-message invoice path, network substituted only',()=>{
 it('places token only in provider input, never audit/message/readback/log payload',async()=>{const s=setup();const r=await s.request();expect(r.body.outcome).toBe('provider_accepted');expect(s.providerBodies).toHaveLength(1);expect(s.providerBodies[0]).toContain(token);expect(JSON.stringify([s.writes,s.logs,r])).not.toContain(token);expect(r.body.delivery_confirmed).toBe(false)});
 it('attaches server-produced PDF and refuses failed/stale artifact before provider invocation',async()=>{const ok=setup();await ok.request();expect(ok.attachments).toEqual([expect.objectContaining({filename:'invoice-INV-0042.pdf',contentType:'application/pdf'})]);for(const options of [{pdfFailure:true},{stalePdf:true}]){const s=setup(options);const result=await s.request();expect(s.providerBodies).toHaveLength(0);expect(result.body.outcome).toBe('failed');}});
 it('scrubs provider exceptions and records unknown, never retry-safe failure',async()=>{const s=setup({failure:true});const r=await s.request();expect(r.body.outcome).toBe('unknown');expect(JSON.stringify([s.writes,s.logs,r])).not.toContain(token)});
 it('refuses queue without claim/provider and losing claim never finalizes another attempt',async()=>{const q=setup({queue:true});expect((await q.request()).body.outcome).toBe('failed');expect(q.providerBodies).toHaveLength(0);expect(q.rpcCalls).not.toContain('claim_sales_invoice_delivery');const s=setup({claimFailure:true});expect((await s.request()).body.outcome).toBe('outcome_unknown');expect(s.providerBodies).toHaveLength(0);expect(s.rpcCalls).not.toContain('finalize_sales_invoice_delivery')});
 it('rejects caller-altered recipients, content and scheduled invoice dispatch before provider admission',async()=>{for(const extra of [{to:'changed@example.test'},{body:'altered'}, {scheduled_for:'2099-01-01T00:00:00Z'}]){const s=setup();const r=await s.request(extra);expect(r.status).toBeGreaterThanOrEqual(400);expect(s.providerBodies).toHaveLength(0);expect(s.rpcCalls).not.toContain('claim_sales_invoice_delivery')}});
 it('SMS uses ephemeral bearer text with token-free durable records and atomic admission',async()=>{const s=setup({sms:true});const r=await s.request();expect(r.body.outcome).toBe('provider_accepted');expect(s.providerBodies[0]).toContain(token);expect(JSON.stringify([s.writes,s.logs,r])).not.toContain(token);expect(s.rpcCalls).toContain('claim_sales_invoice_delivery')});
 it('SMS provider echoed bearer errors stay unknown and never leak to readback audit or logs',async()=>{const s=setup({sms:true,failure:true});const r=await s.request();expect(r.body.outcome).toBe('unknown');expect(JSON.stringify([s.writes,s.logs,r])).not.toContain(token)});
});

for(const sms of [false,true])it.each([{providerAllowed:false},{boundaryError:true}])(`provider floor refuses invoice ${sms?'SMS':'email'} before attachment/token/provider work (%j)`,async options=>{
 const s=setup({...options,sms});const r=await s.request();
 expect(r.status).toBe(403);expect(r.body.outcome).toBe('refused');expect(r.body.error).toBe('COMMS_PROVIDER_EXECUTION_DISABLED');
 expect(s.providerBodies).toHaveLength(0);expect(s.attachments).toHaveLength(0);
 expect(s.rpcCalls).not.toContain('claim_sales_invoice_delivery');expect(s.rpcCalls).not.toContain('read_public_sales_invoice_payment_ledger');
 expect(JSON.stringify([s.writes,s.logs,r])).not.toContain(token);
});
