-- ============================================================================
-- Assigned staff reach what they are assigned, inside the business, with no title role.
--
-- Proves, for the policies that gave an assigned staff member access to a client's records: the
-- assignment plus membership of the client's business is the whole of the grant — no platform role is
-- needed; an assignment to a client of a business the person does not belong to grants nothing; a
-- person holding the retired global coach role gains nothing from it; and no policy on these tables
-- reads that role any more.
--
-- Synthetic fixtures only. Asserts counts, catalog facts and refusals, never field values. Rolls back.
-- ============================================================================
BEGIN;

SELECT plan(10);

-- Production grants `authenticated` these privileges; a schema replayed from migrations does not.
GRANT SELECT, UPDATE, DELETE ON public.clients TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.deals, public.tasks TO authenticated;
GRANT SELECT ON public.pipelines, public.pipeline_stages, public.coach_clients TO authenticated;
-- Function grants exactly as production holds them for `authenticated`.
GRANT EXECUTE ON FUNCTION public.current_user_tenant_id(), public.has_role(uuid, public.app_role),
  public.has_any_role(uuid, text[]), public.is_assigned_to_client(uuid, uuid, text),
  public.is_platform_owner(), public.is_platform_owner(uuid), public.is_tenant_member(uuid)
TO authenticated;

DO $$
DECLARE
  _a uuid := 'a5560000-0000-0000-0000-00000000000a';
  _b uuid := 'a5560000-0000-0000-0000-00000000000b';
  _m uuid := 'a5560000-0000-0000-0000-0000000000a1';  -- member of A, assigned to X; no platform role
  _g uuid := 'a5560000-0000-0000-0000-0000000000a2';  -- member of A holding the retired global coach role
  _y uuid := 'a5560000-0000-0000-0000-000000000e01';  -- the person X is, a client of A
  _p uuid;
BEGIN
  INSERT INTO auth.users (id, email) VALUES
    (_m, 'asn-member@example.test'), (_g, 'asn-titled@example.test'), (_y, 'asn-client@example.test');
  INSERT INTO public.tenants (id, slug, name, status, account_type, account_number_prefix, features) VALUES
    (_a, 'asn-scope-a', 'ASN Scope A', 'active', 'standalone', 'ANA', '{}'),
    (_b, 'asn-scope-b', 'ASN Scope B', 'active', 'standalone', 'ANB', '{}');
  INSERT INTO public.tenant_members (tenant_id, user_id, role, status, is_owner) VALUES
    (_a, _m, 'member', 'active', false),
    (_a, _g, 'member', 'active', false);
  INSERT INTO public.user_roles (user_id, role) VALUES (_g, 'coach') ON CONFLICT DO NOTHING;
  INSERT INTO public.profiles (user_id, active_tenant_id) VALUES (_m, _a), (_g, _a)
  ON CONFLICT (user_id) DO UPDATE SET active_tenant_id = EXCLUDED.active_tenant_id;
  -- X: a client of A assigned to M. W: a client of B assigned to M, a business M does not belong to.
  INSERT INTO public.clients (id, tenant_id, created_by, first_name, last_name, account_number, linked_user_id, assigned_coach_user_id) VALUES
    ('a5560000-0000-0000-0000-00000000c1e1', _a, _m, 'X', 'Client', 'ANX-1', _y, _m),
    ('a5560000-0000-0000-0000-00000000c1e2', _b, _m, 'W', 'Client', 'ANW-1', NULL, _m);
  -- A pipeline's identity is generated by the server, from a recorded creation path.
  PERFORM set_config('app.pipeline_created_through', 'paige', true);
  PERFORM set_config('app.pipeline_requested_by', _m::text, true);
  INSERT INTO public.pipelines (tenant_id, name, is_default) VALUES (_a, 'ASN pipeline', true)
    RETURNING id INTO _p;
  PERFORM set_config('asn.pipeline', _p::text, true);
  INSERT INTO public.pipeline_stages (id, pipeline_id, tenant_id, label, order_index, probability, stage_type) VALUES
    ('a5560000-0000-0000-0000-00000000a101', _p, _a, 'Lead', 1, 10, 'open');
  INSERT INTO public.deals (id, title, pipeline_id, stage_id, status, tenant_id, contact_client_id) VALUES
    ('a5560000-0000-0000-0000-00000000d001', 'ASN deal', _p,
     'a5560000-0000-0000-0000-00000000a101', 'open', _a, 'a5560000-0000-0000-0000-00000000c1e1');
  INSERT INTO public.tasks (id, user_id, tenant_id, title) VALUES
    ('a5560000-0000-0000-0000-00000000f001', _y, _a, 'ASN task');
END $$;

-- 1. No policy on these tables reads the retired role, and the policies that only restated admin
--    access are gone.
SELECT is((SELECT count(*)::int FROM pg_policy p
            WHERE p.polrelid IN ('public.business_verification_runs'::regclass, 'public.clients'::regclass,
                                 'public.coach_clients'::regclass, 'public.deal_activities'::regclass,
                                 'public.deals'::regclass, 'public.invitations'::regclass,
                                 'public.outreach_drafts'::regclass, 'public.paige_health_snapshots'::regclass,
                                 'public.paige_messages_audit'::regclass, 'public.paige_skill_runs'::regclass,
                                 'public.paige_workflow_runs'::regclass, 'public.pipeline_stages'::regclass,
                                 'public.pipelines'::regclass, 'public.quickbooks_connections'::regclass,
                                 'public.quickbooks_financials'::regclass, 'public.quickbooks_transactions'::regclass,
                                 'public.research_runs'::regclass, 'public.research_sources'::regclass,
                                 'public.response_quality_feedback'::regclass, 'public.tasks'::regclass)
              AND (coalesce(pg_get_expr(p.polqual, p.polrelid), '') || coalesce(pg_get_expr(p.polwithcheck, p.polrelid), ''))
                  ~* 'has_role\(.{0,80}?''coach'''), 0,
  'no policy on these tables reads the retired coach role');

-- Counts are read as each person, stored, then asserted after RESET ROLE.
SELECT set_config('request.jwt.claims', '{"sub":"a5560000-0000-0000-0000-0000000000a1","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;
DO $$
DECLARE _n int;
BEGIN
  PERFORM set_config('asn.m_client_a', (SELECT count(*) FROM public.clients WHERE id = 'a5560000-0000-0000-0000-00000000c1e1')::text, true);
  PERFORM set_config('asn.m_client_b', (SELECT count(*) FROM public.clients WHERE id = 'a5560000-0000-0000-0000-00000000c1e2')::text, true);
  PERFORM set_config('asn.m_deal', (SELECT count(*) FROM public.deals WHERE id = 'a5560000-0000-0000-0000-00000000d001')::text, true);
  PERFORM set_config('asn.m_task', (SELECT count(*) FROM public.tasks WHERE id = 'a5560000-0000-0000-0000-00000000f001')::text, true);
  PERFORM set_config('asn.m_rel', (SELECT count(*) FROM public.coach_clients WHERE coach_user_id = 'a5560000-0000-0000-0000-0000000000a1')::text, true);
  DELETE FROM public.clients WHERE id = 'a5560000-0000-0000-0000-00000000c1e1';
  GET DIAGNOSTICS _n = ROW_COUNT;
  PERFORM set_config('asn.m_deleted', _n::text, true);
END $$;
RESET ROLE;

SELECT set_config('request.jwt.claims', '{"sub":"a5560000-0000-0000-0000-0000000000a2","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;
DO $$
BEGIN
  PERFORM set_config('asn.g_pipelines', (SELECT count(*) FROM public.pipelines WHERE tenant_id = 'a5560000-0000-0000-0000-00000000000a')::text, true);
  PERFORM set_config('asn.g_deal', (SELECT count(*) FROM public.deals WHERE id = 'a5560000-0000-0000-0000-00000000d001')::text, true);
END $$;
RESET ROLE;
SELECT set_config('request.jwt.claims', '', true);

-- 2-6. The assignment plus membership of the business is the whole grant.
SELECT is(current_setting('asn.m_client_a')::int, 1, 'an assigned member sees the client they are assigned');
SELECT is(current_setting('asn.m_client_b')::int, 0,
  'an assignment to a client of a business the person does not belong to grants nothing');
SELECT is(current_setting('asn.m_deal')::int, 1, 'an assigned member sees the deals on that client');
SELECT is(current_setting('asn.m_task')::int, 1, 'an assigned member sees the tasks for that client');
SELECT is(current_setting('asn.m_rel')::int, 1, 'an assigned member sees their own assignment');

-- 7. An assignment does not let the assignee delete the client.
SELECT is(current_setting('asn.m_deleted')::int, 0, 'an assignment does not let the assignee delete the client');

-- 8-9. The retired role grants nothing on its own.
SELECT is(current_setting('asn.g_pipelines')::int, 0, 'the retired coach role does not open the business''s pipelines');
SELECT is(current_setting('asn.g_deal')::int, 0, 'the retired coach role does not open a deal the person is not assigned to');

-- 10. Nor does it let the person create a deal.
SELECT set_config('request.jwt.claims', '{"sub":"a5560000-0000-0000-0000-0000000000a2","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;
SELECT throws_ok(
  $$INSERT INTO public.deals (title, pipeline_id, stage_id, status, tenant_id, owner_user_id)
    VALUES ('ASN new deal', current_setting('asn.pipeline')::uuid,
            'a5560000-0000-0000-0000-00000000a101', 'open',
            'a5560000-0000-0000-0000-00000000000a', 'a5560000-0000-0000-0000-0000000000a2')$$,
  '42501', NULL, 'the retired coach role does not let a person create a deal');
RESET ROLE;

SELECT * FROM finish();
ROLLBACK;
