-- ============================================================================
-- No database function grants anything through the retired title role.
--
-- Proves: outside the grant paths (the next slice) and the finance functions, no function reads the
-- platform-wide `coach` role or a `coach` membership seat; a person holding either gains nothing from
-- it — not staff standing, not a studio seat, not paid features, not record access through the CRM
-- commands; and an assigned member reads the deals of the client they are assigned in the pipeline
-- workspace through the assignment plus membership of the business, and not the deals of a client they
-- only created; and the retired role no longer opens another person's profile.
--
-- Synthetic fixtures only. Asserts counts, catalog facts and refusals, never field values. Rolls back.
-- ============================================================================
BEGIN;

-- No row may hold the retired role any longer (20270508000000). This file proves that rows
-- holding it, like the ones production held before they were deleted, grant nothing, so it
-- stands such rows up by lifting the constraint inside this rolled-back transaction.
ALTER TABLE public.user_roles DROP CONSTRAINT IF EXISTS user_roles_role_not_retired_title_role;
ALTER TABLE public.tenant_members DROP CONSTRAINT IF EXISTS tenant_members_role_not_retired_title_role;

SELECT plan(8);

-- Production grants `authenticated` these privileges; a schema replayed from migrations does not.
GRANT SELECT ON public.clients, public.deals, public.pipelines, public.pipeline_stages,
  public.tasks, public.deal_activities TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_tenant_id(), public.has_role(uuid, public.app_role),
  public.has_any_role(uuid, text[]), public.is_assigned_to_client(uuid, uuid, text),
  public.is_platform_owner(), public.is_platform_owner(uuid), public.is_tenant_member(uuid),
  public.is_tenant_admin(uuid), public.get_pipeline_workspace_pre_identity(uuid),
  public.get_profile_with_pii_log(uuid)
TO authenticated;
GRANT SELECT ON public.profiles TO authenticated;

DO $$
DECLARE
  _a uuid := 'c8820000-0000-0000-0000-00000000000a';
  _m uuid := 'c8820000-0000-0000-0000-0000000000a1';  -- member of A, assigned to X; no platform role
  _g uuid := 'c8820000-0000-0000-0000-0000000000a2';  -- member of A holding the retired global coach role
  _s uuid := 'c8820000-0000-0000-0000-0000000000a3';  -- holds a coach seat in A, assigned to U
  _y uuid := 'c8820000-0000-0000-0000-000000000e01';  -- the person X is, a client of A
  _p uuid;
BEGIN
  INSERT INTO auth.users (id, email) VALUES
    (_m, 'trf-member@example.test'), (_g, 'trf-titled@example.test'), (_s, 'trf-seat@example.test'),
    (_y, 'trf-client@example.test');
  INSERT INTO public.tenants (id, slug, name, status, account_type, account_number_prefix, features) VALUES
    (_a, 'trf-scope-a', 'TRF Scope A', 'active', 'standalone', 'TFA', '{}');
  INSERT INTO public.tenant_members (tenant_id, user_id, role, status, is_owner) VALUES
    (_a, _m, 'member', 'active', false),
    (_a, _g, 'member', 'active', false),
    (_a, _s, 'coach', 'active', false);
  INSERT INTO public.user_roles (user_id, role) VALUES (_g, 'coach') ON CONFLICT DO NOTHING;
  INSERT INTO public.profiles (user_id, active_tenant_id) VALUES (_m, _a), (_g, _a), (_s, _a)
  ON CONFLICT (user_id) DO UPDATE SET active_tenant_id = EXCLUDED.active_tenant_id;
  INSERT INTO public.clients (id, tenant_id, created_by, first_name, last_name, account_number, linked_user_id, assigned_coach_user_id) VALUES
    ('c8820000-0000-0000-0000-00000000c1e1', _a, _m, 'X', 'Client', 'TFX-1', _y, _m),
    ('c8820000-0000-0000-0000-00000000c1e3', _a, _m, 'U', 'Client', 'TFU-1', NULL, _s);
  -- A pipeline's identity is generated by the server, from a recorded creation path.
  PERFORM set_config('app.pipeline_created_through', 'paige', true);
  PERFORM set_config('app.pipeline_requested_by', _m::text, true);
  INSERT INTO public.pipelines (tenant_id, name, is_default) VALUES (_a, 'TRF pipeline', true)
    RETURNING id INTO _p;
  INSERT INTO public.pipeline_stages (id, pipeline_id, tenant_id, label, order_index, probability, stage_type) VALUES
    ('c8820000-0000-0000-0000-00000000a101', _p, _a, 'Lead', 1, 10, 'open');
  INSERT INTO public.deals (id, title, pipeline_id, stage_id, status, tenant_id, contact_client_id) VALUES
    ('c8820000-0000-0000-0000-00000000d001', 'TRF deal', _p,
     'c8820000-0000-0000-0000-00000000a101', 'open', _a, 'c8820000-0000-0000-0000-00000000c1e1'),
    ('c8820000-0000-0000-0000-00000000d002', 'TRF deal U', _p,
     'c8820000-0000-0000-0000-00000000a101', 'open', _a, 'c8820000-0000-0000-0000-00000000c1e3');
END $$;

-- 1. No function reads the retired role, outside the grant paths and the finance functions.
SELECT is((SELECT coalesce(string_agg(p.proname, '; ' ORDER BY p.proname), '')
             FROM pg_proc p
            WHERE p.pronamespace = 'public'::regnamespace AND p.prokind = 'f'
              -- The grant paths are the next slice.
              AND p.proname NOT IN ('accept_invitation', 'admin_bulk_assign_coach',
                                    'assignment_role_for', 'auto_enroll_affiliate', 'grant_tenant_member_role',
                                    'map_app_role_to_tenant_role', 'map_tenant_role_to_app_role',
                                    'sync_user_role_to_tenant_member', 'reassign_coach_clients',
                                    -- A finance function, with the finance slice.
                                    'delete_credit_report_upload')
              AND p.prosrc ~ ('has_(any_|tenant_)?role\([^;]*''coach'''
                              || '|\m(tm|m)\.role(::text)?\s*(in|IN|=)\s*\(?[^;)]*''coach'''
                              || '|\mrole::text\s*(in|IN|=)\s*\(?[^;)]*''coach'''
                              || '|v_role is distinct from ''coach''|v_actor_role\s*=\s*''coach''')),
  '', 'no function outside the grant paths and the finance functions reads the retired coach role');

-- 2-4. The retired role gives no staff standing, no studio seat and no paid features.
SELECT is(public.is_staff('c8820000-0000-0000-0000-0000000000a2'), false,
  'the retired coach role does not make a person staff');
SELECT is(public.studio_role_ok('c8820000-0000-0000-0000-0000000000a2'), false,
  'the retired coach role does not open the studio');
SELECT is(public.check_feature_access('c8820000-0000-0000-0000-0000000000a2', 'advanced_analytics'), false,
  'the retired coach role does not unlock paid features');

-- 5. A coach seat gives no record access through the CRM commands, even on a client assigned to it.
SELECT is(public.crm_actor_can_access_record('c8820000-0000-0000-0000-00000000000a',
            'c8820000-0000-0000-0000-0000000000a3', 'contact', 'c8820000-0000-0000-0000-00000000c1e3'),
  false, 'a coach seat does not open a client''s record to the CRM commands');

-- 6. An assigned member sees the deals of the client they are assigned in the pipeline workspace.
SELECT set_config('request.jwt.claims', '{"sub":"c8820000-0000-0000-0000-0000000000a1","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;
SELECT set_config('trf.m_deals',
  jsonb_array_length(public.get_pipeline_workspace_pre_identity('c8820000-0000-0000-0000-00000000000a')->'deals')::text, true);
SELECT set_config('trf.m_deal_u',
  (SELECT count(*) FROM jsonb_array_elements(public.get_pipeline_workspace_pre_identity('c8820000-0000-0000-0000-00000000000a')->'deals') d
    WHERE d->>'id' = 'c8820000-0000-0000-0000-00000000d002')::text, true);
RESET ROLE;
SELECT set_config('request.jwt.claims', '', true);
SELECT is(current_setting('trf.m_deals')::int, 1,
  'an assigned member sees the deals of the client they are assigned in the pipeline workspace');

-- 7. Regression guard: a client the member only created, assigned to someone else, stays out of view.
SELECT is(current_setting('trf.m_deal_u')::int, 0,
  'a member does not see the deals of a client they created but are not assigned');

-- 8. The retired role does not open another person's profile.
SELECT set_config('request.jwt.claims', '{"sub":"c8820000-0000-0000-0000-0000000000a2","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;
SELECT throws_ok($$SELECT * FROM public.get_profile_with_pii_log('c8820000-0000-0000-0000-0000000000a1')$$,
  NULL, NULL, 'the retired coach role does not open another person''s profile');
RESET ROLE;
SELECT set_config('request.jwt.claims', '', true);

SELECT * FROM finish();
ROLLBACK;
