// GENERATED by scripts/fonts/fetch-brand-fonts.mjs — do not edit by hand; rerun the script.
// The self-hosted WOFF2 files under public/fonts/brand/<slug>/ (latin subset, OFL, licence beside each).
// Policy (what is offered, character, pairing, fallback) lives in ./brand-fonts.ts, never here.

export interface BrandFontFile {
  /** File name under /fonts/brand/<slug>/. */
  file: string;
  style: string;
  /** CSS font-weight descriptor: a single weight, or "min max" for a variable file. */
  weight: string;
  /** CSS font-stretch descriptor, present only for a width-variable file. */
  stretch?: string;
  /** The fvar axes verified in the file by the fetch script (empty = static). */
  axes: readonly string[];
  bytes: number;
}

export interface BrandFontFileSet {
  family: string;
  license: string;
  designer: string | null;
  source: string;
  unicodeRange: string;
  files: readonly BrandFontFile[];
}

export const BRAND_FONT_FILES: Record<string, BrandFontFileSet> = {
  "source-serif-4": {
    "family": "Source Serif 4",
    "license": "OFL",
    "designer": "Frank Grießhammer",
    "source": "https://github.com/google/fonts/tree/main/ofl/sourceserif4",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "source-serif-4-normal-200-900.woff2",
        "style": "normal",
        "weight": "200 900",
        "axes": [
          "wght 200–900",
          "opsz 8–60"
        ],
        "bytes": 122360
      }
    ]
  },
  "literata": {
    "family": "Literata",
    "license": "OFL",
    "designer": "TypeTogether",
    "source": "https://github.com/google/fonts/tree/main/ofl/literata",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "literata-normal-200-900.woff2",
        "style": "normal",
        "weight": "200 900",
        "axes": [
          "opsz 7–72",
          "wght 200–900"
        ],
        "bytes": 110080
      }
    ]
  },
  "spectral": {
    "family": "Spectral",
    "license": "OFL",
    "designer": "Production Type",
    "source": "https://github.com/google/fonts/tree/main/ofl/spectral",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "spectral-normal-400.woff2",
        "style": "normal",
        "weight": "400",
        "axes": [],
        "bytes": 21696
      },
      {
        "file": "spectral-normal-500.woff2",
        "style": "normal",
        "weight": "500",
        "axes": [],
        "bytes": 22836
      },
      {
        "file": "spectral-normal-600.woff2",
        "style": "normal",
        "weight": "600",
        "axes": [],
        "bytes": 22936
      },
      {
        "file": "spectral-normal-700.woff2",
        "style": "normal",
        "weight": "700",
        "axes": [],
        "bytes": 23036
      },
      {
        "file": "spectral-normal-800.woff2",
        "style": "normal",
        "weight": "800",
        "axes": [],
        "bytes": 22120
      }
    ]
  },
  "bodoni-moda": {
    "family": "Bodoni Moda",
    "license": "OFL",
    "designer": "Owen Earl",
    "source": "https://github.com/google/fonts/tree/main/ofl/bodonimoda",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "bodoni-moda-normal-400-900.woff2",
        "style": "normal",
        "weight": "400 900",
        "axes": [
          "wght 400–900",
          "opsz 6–96"
        ],
        "bytes": 46260
      }
    ]
  },
  "libre-caslon-display": {
    "family": "Libre Caslon Display",
    "license": "OFL",
    "designer": "Impallari Type",
    "source": "https://github.com/google/fonts/tree/main/ofl/librecaslondisplay",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "libre-caslon-display-normal-400.woff2",
        "style": "normal",
        "weight": "400",
        "axes": [],
        "bytes": 24236
      }
    ]
  },
  "gloock": {
    "family": "Gloock",
    "license": "OFL",
    "designer": "Duarte Pinto",
    "source": "https://github.com/google/fonts/tree/main/ofl/gloock",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "gloock-normal-400.woff2",
        "style": "normal",
        "weight": "400",
        "axes": [],
        "bytes": 26356
      }
    ]
  },
  "source-sans-3": {
    "family": "Source Sans 3",
    "license": "OFL",
    "designer": "Paul D. Hunt",
    "source": "https://github.com/google/fonts/tree/main/ofl/sourcesans3",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "source-sans-3-normal-200-900.woff2",
        "style": "normal",
        "weight": "200 900",
        "axes": [
          "wght 200–900"
        ],
        "bytes": 28872
      }
    ]
  },
  "public-sans": {
    "family": "Public Sans",
    "license": "OFL",
    "designer": "USWDS, Dan Williams, Pablo Impallari, Rodrigo Fuenzalida",
    "source": "https://github.com/google/fonts/tree/main/ofl/publicsans",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "public-sans-normal-100-900.woff2",
        "style": "normal",
        "weight": "100 900",
        "axes": [
          "wght 100–900"
        ],
        "bytes": 26832
      }
    ]
  },
  "urbanist": {
    "family": "Urbanist",
    "license": "OFL",
    "designer": "Corey Hu",
    "source": "https://github.com/google/fonts/tree/main/ofl/urbanist",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "urbanist-normal-100-900.woff2",
        "style": "normal",
        "weight": "100 900",
        "axes": [
          "wght 100–900"
        ],
        "bytes": 27752
      }
    ]
  },
  "figtree": {
    "family": "Figtree",
    "license": "OFL",
    "designer": "Erik Kennedy",
    "source": "https://github.com/google/fonts/tree/main/ofl/figtree",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "figtree-normal-300-900.woff2",
        "style": "normal",
        "weight": "300 900",
        "axes": [
          "wght 300–900"
        ],
        "bytes": 20156
      }
    ]
  },
  "onest": {
    "family": "Onest",
    "license": "OFL",
    "designer": "Dmitri Voloshin, Andrey Kudryavtsev",
    "source": "https://github.com/google/fonts/tree/main/ofl/onest",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "onest-normal-100-900.woff2",
        "style": "normal",
        "weight": "100 900",
        "axes": [
          "wght 100–900"
        ],
        "bytes": 33760
      }
    ]
  },
  "manrope": {
    "family": "Manrope",
    "license": "OFL",
    "designer": "Mikhail Sharanda",
    "source": "https://github.com/google/fonts/tree/main/ofl/manrope",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "manrope-normal-200-800.woff2",
        "style": "normal",
        "weight": "200 800",
        "axes": [
          "wght 200–800"
        ],
        "bytes": 24836
      }
    ]
  },
  "barlow-semi-condensed": {
    "family": "Barlow Semi Condensed",
    "license": "OFL",
    "designer": "Jeremy Tribby",
    "source": "https://github.com/google/fonts/tree/main/ofl/barlowsemicondensed",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "barlow-semi-condensed-normal-400.woff2",
        "style": "normal",
        "weight": "400",
        "axes": [],
        "bytes": 22300
      },
      {
        "file": "barlow-semi-condensed-normal-500.woff2",
        "style": "normal",
        "weight": "500",
        "axes": [],
        "bytes": 22428
      },
      {
        "file": "barlow-semi-condensed-normal-600.woff2",
        "style": "normal",
        "weight": "600",
        "axes": [],
        "bytes": 22984
      },
      {
        "file": "barlow-semi-condensed-normal-700.woff2",
        "style": "normal",
        "weight": "700",
        "axes": [],
        "bytes": 23244
      },
      {
        "file": "barlow-semi-condensed-normal-800.woff2",
        "style": "normal",
        "weight": "800",
        "axes": [],
        "bytes": 23192
      }
    ]
  },
  "oswald": {
    "family": "Oswald",
    "license": "OFL",
    "designer": "Vernon Adams, Kalapi Gajjar, Cyreal",
    "source": "https://github.com/google/fonts/tree/main/ofl/oswald",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "oswald-normal-200-700.woff2",
        "style": "normal",
        "weight": "200 700",
        "axes": [
          "wght 200–700"
        ],
        "bytes": 28488
      }
    ]
  },
  "anton": {
    "family": "Anton",
    "license": "OFL",
    "designer": "Vernon Adams",
    "source": "https://github.com/google/fonts/tree/main/ofl/anton",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "anton-normal-400.woff2",
        "style": "normal",
        "weight": "400",
        "axes": [],
        "bytes": 18612
      }
    ]
  },
  "unbounded": {
    "family": "Unbounded",
    "license": "OFL",
    "designer": "NaN",
    "source": "https://github.com/google/fonts/tree/main/ofl/unbounded",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "unbounded-normal-200-900.woff2",
        "style": "normal",
        "weight": "200 900",
        "axes": [
          "wght 200–900"
        ],
        "bytes": 50904
      }
    ]
  },
  "archivo": {
    "family": "Archivo",
    "license": "OFL",
    "designer": "Omnibus-Type",
    "source": "https://github.com/google/fonts/tree/main/ofl/archivo",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "archivo-normal-100-900.woff2",
        "style": "normal",
        "weight": "100 900",
        "stretch": "62% 125%",
        "axes": [
          "wght 100–900",
          "wdth 62–125"
        ],
        "bytes": 90104
      }
    ]
  },
  "montserrat": {
    "family": "Montserrat",
    "license": "OFL",
    "designer": "Julieta Ulanovsky, Sol Matas, Juan Pablo del Peral, Jacques Le Bailly",
    "source": "https://github.com/google/fonts/tree/main/ofl/montserrat",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "montserrat-normal-100-900.woff2",
        "style": "normal",
        "weight": "100 900",
        "axes": [
          "wght 100–900"
        ],
        "bytes": 37956
      }
    ]
  },
  "inter": {
    "family": "Inter",
    "license": "OFL",
    "designer": "Rasmus Andersson",
    "source": "https://github.com/google/fonts/tree/main/ofl/inter",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "inter-normal-100-900.woff2",
        "style": "normal",
        "weight": "100 900",
        "axes": [
          "opsz 14–32",
          "wght 100–900"
        ],
        "bytes": 72920
      }
    ]
  },
  "plus-jakarta-sans": {
    "family": "Plus Jakarta Sans",
    "license": "OFL",
    "designer": "Tokotype",
    "source": "https://github.com/google/fonts/tree/main/ofl/plusjakartasans",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "plus-jakarta-sans-normal-200-800.woff2",
        "style": "normal",
        "weight": "200 800",
        "axes": [
          "wght 200–800"
        ],
        "bytes": 27348
      }
    ]
  },
  "poppins": {
    "family": "Poppins",
    "license": "OFL",
    "designer": "Indian Type Foundry, Jonny Pinhorn, Ninad Kale",
    "source": "https://github.com/google/fonts/tree/main/ofl/poppins",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "poppins-normal-400.woff2",
        "style": "normal",
        "weight": "400",
        "axes": [],
        "bytes": 7884
      },
      {
        "file": "poppins-normal-500.woff2",
        "style": "normal",
        "weight": "500",
        "axes": [],
        "bytes": 7748
      },
      {
        "file": "poppins-normal-600.woff2",
        "style": "normal",
        "weight": "600",
        "axes": [],
        "bytes": 8000
      },
      {
        "file": "poppins-normal-700.woff2",
        "style": "normal",
        "weight": "700",
        "axes": [],
        "bytes": 7816
      }
    ]
  },
  "playfair-display": {
    "family": "Playfair Display",
    "license": "OFL",
    "designer": "Claus Eggers Sørensen",
    "source": "https://github.com/google/fonts/tree/main/ofl/playfairdisplay",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "playfair-display-normal-400-900.woff2",
        "style": "normal",
        "weight": "400 900",
        "axes": [
          "wght 400–900"
        ],
        "bytes": 38404
      }
    ]
  },
  "lora": {
    "family": "Lora",
    "license": "OFL",
    "designer": "Cyreal",
    "source": "https://github.com/google/fonts/tree/main/ofl/lora",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "lora-normal-400-700.woff2",
        "style": "normal",
        "weight": "400 700",
        "axes": [
          "wght 400–700"
        ],
        "bytes": 37788
      }
    ]
  },
  "dm-sans": {
    "family": "DM Sans",
    "license": "OFL",
    "designer": "Colophon Foundry",
    "source": "https://github.com/google/fonts/tree/main/ofl/dmsans",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "dm-sans-normal-100-1000.woff2",
        "style": "normal",
        "weight": "100 1000",
        "axes": [
          "opsz 9–40",
          "wght 100–1000"
        ],
        "bytes": 62724
      }
    ]
  },
  "space-grotesk": {
    "family": "Space Grotesk",
    "license": "OFL",
    "designer": "Florian Karsten",
    "source": "https://github.com/google/fonts/tree/main/ofl/spacegrotesk",
    "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    "files": [
      {
        "file": "space-grotesk-normal-300-700.woff2",
        "style": "normal",
        "weight": "300 700",
        "axes": [
          "wght 300–700"
        ],
        "bytes": 22288
      }
    ]
  }
};

/** Total bytes of every self-hosted brand font file. */
export const BRAND_FONT_TOTAL_BYTES = 1237256;
