import React,{act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {MemoryRouter,Routes,Route,useLocation,useNavigationType} from 'react-router-dom';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {SalesWorkspace} from './SalesWorkspace';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const fixture=vi.hoisted(()=>({data:{phase:'ready',tenantId:'test-tenant-a',pipelineWorkspace:{canManage:true,pipelines:[{id:'p1',name:'Client work',lifecycleStatus:'active'},{id:'p2',name:'Partnerships',lifecycleStatus:'active'}],stages:[{id:'s1',pipelineId:'p1',label:'Review',archivedAt:null},{id:'s2',pipelineId:'p2',label:'Discuss',archivedAt:null}],deals:[{id:'d1',pipelineId:'p1',stageId:'s1',title:'Alpha brief',clientName:'Example A',owner:'Owner',createdAt:new Date().toISOString(),status:'open',nextAction:'Review'},{id:'d2',pipelineId:'p2',stageId:'s2',title:'Beta brief',clientName:'Example B',owner:'Owner',createdAt:new Date().toISOString(),status:'open',nextAction:'Discuss'}]},submissions:[],retry:vi.fn()}}));
vi.mock('./useSoloCampaigns',()=>({useSoloCampaigns:()=>fixture.data}));
vi.mock('./growth2',()=>({DetailDrawer:()=>null,PipelineSurface:({data,dealFilter,selectedPipelineId,focusDealId,createRequested}:{data:typeof fixture.data;dealFilter:(deal:typeof fixture.data.pipelineWorkspace.deals[number])=>boolean;selectedPipelineId:string|null;focusDealId:string|null;createRequested:boolean})=><div data-testid="board" data-pipeline={selectedPipelineId} data-deal={focusDealId} data-create={String(createRequested)}>{data.pipelineWorkspace.deals.filter(dealFilter).map(d=><span key={d.id}>{d.title}</span>)}</div>}));
vi.mock('./catalog-offers',()=>({CatalogOffers:()=>null}));vi.mock('./sales-ops',()=>({SalesOps:()=>null}));vi.mock('./analytics2',()=>({Analytics2:()=>null}));vi.mock('./sales/SalesOverview',()=>({SalesOverview:()=>null}));vi.mock('./sales/collections/CollectionsWorkspace',()=>({CollectionsWorkspace:()=>null}));
function Address(){const l=useLocation(),kind=useNavigationType();return <output data-address data-navigation-type={kind}>{l.pathname+l.search+l.hash}</output>}
let host:HTMLDivElement,root:Root;
beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host)});afterEach(()=>{act(()=>root.unmount());host.remove()});
const render=async(url:string)=>act(async()=>root.render(<MemoryRouter initialEntries={[url]}><Routes><Route path="/solo/:account/*" element={<><SalesWorkspace/><Address/></>}/></Routes></MemoryRouter>));
const click=async(name:string)=>act(async()=>{[...host.querySelectorAll('button')].find(b=>b.textContent===name)!.click()});
it('renders six main tabs and List/Board views of one canonical deal source',async()=>{await render('/solo/test/sales/opportunities');expect([...host.querySelectorAll('[role="tab"]')].map(e=>e.textContent)).toEqual(['Overview','Opportunities','Offers','Terms & Agreements','Payments','Performance']);expect(host.querySelectorAll('tbody tr')).toHaveLength(2);await click('Board');expect(host.querySelector('[data-testid="board"]')?.textContent).toContain('Alpha brief');await click('List');expect(host.querySelectorAll('tbody tr')).toHaveLength(2)});
it('preserves shared search/stage/date/pipeline context through both representations',async()=>{await render('/solo/test/sales/opportunities?search=Alpha&stage=s1&period=7d&pipeline=p1');expect(host.querySelectorAll('tbody tr')).toHaveLength(1);await click('Board');expect(host.querySelector('[data-testid="board"]')?.textContent).toBe('Alpha brief');expect(host.querySelector('[data-address]')?.textContent).toContain('stage=s1');expect(host.querySelector('[data-address]')?.textContent).toContain('period=7d');await click('List');expect(host.querySelectorAll('tbody tr')).toHaveLength(1)});
it('replaces a legacy pipeline address while preserving deal/new/query/hash intent',async()=>{await render('/solo/test/sales/pipeline?deal=d1&new=opportunity&period=7d&search=Alpha#record');expect(host.querySelector('[data-address]')?.textContent).toBe('/solo/test/sales/opportunities?deal=d1&new=opportunity&period=7d&search=Alpha&view=board#record');expect(host.querySelector('[data-testid="board"]')?.getAttribute('data-deal')).toBe('d1');expect(host.querySelector('[data-testid="board"]')?.getAttribute('data-create')).toBe('true');expect(host.querySelector('[data-address]')?.getAttribute('data-navigation-type')).toBe('REPLACE')});
it('opens the selected list record in its canonical pipeline without clearing filters',async()=>{await render('/solo/test/sales/opportunities?search=Beta&period=7d');await click('Beta brief');expect(host.querySelector('[data-testid="board"]')?.getAttribute('data-pipeline')).toBe('p2');expect(host.querySelector('[data-address]')?.textContent).toContain('deal=d2');expect(host.querySelector('[data-address]')?.textContent).toContain('search=Beta')});
