import React from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Route, Routes, useParams } from "react-router-dom";
import { ThemeProvider } from "next-themes";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { AgentPresenceProvider } from "@/components/ui/paige/AgentPresenceContext";
import { TenantCommandCenterShell } from "@/components/tenant-shell/TenantCommandCenterShell";
import { GrowthHub } from "@/solo/growth2";
import { SalesWorkspace } from "@/solo/SalesWorkspace";
import { setAgreementsHarnessMode } from "../sales-mount/useSoloCommercialTerms-stub";
import { setSigningsHarnessMode } from "../sales-mount/useSoloAgreementSignings-stub";
import { setSalesHarnessMode } from "../sales-mount/useSoloSalesOps-stub";
import "@/index.css";
import "@/solo/solo-tokens.css";
(globalThis as { __React?: typeof React }).__React = React;
function CutoverOwner() { const route=useParams(); return route["*"].startsWith("growth") ? <GrowthHub/> : <SalesWorkspace accountContext={{accountName:"Synthetic test workspace",accountType:"standalone"}} accountEpoch="harness-tenant"/>; }
const params = new URLSearchParams(location.search);
const theme = params.get("theme") === "dark" ? "dark" : "light";
setAgreementsHarnessMode("populated"); setSigningsHarnessMode("populated"); setSalesHarnessMode("populated");
localStorage.setItem("paige.agentRail.collapsed", String(params.get("paige") !== "open"));
localStorage.setItem("paige.tenantShell.navExpanded", "true");
const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
createRoot(document.getElementById("root")!).render(<QueryClientProvider client={client}><ThemeProvider attribute="class" defaultTheme={theme} storageKey={`sales-domain-review-${theme}`} enableSystem={false}><AgentPresenceProvider launcherEnabled={false} hasChatBody={false}><BrowserRouter><TenantCommandCenterShell accountName="Synthetic test workspace" accountType="standalone" userRole="admin" onSignOut={() => undefined} soloPaigeWorkspace={<div style={{ padding: 16 }}>PAIGE review slot · transport unavailable</div>}><main className="paige-solo" data-theme={theme} data-solo-screen-host style={{ height: "100%", minHeight: 0, minWidth: 0 }}><Routes><Route path="/solo/:account/*" element={<CutoverOwner/>}/></Routes></main></TenantCommandCenterShell><span data-harness-chrome style={{ position: "fixed", bottom: 0, left: 0, fontSize: 10 }}>LOCAL FIXTURES · AUTH/PROVIDERS UNVERIFIED</span></BrowserRouter></AgentPresenceProvider></ThemeProvider></QueryClientProvider>);
