SET ROLE service_role;
DELETE FROM public.extract_test WHERE name='new';
INSERT INTO public.extract_test VALUES('new',public.test_extract(gen_random_uuid()),NULL);
UPDATE public.extract_test SET started=public.start_knowledge_extraction((result->>'work_id')::uuid) WHERE name='new';
SELECT public.complete_knowledge_extraction((result->>'work_id')::uuid,started->>'server_key',1,1,'Neutral extracted text',started->>'input_hash') FROM public.extract_test WHERE name='new';
RESET ROLE;
-- Uses actual extraction setup from extraction-behavior.sql.
CREATE FUNCTION public.test_review(n text) RETURNS jsonb LANGUAGE sql AS $$ SELECT public.read_tenant_knowledge_pending('00000000-0000-0000-0000-000000000001',(SELECT (result->>'document_id')::uuid FROM public.extract_test WHERE name=n)) $$;
CREATE FUNCTION public.test_save(n text,r integer,c text DEFAULT 'Reviewed exact text') RETURNS jsonb LANGUAGE sql AS $$ SELECT public.save_tenant_knowledge_review('00000000-0000-0000-0000-000000000001',(SELECT (result->>'document_id')::uuid FROM public.extract_test WHERE name=n),(SELECT (result->>'work_id')::uuid FROM public.extract_test WHERE name=n),r,c,'{"title":"Reviewed title","summary":"Reviewed summary","category":"Reviewed category","tags":["reviewed"]}') $$;
CREATE FUNCTION public.test_discard(n text,r integer) RETURNS jsonb LANGUAGE sql AS $$ SELECT public.discard_tenant_knowledge_review('00000000-0000-0000-0000-000000000001',(SELECT (result->>'document_id')::uuid FROM public.extract_test WHERE name=n),(SELECT (result->>'work_id')::uuid FROM public.extract_test WHERE name=n),r) $$;
SELECT set_config('test.actor','10000000-0000-0000-0000-000000000001',false);
SET ROLE authenticated;
SELECT public.test_assert(public.test_review('new')->>'extraction_outcome'='capability_succeeded','real extraction receipt visible');
SELECT public.test_assert(public.test_review('replacement')->>'extraction_outcome'='capability_completed_unrecorded','missing extraction receipt distinct');
SELECT public.test_assert(NOT (public.test_review('new')->'work') ? 'terminal_outcome' AND NOT public.test_review('new') ? 'extraction_input','raw work and intake payload hidden');
SELECT public.test_denied('SELECT pending_review_metadata FROM public.tenant_knowledge_docs','permission denied');
SELECT public.test_denied('UPDATE public.tenant_knowledge_docs SET last_review_operation=NULL','permission denied');
SELECT public.test_denied($q$SELECT public.list_tenant_knowledge_pending('00000000-0000-0000-0000-000000000001',NULL,51)$q$,'KNOWLEDGE_LIMIT_INVALID');
SELECT public.test_denied($q$SELECT public.list_tenant_knowledge_pending('00000000-0000-0000-0000-000000000002',NULL,20)$q$,'KNOWLEDGE_SCOPE_CHANGED');
SELECT public.test_assert(public.test_save('new',2)->>'revision'='3','review save advances CAS once');
SELECT public.test_assert(public.test_review('new')->'pending_review'->>'reviewed_content'='Reviewed exact text' AND public.test_review('new')->'pending_review'->>'extracted_content'='Neutral extracted text','save retains immutable extracted source');
SELECT public.test_assert(public.test_review('new')->'pending_review_metadata'->>'title'='Reviewed title','staged metadata readback');
SELECT public.test_denied($q$SELECT public.test_save('new',2)$q$,'KNOWLEDGE_REVISION_CONFLICT');
SELECT public.test_denied($q$SELECT public.test_save('new',3,'')$q$,'KNOWLEDGE_REVIEW_INVALID');
SELECT public.test_denied(format('SELECT public.save_tenant_knowledge_review(%L,%L,%L,3,%L,%L::jsonb)','00000000-0000-0000-0000-000000000001',(SELECT result->>'document_id' FROM public.extract_test WHERE name='new'),(SELECT result->>'work_id' FROM public.extract_test WHERE name='new'),'text','{"title":"x","summary":null,"category":null,"tags":[],"share_to_network":true}'),'KNOWLEDGE_REVIEW_INVALID');
SELECT public.test_denied(format('SELECT public.save_tenant_knowledge_review(%L,%L,%L,3,%L,%L::jsonb)','00000000-0000-0000-0000-000000000001',(SELECT result->>'document_id' FROM public.extract_test WHERE name='new'),(SELECT result->>'work_id' FROM public.extract_test WHERE name='replacement'),'text','{"title":"x","summary":null,"category":null,"tags":[]}'),'KNOWLEDGE_REVISION_CONFLICT');
SELECT public.test_denied($q$SELECT public.test_save('new',3,repeat('a',480001))$q$,'KNOWLEDGE_REVIEW_INVALID');
SELECT public.test_assert(public.test_save('replacement',3)->>'revision'='4','replacement review saved');
RESET ROLE;
SELECT public.test_assert((SELECT title='A' AND content='private A' AND summary IS NULL AND source_binding IS NULL FROM public.tenant_knowledge_docs WHERE id='20000000-0000-0000-0000-000000000001'),'replacement canonical metadata content source unchanged');
SELECT public.test_assert((SELECT content='A chunk' FROM public.tenant_knowledge_chunks WHERE doc_id='20000000-0000-0000-0000-000000000001'),'replacement chunks unchanged');
SELECT set_config('test.receipt_fail','true',false);
SET ROLE authenticated;
SELECT public.test_assert(public.test_save('replacement',4)->>'outcome'='capability_completed_unrecorded','save survives receipt failure honestly');
SELECT public.test_assert(public.test_review('replacement')->'last_review_operation'->>'outcome'='capability_completed_unrecorded','save receipt failure visible on revisit');
RESET ROLE;
SELECT set_config('test.receipt_fail','false',false);
SELECT set_config('test.actor','10000000-0000-0000-0000-000000000004',false);
SET ROLE authenticated;
SELECT public.test_assert(jsonb_array_length(public.list_tenant_knowledge_pending('00000000-0000-0000-0000-000000000001',NULL,20)->'items')=0,'ordinary member cannot discover another members jobs');
SELECT public.test_denied($q$SELECT public.test_review('new')$q$,'KNOWLEDGE_REVIEW_UNAVAILABLE');
SELECT public.test_denied($q$SELECT public.test_save('new',3)$q$,'KNOWLEDGE_SCOPE_CHANGED');
RESET ROLE;
UPDATE public.tenant_members SET is_owner=true WHERE user_id='10000000-0000-0000-0000-000000000004';
SET ROLE authenticated;
SELECT public.test_assert(public.test_review('new')->>'document_id' IS NOT NULL,'active owner flag retains visibility');
RESET ROLE;
UPDATE public.tenant_members SET status='inactive' WHERE user_id='10000000-0000-0000-0000-000000000004';
SET ROLE authenticated;
SELECT public.test_denied($q$SELECT public.test_review('new')$q$,'KNOWLEDGE_SCOPE_CHANGED');
RESET ROLE;
UPDATE public.tenant_members SET status='active',is_owner=false WHERE user_id='10000000-0000-0000-0000-000000000004';
SELECT set_config('test.actor','10000000-0000-0000-0000-000000000001',false);
UPDATE public.profiles SET active_tenant_id=NULL WHERE user_id=auth.uid();
SET ROLE authenticated;
SELECT public.test_denied($q$SELECT public.test_review('new')$q$,'KNOWLEDGE_SCOPE_CHANGED');
RESET ROLE;
UPDATE public.profiles SET active_tenant_id='00000000-0000-0000-0000-000000000001' WHERE user_id=auth.uid();
UPDATE auth.users SET banned_until=now()+interval '1 hour' WHERE id=auth.uid();
SET ROLE authenticated;
SELECT public.test_denied($q$SELECT public.test_save('new',3)$q$,'KNOWLEDGE_SCOPE_CHANGED');
RESET ROLE;
UPDATE auth.users SET banned_until=NULL WHERE id=auth.uid();
SET ROLE authenticated;
SELECT public.test_denied($q$SELECT public.test_discard('changed',2)$q$,'KNOWLEDGE_DISCARD_IN_FLIGHT');
SELECT public.test_assert(public.test_discard('replacement',5)->>'document_removed'='false','discard replacement clears pending only');
SELECT public.test_assert(public.test_review('replacement')->'last_review_operation'->>'operation'='review_discarded' AND public.test_review('replacement')->'pending_review'='null'::jsonb,'discard replacement readback is attributable only via operation reference');
SELECT public.test_assert(public.test_discard('new',3)->>'document_removed'='true','discard draft verified removal');
SELECT public.test_denied($q$SELECT public.test_review('new')$q$,'KNOWLEDGE_NOT_FOUND');
SELECT public.test_denied($q$SELECT public.test_discard('new',3)$q$,'KNOWLEDGE_NOT_FOUND');
RESET ROLE;
SELECT public.test_assert((SELECT status='succeeded' AND terminal_outcome->>'phase'='awaiting_review' FROM public.paige_durable_work WHERE id=(SELECT (result->>'work_id')::uuid FROM public.extract_test WHERE name='new')),'discard preserves succeeded native history');
SELECT public.test_assert((SELECT title='A' AND content='private A' AND pending_review IS NULL AND extraction_work_id IS NULL FROM public.tenant_knowledge_docs WHERE id='20000000-0000-0000-0000-000000000001'),'discard preserves published replacement content');
SET ROLE service_role;
SELECT public.test_denied($q$SELECT public.list_tenant_knowledge_pending('00000000-0000-0000-0000-000000000001',NULL,20)$q$,'permission denied');
RESET ROLE;
SET ROLE anon;
SELECT public.test_denied($q$SELECT public.test_review('replacement')$q$,'permission denied');
RESET ROLE;
-- >100 native documents, stable exclusive cursor, bounded summaries only.
SET ROLE service_role;
INSERT INTO public.extract_test SELECT 'page'||n,public.test_extract(gen_random_uuid()),NULL FROM generate_series(1,105)n;
RESET ROLE;
CREATE TABLE public.manage_pages(id uuid PRIMARY KEY);
GRANT ALL ON public.manage_pages TO authenticated;
SET ROLE authenticated;
DO $$ DECLARE cursor_id uuid; page jsonb; n integer:=0; BEGIN LOOP
 page:=public.list_tenant_knowledge_pending('00000000-0000-0000-0000-000000000001',cursor_id,20);
 PERFORM public.test_assert(jsonb_array_length(page->'items')<=20,'bounded discovery page');
 INSERT INTO public.manage_pages SELECT (x->>'document_id')::uuid FROM jsonb_array_elements(page->'items') x;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(page->'items') x WHERE x ? 'pending_review' OR x ? 'source_binding') THEN RAISE EXCEPTION 'discovery exposed content'; END IF;
 n:=n+1; cursor_id:=(page->>'next_cursor')::uuid; EXIT WHEN cursor_id IS NULL; IF n>20 THEN RAISE EXCEPTION 'cursor loop'; END IF;
 END LOOP; PERFORM public.test_assert((SELECT count(*)>=105 FROM public.manage_pages),'discovery revisits over 100 without duplicates'); END $$;
RESET ROLE;

-- Terminal failure discard preserves immutable history, including lost receipt acknowledgement.
SET ROLE service_role;
INSERT INTO public.extract_test VALUES('failed_discard',public.test_extract(gen_random_uuid()),NULL);
UPDATE public.extract_test SET started=public.start_knowledge_extraction((result->>'work_id')::uuid) WHERE name='failed_discard';
SELECT public.settle_knowledge_extraction_failure((result->>'work_id')::uuid,started->>'server_key',1,'source_unavailable',false) FROM public.extract_test WHERE name='failed_discard';
RESET ROLE;
CREATE TEMP TABLE failed_before AS SELECT status,terminal_outcome FROM public.paige_durable_work WHERE id=(SELECT (result->>'work_id')::uuid FROM public.extract_test WHERE name='failed_discard');
SELECT set_config('test.receipt_fail','true',false);
SET ROLE authenticated;
SELECT public.test_assert(public.test_discard('failed_discard',1)->>'outcome'='capability_completed_unrecorded','discard receipt failure retains truthful outcome');
RESET ROLE;
SELECT set_config('test.receipt_fail','false',false);
SELECT public.test_assert((SELECT (w.status,w.terminal_outcome)=(b.status,b.terminal_outcome) FROM public.paige_durable_work w,failed_before b WHERE w.id=(SELECT (result->>'work_id')::uuid FROM public.extract_test WHERE name='failed_discard')),'failed terminal outcome unchanged by discard');
-- Existing company operator is scoped to its selected company; another company fails.
SELECT set_config('test.actor','10000000-0000-0000-0000-000000000002',false);
SET ROLE authenticated;
SELECT public.test_assert(public.list_tenant_knowledge_pending('00000000-0000-0000-0000-000000000003',NULL,20)->>'tenant_id'='00000000-0000-0000-0000-000000000003','company operator selected scope');
SELECT public.test_denied($q$SELECT public.list_tenant_knowledge_pending('00000000-0000-0000-0000-000000000004',NULL,20)$q$,'KNOWLEDGE_SCOPE_CHANGED');
RESET ROLE;
SELECT set_config('test.actor','10000000-0000-0000-0000-000000000001',false);
