import {describe,it,expect,vi,afterEach} from 'vitest';
import {pdfEmailAttachment,attachmentMime} from './email-attachments.ts';
import {gmailSend} from './gmail.ts';
afterEach(()=>vi.unstubAllGlobals());
describe('server PDF attachment transport',()=>{
 it('produces exact binary base64 and safe customer filename without draft identifiers',()=>{const bytes=new TextEncoder().encode('%PDF-1.7\nfixture');const a=pdfEmailAttachment(bytes,'DRAFT-private-id');expect(atob(a.content)).toBe(new TextDecoder().decode(bytes));expect(a.filename).toBe('invoice-document.pdf');const mime=attachmentMime('<p>Invoice</p>','text/html; charset=UTF-8',[a]);const boundary=mime.contentType.match(/boundary="([^"]+)"/)![1];expect(mime.body).toContain(`--${boundary}--`);expect(mime.body).toContain('Content-Disposition: attachment; filename="invoice-document.pdf"');expect(mime.body).toContain(a.content);});
 it('never substitutes HTML for PDF, injects filename headers or changes ordinary email bodies',()=>{expect(()=>pdfEmailAttachment(new TextEncoder().encode('<html>not PDF'),'INV-1')).toThrow();expect(attachmentMime('hello','text/plain',[])).toEqual({body:'hello',contentType:'text/plain'});expect(()=>attachmentMime('body','text/plain',[{filename:'x\r\nBcc: attacker.pdf',content:'JVBERi0=',contentType:'application/pdf'}])).toThrow();});
 it('Gmail posts a multipart PDF with exact decoded bytes and retains provider receipt',async()=>{const attachment=pdfEmailAttachment(new TextEncoder().encode('%PDF-1.7\nexact binary'),'INV-42');let raw='';vi.stubGlobal('fetch',async(_url:unknown,options:RequestInit)=>{raw=JSON.parse(String(options.body)).raw;return new Response(JSON.stringify({id:'provider-message'}),{status:200})});const result=await gmailSend('synthetic-token',{from:'business@example.test',to:'customer@example.test',subject:'Invoice INV-42',html:'<p>Invoice</p>',attachments:[attachment]});const message=atob(raw.replace(/-/g,'+').replace(/_/g,'/'));expect(message).toContain('Content-Type: multipart/mixed');expect(message).toContain('filename="invoice-INV-42.pdf"');expect(message).toContain(attachment.content);expect(result.data?.id).toBe('provider-message');});
 it('ordinary Gmail email remains a single HTML part',async()=>{let raw='';vi.stubGlobal('fetch',async(_url:unknown,options:RequestInit)=>{raw=JSON.parse(String(options.body)).raw;return new Response(JSON.stringify({id:'ordinary-message'}),{status:200})});await gmailSend('synthetic-token',{from:'business@example.test',to:'customer@example.test',subject:'Hello',html:'<p>Hello</p>'});const message=atob(raw.replace(/-/g,'+').replace(/_/g,'/'));expect(message).toContain('Content-Type: text/html');expect(message).not.toContain('multipart/mixed');});
});
