import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route} from 'react-router-dom';
import {ThemeProvider} from 'next-themes';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {AgentPresenceProvider} from '@/components/ui/paige/AgentPresenceContext';
import {TenantCommandCenterShell} from '@/components/tenant-shell/TenantCommandCenterShell';
import {SalesWorkspace} from '@/solo/SalesWorkspace';
import {setAgreementsHarnessMode} from '../sales-mount/useSoloCommercialTerms-stub';
import {setSigningsHarnessMode} from '../sales-mount/useSoloAgreementSignings-stub';
import {setSalesHarnessMode} from '../sales-mount/useSoloSalesOps-stub';
import '@/index.css';
import '@/solo/solo-tokens.css';
import '@/solo/sales/sales-billing.css';
setAgreementsHarnessMode('populated');setSigningsHarnessMode('populated');setSalesHarnessMode('populated');
const params=new URLSearchParams(location.search),theme=params.get('theme')==='dark'?'dark':'light';
localStorage.setItem('paige.agentRail.collapsed',String(params.get('paige')!=='open'));localStorage.setItem('paige.tenantShell.navExpanded','true');
(globalThis as {__React?:typeof React}).__React=React;
const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={client}><ThemeProvider attribute="class" defaultTheme={theme} storageKey={`collections-review-${theme}`} enableSystem={false}><AgentPresenceProvider launcherEnabled={false} hasChatBody={false}><BrowserRouter><TenantCommandCenterShell accountName="Synthetic Collections workspace" accountType="standalone" userRole="admin" onSignOut={()=>undefined} soloPaigeWorkspace={<div style={{padding:16}}>Synthetic PAIGE slot · no transport</div>}><main className="paige-solo" data-theme={theme} style={{height:'100%',minHeight:0,minWidth:0,display:'flex',flexDirection:'column'}}><Routes><Route path="/solo/:account/*" element={<SalesWorkspace accountContext={{accountName:"Synthetic Collections workspace",accountType:"standalone"}} accountEpoch="collections-fixture"/>}/></Routes></main></TenantCommandCenterShell><span style={{position:'fixed',bottom:0,left:0,fontSize:10,background:'#eeeafd',color:'#362666',padding:3,zIndex:100}}>SYNTHETIC COMPONENT FIXTURE · AUTH / PROVIDERS UNVERIFIED</span></BrowserRouter></AgentPresenceProvider></ThemeProvider></QueryClientProvider>);
