// C4a — ONE RESUME MODEL for a paused objective (docs/delivery/paige-conversational-loop-c4.md).
//
// WAIT_APPROVAL, ASK_USER and WAIT_WORK are three reasons one objective paused, not three workflow
// systems. This module is the pure half of resuming it; the chat handler (`paige-ai-chat`) does the
// IO. C4a ships the APPROVAL kind: when the person approves a stored proposal, the server carries
// the exact approved act forward — rebuilt from the stored row, never regenerated by the model —
// runs it once through the existing gate, and then lets PAIGE continue the same objective.
//
// WHAT THIS MODULE NEVER DOES, so the authority story stays in one place:
//  - it grants nothing. A synthetic call is only a CALL; the existing gate still decides, the
//    existing compare-and-set claim on `consumed_at` still makes it exactly-once, and the stored
//    arguments still overwrite whatever the call carried;
//  - it reads no request field for authority. The row it is handed was selected by the handler
//    under the caller's own user, tenant, thread and client scope;
//  - it writes no prose into a turn record. `turn_state.resumed` is a closed enum; the per-act
//    outcomes live beside it in `bundle_ref.paige_resume` as closed enums and the caller's own
//    tool names (already on the same row in `paige_confirm`).
//
// Pure TypeScript with no Deno API and no runtime imports beyond the sibling outcome module, so
// Deno, Node (the authz harness) and vitest all load it.

import {
  APPROVAL_OUTCOME_SENTENCES,
  classifySpentApproval,
  classifyUnspentApproval,
  settleUsedEarlier,
  type ApprovalOutcomeKind,
  type ApprovalRefusalReason,
} from "../approval-outcome.ts";

import { RESUME_KINDS, type ResumeKind } from "./contract.ts";
export { RESUME_KINDS, type ResumeKind };

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const SCOPED_TOKEN = /^([0-9a-f]{16}):([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/;
const OUTCOMES: readonly ApprovalOutcomeKind[] = ["ran", "not_run", "unconfirmed"];

/**
 * A card token the server issued for a thread-scoped proposal: `<16-hex scoped fingerprint>:<uuid
 * of the request that minted it>`. A bare 16-hex token is a pre-scoping legacy row or a door's
 * own proposal; neither is resumed here (doors are C4b) and both keep the model-re-emit path.
 */
export function parseScopedToken(token: string): { fingerprint: string; nonce: string } | null {
  const m = typeof token === "string" ? SCOPED_TOKEN.exec(token) : null;
  return m ? { fingerprint: m[1], nonce: m[2] } : null;
}

/**
 * The tool-call id the resumed act runs under. Deterministic per approval, so a receipt keyed on it
 * (`stableRunId(...tc.id)`) is one per approval rather than one per request; and inside the
 * provider's id alphabet (`^[A-Za-z0-9_-]+$` for Anthropic tool_use ids — a ":" would be rejected
 * when the call is replayed to the model as conversation history).
 */
export function resumeCallId(token: string): string {
  return `resume_${String(token).replace(/[^A-Za-z0-9_-]/g, "_")}`;
}

/** A stored proposal row, as the handler selected it. */
export interface StoredProposal {
  tool_name: string;
  args: Record<string, unknown>;
}

/** The synthetic tool call that carries the stored act into the existing dispatch. */
export interface ResumeCall {
  id: string;
  type: "function";
  function: { name: string; arguments: string };
}

/** Rebuild the approved act from its stored row. The model never authors these arguments. */
export function buildResumeCall(token: string, row: StoredProposal): ResumeCall {
  return {
    id: resumeCallId(token),
    type: "function",
    function: { name: row.tool_name, arguments: JSON.stringify(row.args ?? {}) },
  };
}

/**
 * Which stored rows C4a may carry forward: a governed write that reaches the general gate. A door
 * tool (CRM, Sales, publish) claims its own proposals through its door — those are C4b — and a tool
 * that is not a governed write would skip the gate entirely, so it is never resumed (it would run
 * without spending the approval).
 */
export function isResumableTool(
  tool: unknown,
  sets: { mutating: ReadonlySet<string>; doorTools: ReadonlyArray<ReadonlySet<string>> },
): tool is string {
  if (typeof tool !== "string" || !tool) return false;
  if (!sets.mutating.has(tool)) return false;
  return !sets.doorTools.some((s) => s.has(tool));
}

/**
 * What a stored proposal row says about itself, read from its own two timestamps.
 *  - `live`: unused and still inside its window.
 *  - `expired`: its window closed before anything used it. Two shapes: unused and past `expires_at`,
 *    or stamped consumed AT OR AFTER `expires_at` — the expiry sweep in `recordConfirmation` stamps
 *    `consumed_at` only on rows already past their window (`lte expires_at`), while the claim and the
 *    decline only ever stamp a row still inside it (`gt expires_at`), so the sweep is the only writer
 *    that can produce that shape. Nothing ran.
 *  - `used`: consumed inside its window — by a claim (it may have run) or a decline.
 * An unreadable timestamp reads as `used` when the row is consumed (the cautious "check first"), and
 * as `expired` when it is not (a row with no readable window is never run).
 */
export type StoredRowState = "live" | "expired" | "used";
export function storedRowState(
  row: { consumed_at?: unknown; expires_at?: unknown },
  nowMs: number,
): StoredRowState {
  const expires = typeof row.expires_at === "string" ? Date.parse(row.expires_at) : NaN;
  const consumed = typeof row.consumed_at === "string" && row.consumed_at ? Date.parse(row.consumed_at) : null;
  if (consumed !== null) return Number.isFinite(consumed) && Number.isFinite(expires) && consumed >= expires ? "expired" : "used";
  return Number.isFinite(expires) && expires > nowMs ? "live" : "expired";
}

/**
 * The system note a resume turn adds, and ONLY a resume turn. Rule 1 of the standing prompt is
 * neutral (an approval turn the server did not carry forward has no result to point at — a door
 * proposal, a legacy token, a resume that failed to resolve); this note is what tells PAIGE that on
 * THIS turn the approved act was attempted before she was asked anything. It names no outcome: the
 * act's own tool result says whether it ran, was refused, or could not be confirmed.
 */
export const RESUME_TURN_NOTE = "THIS TURN CARRIES AN APPROVAL FORWARD. Before you were asked anything, the platform took the action the person just approved, exactly as it was stored when they saw the card, and put it through the approval gate itself. What happened is the tool result for that call, already in this conversation — it may have run, been refused, or be impossible to confirm; read it, do not assume. Do not call that action again and do not ask for its approval again. Tell the person plainly what the result says (success words only if it says it succeeded), then carry on with what they originally asked for.";

/**
 * The keys the gate SETTLES on a call that arrives without them (a fresh `request_key` /
 * `idempotency_key`). Two calls that differ only in a settled key are the same act, so they are
 * left out when asking "did the model just re-emit the act that already ran?". `confirm` and
 * `confirm_token` are never identity either (confirm-fingerprint.ts).
 */
const SETTLED_KEYS = new Set(["confirm", "confirm_token", "request_key", "idempotency_key"]);

/** The arguments that make two calls the same act, for the re-emit refusal. Key order is irrelevant. */
export function actIdentityArgs(args: Record<string, unknown> | null | undefined): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(args ?? {})) if (!SETTLED_KEYS.has(k)) out[k] = v;
  return out;
}

/**
 * What became of ONE resumed approval, in the existing closed outcome vocabulary. The same reading
 * goes to the card on the wire (`paige_approval_outcome`) and into the turn's record, so the wire,
 * the saved thread and a reload can never disagree about it.
 *  - spent: the claim succeeded and the stored act ran; its own result decides done / didn't run /
 *    couldn't confirm (classifySpentApproval — never optimism).
 *  - lost: the row was live when this request selected it, and the claim then found it already
 *    used — another request (a second click, another tab) got there first, and may have done the
 *    work. "Couldn't confirm / can't be used any more", never "didn't run".
 *  - expired: the proposal's window closed before it was approved. Nothing ran.
 *  - withheld: the approved tool is not offered on this turn any more. Nothing ran, nothing spent.
 *  - otherwise a gate refused it before any claim (autonomy off, the workspace role, the scope),
 *    and nothing ran.
 */
export function classifyResumedApproval(input: {
  spentContent?: string | undefined;
  spent: boolean;
  lost?: boolean;
  expired?: boolean;
  /** The approved tool is not one this turn offers (the manifest, a Studio scope, a preset or a tier
   *  narrowed since the card was shown): it was not run and the approval was not spent. */
  withheld?: boolean;
  refusal?: ApprovalRefusalReason;
  reportsOk?: boolean;
}) {
  if (input.spent) return classifySpentApproval(input.spentContent, { reportsOk: input.reportsOk });
  if (input.lost) return settleUsedEarlier(classifyUnspentApproval(undefined), true);
  if (input.expired) return classifyUnspentApproval("expired");
  if (input.withheld) return classifyUnspentApproval("unclaimable");
  return classifyUnspentApproval(input.refusal);
}

/** One resumed act as the turn record keeps it: the caller's own tool name and a closed outcome. */
export interface ResumeOutcome {
  tool: string;
  outcome: ApprovalOutcomeKind;
}

/**
 * The approval card's report exactly as the wire carried it (`paige_approval_outcome`): the caller's
 * own card fingerprints, the closed outcome kinds, and sentences from the closed set only. Kept so a
 * reload rebuilds the same report card the person saw live, through the same client reader.
 */
export interface ResumeApprovalFrame {
  actions: Array<{ fingerprint: string; outcome: ApprovalOutcomeKind; note?: string }>;
  note?: string;
}

/** bundle_ref.paige_resume on the assistant turn that carried the objective forward. */
export interface ResumeRecord {
  kind: ResumeKind;
  /** The suspended assistant turn (the one that showed the card), when it could be found. */
  from_turn_id: string | null;
  outcomes: ResumeOutcome[];
  /** The card's report as sent on the wire, when one was sent before the turn was saved. */
  approval_outcome?: ResumeApprovalFrame;
}

const CARD_TOKEN = /^[0-9a-f]{16}(?::[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})?$/;

/** Read a report frame defensively: a token outside the card alphabet, a kind outside the set, or a
 *  sentence outside the closed set makes the whole frame unreadable (null), never partly trusted. */
export function readResumeApprovalFrame(value: unknown): ResumeApprovalFrame | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const o = value as Record<string, unknown>;
  if (!Array.isArray(o.actions)) return null;
  const actions: ResumeApprovalFrame["actions"] = [];
  for (const a of o.actions) {
    if (!a || typeof a !== "object") return null;
    const { fingerprint, outcome, note } = a as Record<string, unknown>;
    if (typeof fingerprint !== "string" || !CARD_TOKEN.test(fingerprint)) return null;
    if (!(OUTCOMES as readonly unknown[]).includes(outcome)) return null;
    if (note !== undefined && !(typeof note === "string" && APPROVAL_OUTCOME_SENTENCES.has(note))) return null;
    actions.push({ fingerprint, outcome: outcome as ApprovalOutcomeKind, ...(typeof note === "string" ? { note } : {}) });
  }
  if (o.note !== undefined && !(typeof o.note === "string" && APPROVAL_OUTCOME_SENTENCES.has(o.note))) return null;
  return { actions, ...(typeof o.note === "string" ? { note: o.note } : {}) };
}

const TOOL_NAME = /^[a-z][a-z0-9_]{0,63}$/;

/** Build the record. Throws on a value outside the contract — a bug, never a runtime input. */
export function resumeRecord(
  kind: ResumeKind,
  fromTurnId: string | null,
  outcomes: ResumeOutcome[],
  approvalFrame?: unknown,
): ResumeRecord {
  if (!(RESUME_KINDS as readonly string[]).includes(kind)) throw new Error(`paige_resume: kind outside the contract (${kind})`);
  if (fromTurnId !== null && !UUID.test(fromTurnId)) throw new Error("paige_resume: from_turn_id is not a turn id");
  for (const o of outcomes) {
    if (!TOOL_NAME.test(o.tool) || !OUTCOMES.includes(o.outcome)) throw new Error("paige_resume: outcome outside the contract");
  }
  const frame = approvalFrame === undefined || approvalFrame === null ? null : readResumeApprovalFrame(approvalFrame);
  if (approvalFrame !== undefined && approvalFrame !== null && !frame) throw new Error("paige_resume: approval report outside the contract");
  return {
    kind,
    from_turn_id: fromTurnId,
    outcomes: outcomes.map((o) => ({ tool: o.tool, outcome: o.outcome })),
    ...(frame ? { approval_outcome: frame } : {}),
  };
}

/** Read a persisted record defensively: anything outside the contract reads as none. */
export function readResumeRecord(value: unknown): ResumeRecord | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const o = value as Record<string, unknown>;
  if (!(RESUME_KINDS as readonly unknown[]).includes(o.kind)) return null;
  const from = o.from_turn_id;
  if (from !== null && !(typeof from === "string" && UUID.test(from))) return null;
  if (!Array.isArray(o.outcomes)) return null;
  const outcomes: ResumeOutcome[] = [];
  for (const e of o.outcomes) {
    if (!e || typeof e !== "object") return null;
    const { tool, outcome } = e as Record<string, unknown>;
    if (typeof tool !== "string" || !TOOL_NAME.test(tool) || !(OUTCOMES as readonly unknown[]).includes(outcome)) return null;
    outcomes.push({ tool, outcome: outcome as ApprovalOutcomeKind });
  }
  const frame = o.approval_outcome === undefined ? null : readResumeApprovalFrame(o.approval_outcome);
  if (o.approval_outcome !== undefined && !frame) return null;
  return { kind: o.kind as ResumeKind, from_turn_id: from as string | null, outcomes, ...(frame ? { approval_outcome: frame } : {}) };
}

/**
 * The suspended turn an approval resumes: the LATEST assistant turn in the thread whose card
 * (`bundle_ref.paige_confirm[].fingerprint`) carries one of the approved tokens. `turns` is newest
 * first. Null when none is found — the record then says so rather than guessing a turn.
 */
export function findSuspendedTurnId(
  turns: ReadonlyArray<{ id?: unknown; role?: unknown; bundle_ref?: unknown }>,
  tokens: ReadonlySet<string>,
): string | null {
  for (const t of turns) {
    if (t?.role !== "assistant" || typeof t.id !== "string" || !UUID.test(t.id)) continue;
    const cards = (t.bundle_ref as { paige_confirm?: unknown } | null)?.paige_confirm;
    if (!Array.isArray(cards)) continue;
    if (cards.some((c) => typeof (c as { fingerprint?: unknown })?.fingerprint === "string" && tokens.has((c as { fingerprint: string }).fingerprint))) {
      return t.id;
    }
  }
  return null;
}

/** The note PAIGE reads when a resumed act's approval was already used by another request. */
export const RESUME_LOST_RESULT = {
  success: false,
  refused_before_run: true,
  error: "approval_already_used",
  note: "This approval had already been used — most likely by another request a moment ago — so it did not run here. It may already have happened. Tell the operator to check before asking again, so nothing happens twice. Do not call this tool again in this reply.",
} as const;

/** The note PAIGE reads when a resumed act's proposal expired between selection and its claim. */
export const RESUME_EXPIRED_RESULT = {
  success: false,
  refused_before_run: true,
  error: "approval_expired",
  note: "Nothing ran: the approval expired before it could be used. Say so in one plain line, say nothing changed, and offer to propose it again if they still want it. Do not call this tool again in this reply.",
} as const;

/** The note PAIGE reads when a resumed act's claim could not run at all (the row is still live):
 *  nothing ran, and the card says "something went wrong on our side while checking your approval". */
export const RESUME_CHECK_UNAVAILABLE_RESULT = {
  success: false,
  refused_before_run: true,
  error: "approval_check_unavailable",
  note: "Nothing ran: the approval could not be checked right now. Say so in one plain line, say nothing changed, and do not call this tool again in this reply.",
} as const;

/** The note PAIGE reads when she re-emits an act the server already carried forward this reply. */
export const RESUME_ALREADY_HANDLED_RESULT = {
  success: false,
  refused_before_run: true,
  error: "already_handled_this_reply",
  note: "The person's approval already carried this exact action forward earlier in this reply — its result is the earlier tool result for it. It was not run again and no new approval was requested. Do not call it again; tell the operator what that earlier result says, then continue with what they originally asked for.",
} as const;
