import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import {readStripeMerchant} from './merchant.ts';
import * as onboarding from './merchant-onboarding.ts';
import * as command from './merchant-command.ts';
import {admitMerchantCommand} from './merchant-admission.ts';
import {merchantApprovalStore} from './merchant-approval-store.ts';
import {recordCapabilityRun} from '../capability-record.ts';
const tenant='10000000-0000-4000-8000-000000000001',actor='30000000-0000-4000-8000-000000000001',operation='20000000-0000-4000-8000-000000000001';
const source=readFileSync(new URL('../../tenant-stripe-connect/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?$/gm,'');
const js=transformSync(source,{loader:'ts',format:'esm'}).code;
type Row=Record<string,unknown>;
function fixture(initial:Row|null=null){
 const tables:Record<string,Row[]>={profiles:[{user_id:actor,active_tenant_id:tenant}],tenants:[{id:tenant,account_number:100}],tenant_stripe_accounts:initial?[{...initial}]:[],paige_pending_confirmations:[],paige_audit_log:[]};
 const calls:string[]=[],logs:unknown[]=[],receiptArgs:Row[]=[],creates:Row[]=[],queries:{table:string;op:string;filters:string[]}[]=[];
 let active=tenant,lane='confirm',receiptFails=false,auditFails=false,providerError:unknown=null,listError:unknown=null,recover=false,switchOnCreate=false;
 let onCreate:()=>Promise<void>=async()=>{};
 const account={id:'acct_fixture',metadata:{tenant_id:tenant},charges_enabled:true,payouts_enabled:true,details_submitted:true,capabilities:{card_payments:'active'},requirements:{disabled_reason:null}};
 class Query{
  filters:((row:Row)=>boolean)[]=[];names:string[]=[];op='select';values:Row={};count=100;singleRow=false;
  constructor(public table:string){}
  select(_columns:string){return this;} update(values:Row){this.op='update';this.values=values;return this;} insert(values:Row){this.op='insert';this.values=values;return this;}
  eq(key:string,value:unknown){this.names.push(`eq:${key}`);this.filters.push(r=>r[key]===value);return this;}
  is(key:string,_value:null){this.names.push(`is:${key}`);this.filters.push(r=>r[key]==null);return this;}
  not(key:string,_operator:string,_value:null){this.names.push(`not:${key}`);this.filters.push(r=>r[key]!=null);return this;}
  neq(key:string,value:string){this.names.push(`neq:${key}`);this.filters.push(r=>r[key]!==value);return this;}
  gt(key:string,value:string){this.names.push(`gt:${key}`);this.filters.push(r=>String(r[key])>value);return this;}
  lte(key:string,value:string){this.filters.push(r=>String(r[key])<=value);return this;}
  contains(key:string,value:Row){this.filters.push(r=>Object.entries(value).every(([k,v])=>(r[key] as Row)?.[k]===v));return this;}
  order(_key:string,_opts:unknown){return this;}limit(n:number){this.count=n;return this;}
  single(){this.singleRow=true;return this;}maybeSingle(){this.singleRow=true;return this;}
  then<T>(resolve:(value:{data:unknown;error:unknown})=>T,reject?:(reason:unknown)=>unknown){return Promise.resolve().then(()=>{
   queries.push({table:this.table,op:this.op,filters:[...this.names]});
   if(this.table==='paige_audit_log'&&auditFails)return {data:null,error:{message:'SECRET'}};
   if(this.op==='insert'){const row={...this.values};tables[this.table].push(row);return {data:this.singleRow?row:[row],error:null};}
   const matches=tables[this.table].filter(r=>this.filters.every(f=>f(r))).slice(0,this.count);
   if(this.op==='update')for(const row of matches)Object.assign(row,this.values);
   return {data:this.singleRow?matches[0]??null:matches,error:null};
  }).then(resolve,reject);}
 }
 const client={from:(table:string)=>new Query(table),auth:{getUser:async()=>({data:{user:{id:actor}},error:null})},rpc:async(name:string,args:Row)=>{
  calls.push(name);
  if(name==='_sales_invoice_actor')return {data:null,error:active!==args._tenant?{}:null};
  if(name==='resolve_tool_autonomy')return {data:lane,error:null};
  if(name==='reserve_sales_merchant_onboarding'){
   const previous=tables.tenant_stripe_accounts[0];if(previous)return {data:{binding:{...previous},dispatch:false},error:null};
   const row={tenant_id:tenant,stripe_account_id:null,provider_environment:'test',binding_version:1,charges_enabled:false,payouts_enabled:false,details_submitted:false,sales_payment_permission:false,sales_readback_at:null,onboarding_id:args._operation_id,onboarding_claim:args._claim,onboarding_started_at:new Date().toISOString()};tables.tenant_stripe_accounts.push(row);return {data:{binding:{...row},dispatch:true},error:null};
  }
  if(name==='persist_sales_merchant_onboarding'){Object.assign(tables.tenant_stripe_accounts[0],{stripe_account_id:args._merchant_id,binding_version:2});return {data:{...tables.tenant_stripe_accounts[0]},error:null};}
  if(name==='record_sales_merchant_onboarding_readback'){Object.assign(tables.tenant_stripe_accounts[0],{provider_environment:args._environment,charges_enabled:args._charges_enabled,payouts_enabled:args._payouts_enabled,details_submitted:args._details_submitted,sales_payment_permission:args._payment_permission,requirements:args._requirements,sales_readback_at:new Date().toISOString()});return {data:tables.tenant_stripe_accounts[0].binding_version,error:null};}
  if(name==='record_capability_run'){receiptArgs.push(args);return {data:true,error:receiptFails?{message:'SECRET'}:null};}
  return {data:null,error:{}};
 }};
 class Provider{
  constructor(_key:string,_options:unknown){}
  accounts={create:async(_params:Row,_options:Row)=>{calls.push('POST:create');creates.push({params:_params,options:_options});await onCreate();if(switchOnCreate)active='other';if(providerError)throw providerError;return {...account,metadata:{...account.metadata,..._params.metadata as Row}};},list:async()=>{calls.push('GET:list');if(listError)throw listError;return {data:recover?[{...account,metadata:{tenant_id:tenant,onboarding_id:operation,provider_environment:initial?.provider_environment??'test'}}]:[],has_more:false};},retrieve:async()=>{calls.push('GET:retrieve');return account;},createLoginLink:async()=>{calls.push('POST:login');return {url:'https://connect.stripe.com/express/test'};}};
  accountLinks={create:async()=>{calls.push('POST:link');return {url:'https://connect.stripe.com/setup/test'};}};
 }
 let handler:(req:Request)=>Promise<Response>=async()=>new Response();
 const deps={createClient:()=>client,Stripe:Provider,readStripeMerchant,...onboarding,...command,admitMerchantCommand,merchantApprovalStore,recordCapabilityRun,Deno:{serve:(fn:typeof handler)=>{handler=fn;},env:{get:(key:string)=>({SUPABASE_URL:'https://test.invalid',SUPABASE_SERVICE_ROLE_KEY:'synthetic-only',STRIPE_SECRET_KEY:initial?.provider_environment==='live'?'sk_live_SYNTHETIC_NOT_A_CREDENTIAL':'sk_test_SYNTHETIC_NOT_A_CREDENTIAL',PUBLIC_SITE_URL:'https://app.paigeagent.ai'} as Row)[key]}},console:{warn:(...args:unknown[])=>logs.push(args),error:(...args:unknown[])=>logs.push(args)}};
 new Function(...Object.keys(deps),js)(...Object.values(deps));
 const send=async(body:Row)=>{const result=await handler(new Request('https://test.invalid',{method:'POST',headers:{Authorization:'Bearer synthetic-session'},body:JSON.stringify(body)}));return {status:result.status,body:await result.json() as Row};};
 const request={command:{action:'merchant.start_onboarding',provider:'stripe'},expected_tenant_id:tenant,operation_id:operation};
 return {tables,calls,queries,logs,creates,receiptArgs,send,request,failReceipt:()=>{receiptFails=true;},failAudit:()=>{auditFails=true;},setLane:(value:string)=>{lane=value;},setError:(error:unknown)=>{providerError=error;},setListError:(error:unknown)=>{listError=error;},recoverAccount:()=>{recover=true;},switchAfterCreate:()=>{switchOnCreate=true;},createHook:(fn:()=>Promise<void>)=>{onCreate=fn;},account};
}
const pending={tenant_id:tenant,stripe_account_id:null,provider_environment:'test',binding_version:1,onboarding_id:operation,onboarding_claim:'40000000-0000-4000-8000-000000000001'};
describe('actual merchant endpoint synthetic SDK/database ports',()=>{
 it('legacy scoped status creates no provider or approval operation',async()=>{const f=fixture();expect(await f.send({action:'status'})).toMatchObject({status:200,body:{ok:true,tenant_id:tenant,provider_environment:'test',state:'not_connected'}});expect(f.calls.some(c=>c.startsWith('POST:'))).toBe(false);expect(f.tables.paige_pending_confirmations).toHaveLength(0);});
 it('rejects legacy unscoped create before any provider call',async()=>{const f=fixture();expect((await f.send({action:'start_onboarding'})).status).toBe(400);expect(f.calls).toHaveLength(0);});
 it('proposes exact server-bound C4b command without reserving',async()=>{const f=fixture();const result=await f.send(f.request);expect(result).toMatchObject({status:202,body:{tenant_id:tenant,operation_id:operation,outcome:'approval_required',preview:{environment:'test',provider:'stripe',binding_version:null}}});expect(f.tables.tenant_stripe_accounts).toHaveLength(0);expect(f.calls.some(c=>c.startsWith('POST:'))).toBe(false);});
 it('consumes a trusted scoped approval and dispatches once',async()=>{const f=fixture();const proposal=await f.send(f.request);const body={...f.request,approved_fingerprint:proposal.body.fingerprint};expect(await f.send(body)).toMatchObject({status:200,body:{ok:true,outcome:'customer_action_required',connected:true}});const second=await f.send(body);expect(second.body.outcome).toBe('refused');expect(f.calls.filter(c=>c==='POST:create')).toHaveLength(1);const claim=f.queries.find(q=>q.op==='update'&&q.filters.includes('neq:issued_in_request'));expect(claim?.filters).toEqual(expect.arrayContaining(['eq:user_id','eq:tenant_id','eq:tool_name','is:thread_id','is:scoped_client_id','is:consumed_at','not:server_issued_at','not:issued_in_request','gt:expires_at']));});
 it.each(['expired','legacy','consumed','other_actor'])('refuses %s approval before provider',async reason=>{const f=fixture();const p=await f.send(f.request),row=f.tables.paige_pending_confirmations[0];if(reason==='expired')row.expires_at='2000-01-01';if(reason==='legacy')row.server_issued_at=null;if(reason==='consumed')row.consumed_at=new Date().toISOString();if(reason==='other_actor')row.user_id='other';expect(await f.send({...f.request,approved_fingerprint:p.body.fingerprint})).toMatchObject({body:{outcome:'refused',code:'APPROVAL_NOT_CLAIMABLE'}});expect(f.calls.some(c=>c.startsWith('POST:'))).toBe(false);});
 it('pending refresh GET recovery never creates or mints approval',async()=>{const f=fixture(pending);expect(await f.send({action:'refresh_status',expected_tenant_id:tenant})).toMatchObject({status:200,body:{state:'outcome_unknown'}});expect(f.calls).toContain('GET:list');expect(f.calls.some(c=>c.startsWith('POST:'))).toBe(false);expect(f.tables.paige_pending_confirmations).toHaveLength(0);});
 it('pending start cannot recreate or mint approval',async()=>{const f=fixture(pending);expect(await f.send(f.request)).toMatchObject({status:409,body:{outcome:'outcome_unknown'}});expect(f.calls.some(c=>c.startsWith('POST:'))).toBe(false);expect(f.tables.paige_pending_confirmations).toHaveLength(0);});
 it('timeout preserves pending reservation and refuses a new POST',async()=>{const f=fixture();const p=await f.send(f.request);f.setError(Error('PROVIDER_OUTCOME_UNKNOWN'));expect(await f.send({...f.request,approved_fingerprint:p.body.fingerprint})).toMatchObject({status:503,body:{state:'outcome_unknown',code:'ONBOARDING_OUTCOME_UNKNOWN'}});await f.send({...f.request,operation_id:'50000000-0000-4000-8000-000000000001'});expect(f.calls.filter(c=>c==='POST:create')).toHaveLength(1);});
 it('safe definitive config refusal exposes no provider message and preserves reservation',async()=>{const f=fixture();const p=await f.send(f.request);f.setError({type:'StripeAuthenticationError',statusCode:401,message:'SECRET_RAW'});expect(await f.send({...f.request,approved_fingerprint:p.body.fingerprint})).toMatchObject({body:{outcome:'refused',state:'outcome_unknown',code:'PROVIDER_CONFIGURATION_REQUIRED'}});expect(f.tables.tenant_stripe_accounts[0].stripe_account_id).toBeNull();expect(JSON.stringify(f.logs)).not.toContain('SECRET_RAW');});
 it('active workspace change after create cannot bind',async()=>{const f=fixture();const p=await f.send(f.request);f.switchAfterCreate();expect(await f.send({...f.request,approved_fingerprint:p.body.fingerprint})).toMatchObject({status:409,body:{code:'WORKSPACE_CHANGED'}});expect(f.calls).not.toContain('persist_sales_merchant_onboarding');});
 it('audit failure prevents reservation or provider execution',async()=>{const f=fixture();f.failAudit();expect(await f.send(f.request)).toMatchObject({body:{code:'MERCHANT_DECISION_RECEIPT_FAILED'}});expect(f.tables.tenant_stripe_accounts).toHaveLength(0);});
 it('receipt failure cannot return a hosted credential or optimistic success',async()=>{const f=fixture();const p=await f.send(f.request);f.failReceipt();const result=await f.send({...f.request,approved_fingerprint:p.body.fingerprint});expect(result).toMatchObject({status:503,body:{ok:false,outcome:'completed_unrecorded',code:'MERCHANT_HANDOFF_UNRECORDED'}});expect(result.body.url).toBeUndefined();});
 it('pending LIVE configuration failure on GET is safely diagnosed without changing reservation',async()=>{const initial={...pending,provider_environment:'live'};const f=fixture(initial);f.setListError({type:'StripePermissionError',statusCode:403,message:'SECRET_RAW'});expect(await f.send({action:'refresh_status',expected_tenant_id:tenant})).toMatchObject({status:409,body:{state:'outcome_unknown',provider_environment:'live',outcome:'refused',recovery_reason:'PROVIDER_CONFIGURATION_REQUIRED'}});expect(f.tables.tenant_stripe_accounts[0]).toEqual(initial);expect(f.calls.some(c=>c.startsWith('POST:'))).toBe(false);expect(JSON.stringify(f.logs)).not.toContain('SECRET_RAW');});
 it('pending LIVE empty lookup remains unknown unchanged without approval/provider POST',async()=>{const initial={...pending,provider_environment:'live'};const f=fixture(initial);expect(await f.send({action:'refresh_status',expected_tenant_id:tenant})).toMatchObject({status:200,body:{state:'outcome_unknown',provider_environment:'live'}});expect(f.tables.tenant_stripe_accounts[0]).toEqual(initial);expect(f.calls.some(c=>c.startsWith('POST:'))).toBe(false);});
 it('explicit pending refresh recovers exact operation by GET then binds and reads fresh facts',async()=>{const f=fixture(pending);f.recoverAccount();expect(await f.send({action:'refresh_status',expected_tenant_id:tenant})).toMatchObject({status:200,body:{ok:true,state:'ready',connected:true,binding_version:2}});expect(f.calls).toEqual(expect.arrayContaining(['GET:list','persist_sales_merchant_onboarding','GET:retrieve','record_sales_merchant_onboarding_readback']));expect(f.calls.some(c=>c.startsWith('POST:'))).toBe(false);});
 it('concurrent redemption of one fingerprint authorizes at most one dispatch',async()=>{const f=fixture();const p=await f.send(f.request);const body={...f.request,approved_fingerprint:p.body.fingerprint};const results=await Promise.all([f.send(body),f.send(body)]);expect(results.filter(r=>r.body.outcome==='customer_action_required')).toHaveLength(1);expect(f.calls.filter(c=>c==='POST:create')).toHaveLength(1);});
 it('concurrent different approvals cannot overwrite the first canonical reservation',async()=>{const f=fixture();const a=await f.send(f.request),second={...f.request,operation_id:'50000000-0000-4000-8000-000000000001'},b=await f.send(second);await Promise.all([f.send({...f.request,approved_fingerprint:a.body.fingerprint}),f.send({...second,approved_fingerprint:b.body.fingerprint})]);expect(f.calls.filter(c=>c==='POST:create')).toHaveLength(1);expect(f.tables.tenant_stripe_accounts[0].onboarding_id).toBe(operation);});
 it('provider creation parameters remain immutable and receipt uses safe operation identity',async()=>{const f=fixture();const p=await f.send(f.request);await f.send({...f.request,approved_fingerprint:p.body.fingerprint});expect(f.creates[0]).toEqual({params:{type:'express',capabilities:{card_payments:{requested:true},transfers:{requested:true}},metadata:{tenant_id:tenant,onboarding_id:operation,provider_environment:'test'}},options:{idempotencyKey:`sales-merchant-${operation}`}});expect(f.receiptArgs[0]).toMatchObject({_tenant_id:tenant,_actor_id:actor,_capability_key:'sales_start_merchant_onboarding',_run_id:operation,_outcome:'capability_succeeded'});expect(JSON.stringify(f.receiptArgs)).not.toContain('https:');expect(JSON.stringify(f.receiptArgs)).not.toContain('provider_configuration');});
 it.each(['merchant.start_onboarding','merchant.login_link'])('fresh restricted provider facts cannot return cached Ready during %s',async action=>{const cached={tenant_id:tenant,stripe_account_id:'acct_fixture',provider_environment:'test',binding_version:2,charges_enabled:true,payouts_enabled:true,details_submitted:true,sales_payment_permission:true,sales_readback_at:new Date().toISOString(),requirements:{disabled_reason:null}};const f=fixture(cached);const intent={...f.request,command:{action,provider:'stripe'}};const p=await f.send(intent);f.account.charges_enabled=false;f.account.capabilities.card_payments='inactive';const result=await f.send({...intent,approved_fingerprint:p.body.fingerprint});expect(result).toMatchObject({status:200,body:{state:'restricted',charges_enabled:false,sales_payment_permission:false}});expect(f.calls.indexOf('record_sales_merchant_onboarding_readback')).toBeLessThan(f.calls.indexOf(action==='merchant.login_link'?'POST:login':'POST:link'));});
});
