import {describe,it,expect} from 'vitest';
import {admitMerchantCommand,type MerchantAdmissionPort,type MerchantAdmissionContext} from './merchant-admission.ts';
import {parseMerchantRequest} from './merchant-command.ts';
const tenant='10000000-0000-4000-8000-000000000001',operation='20000000-0000-4000-8000-000000000001';
const request=parseMerchantRequest({command:{action:'merchant.start_onboarding',provider:'stripe'},expected_tenant_id:tenant,operation_id:operation});
const context:MerchantAdmissionContext={actor:'30000000-0000-4000-8000-000000000001',tenant,environment:'test',provider_configuration:'synthetic-config-digest',binding_version:null,merchant_id:null,onboarding_id:null,return_url:'https://app.paigeagent.ai/solo/100/settings/integrations?stripe_setup=return',refresh_url:'https://app.paigeagent.ai/solo/100/settings/integrations?stripe_setup=return'};
function fixture(lane='confirm'){
 let stored:Record<string,unknown>|null=null,claims=0,valid=true,audit=true;
 const port:MerchantAdmissionPort={scope:async()=>{if(!valid)throw Error('WORKSPACE_CHANGED');},lane:async()=>lane,find:async()=>stored,claim:async()=>{claims++;const args=stored;stored=null;return args;},issue:async(_tool,_fingerprint,args)=>{stored=args;return {expires_at:'2026-10-07T12:10:00.000Z'};},audit:async()=>audit};
 return {port,get stored(){return stored;},get claims(){return claims;},invalidate:()=>{valid=false;},failAudit:()=>{audit=false;},inject:(args:Record<string,unknown>)=>{stored=args;}};
}
describe('shared merchant admission mock ports; no provider acceptance',()=>{
 it('proposes without claiming or authorizing creation',async()=>{const f=fixture();expect(await admitMerchantCommand(request,context,f.port)).toMatchObject({kind:'propose',capability:'sales_start_merchant_onboarding'});expect(f.claims).toBe(0);expect(f.stored).toMatchObject({command:request.command,operation_id:operation,expected_tenant_id:tenant});});
 it('executes exact earlier stored arguments once',async()=>{const f=fixture();const proposal=await admitMerchantCommand(request,context,f.port);if(proposal.kind!=='propose')throw Error();const stored=f.stored;const result=await admitMerchantCommand({...request,approved_fingerprint:proposal.fingerprint},context,f.port);expect(result).toMatchObject({kind:'execute',args:stored});expect(await admitMerchantCommand({...request,approved_fingerprint:proposal.fingerprint},context,f.port)).toMatchObject({kind:'refuse',code:'APPROVAL_NOT_CLAIMABLE'});});
 it.each(['off','unresolved','AUTO'])('refuses lane %s before any execution',async lane=>{const f=fixture(lane);expect((await admitMerchantCommand(request,context,f.port)).kind).toBe('refuse');});
 it('high auto still uses shared high-risk clamp',async()=>{const f=fixture('auto');expect((await admitMerchantCommand(request,context,f.port)).kind).toBe('propose');});
 it('refuses changed scope before claim',async()=>{const f=fixture();f.invalidate();await expect(admitMerchantCommand({...request,approved_fingerprint:'aaaaaaaaaaaaaaaa'},context,f.port)).rejects.toThrow('WORKSPACE_CHANGED');expect(f.claims).toBe(0);});
 it.each(['actor','environment','provider_configuration','binding_version','merchant_id','return_url','onboarding_id'])('refuses changed server binding %s',async field=>{const f=fixture();const p=await admitMerchantCommand(request,context,f.port);if(p.kind!=='propose')throw Error();const changed={...context,[field]:field==='binding_version'?2:'different'} as MerchantAdmissionContext;expect(await admitMerchantCommand({...request,approved_fingerprint:p.fingerprint},changed,f.port)).toMatchObject({kind:'refuse',code:'MERCHANT_APPROVAL_BINDING_CHANGED'});});
 it('does not silently re-propose failed claims',async()=>{const f=fixture();expect(await admitMerchantCommand({...request,approved_fingerprint:'aaaaaaaaaaaaaaaa'},context,f.port)).toMatchObject({kind:'refuse',code:'APPROVAL_NOT_CLAIMABLE'});expect(f.stored).toBe(null);});
 it('audit failure prevents proposal/execution',async()=>{const f=fixture();f.failAudit();expect(await admitMerchantCommand(request,context,f.port)).toMatchObject({kind:'refuse',code:'MERCHANT_DECISION_RECEIPT_FAILED'});expect(f.stored).toBe(null);});
 it('rejects substituted operation on redemption',async()=>{const f=fixture();const p=await admitMerchantCommand(request,context,f.port);if(p.kind!=='propose')throw Error();expect(await admitMerchantCommand({...request,operation_id:'40000000-0000-4000-8000-000000000001',approved_fingerprint:p.fingerprint},context,f.port)).toMatchObject({kind:'refuse',code:'MERCHANT_APPROVAL_BINDING_CHANGED'});});
});
