import {describe,it,expect} from 'vitest';
import {parseClaimedPayment,safePaymentOperation} from './operation-projection.ts';
const id='11111111-1111-4111-8111-111111111111',tenant='22222222-2222-4222-8222-222222222222',actor='33333333-3333-4333-8333-333333333333';
const command={action:'invoice.payment_request',invoice_id:id,expected_version:3,provider:'stripe',purpose:'partial',issued_snapshot_version:1,client_id:actor,amount_minor:50000,currency:'usd',merchant_account_id:'acct_A',merchant_binding_version:1,environment:'test'};
const row={id,tenant_id:tenant,actor_user_id:actor,invoice_id:id,client_id:actor,invoice_version:3,issued_snapshot_version:1,provider:'stripe',merchant_account_id:'acct_A',merchant_binding_version:1,environment:'test',amount_minor:50000,currency:'usd',purpose:'partial',command,idempotency_key:`sales-payment-${id}`,state:'dispatching',provider_object_id:null,dispatch_claim_token:'44444444-4444-4444-8444-444444444444',dispatch_started_at:'2026-10-05T12:00:00Z',authority_fingerprint:'1234567890abcdef'};
describe('internal payment facts and safe projection',()=>{
 it('reconstructs only command-bound provider facts',()=>expect(parseClaimedPayment(row,tenant,actor,id)).toMatchObject({operation:{merchant_id:'acct_A',application_fee_minor:0},request:{amount_minor:50000,client_id:actor},claimToken:row.dispatch_claim_token}));
 it.each([{tenant_id:'foreign'},{actor_user_id:'foreign'},{amount_minor:40000},{currency:'eur'},{merchant_account_id:'acct_other'},{merchant_binding_version:2},{environment:'live'},{invoice_version:4},{client_id:'foreign'},{idempotency_key:'different'},{dispatch_claim_token:null},{provider_object_id:'pi_other'},{dispatch_started_at:'invalid'},{state:'paid'}])('fails closed for conflicting persistent facts %j',patch=>expect(()=>parseClaimedPayment({...row,...patch},tenant,actor,id)).toThrow());
 it('reads cancellation before any dispatch without inventing a claim',()=>expect(parseClaimedPayment({...row,state:'cancelled',dispatch_claim_token:null,dispatch_started_at:null,provider_object_id:null},tenant,actor,id)).toMatchObject({operation:{state:'cancelled'},claimToken:'',dispatchStartedAt:''}));
 it('rejects a prepared row that already holds dispatch evidence',()=>expect(()=>parseClaimedPayment({...row,state:'prepared'},tenant,actor,id)).toThrow());
 it('safe model/UI output excludes authority, internal claims, provider secrets and command',()=>{const result=safePaymentOperation({...row,secret:'forbidden',provider_error_body:'forbidden'});expect(JSON.stringify(result)).not.toMatch(/claim|fingerprint|secret|command|provider_error/);expect(result).toMatchObject({outcome:'dispatching',operation_id:id,amount_minor:50000});});
 it('does not publish a stale hosted URL during uncertain readback',()=>expect(safePaymentOperation({...row,state:'outcome_unknown',provider_url:'https://checkout.stripe.com/pay/test'})).not.toHaveProperty('payment_url'));
 it('exposes only approved provider-hosted URL when customer action is required',()=>expect(safePaymentOperation({...row,state:'customer_action_required',expires_at:new Date(Date.now()+3600000).toISOString(),provider_url:'https://checkout.stripe.com/pay/test'})).toHaveProperty('payment_url','https://checkout.stripe.com/pay/test'));
 it('suppresses expired provider URLs',()=>expect(safePaymentOperation({...row,state:'customer_action_required',expires_at:'2020-01-01T00:00:00Z',provider_url:'https://checkout.stripe.com/pay/test'})).not.toHaveProperty('payment_url'));
 it('never exposes another host or userinfo URL',()=>{expect(safePaymentOperation({...row,state:'customer_action_required',expires_at:new Date(Date.now()+3600000).toISOString(),provider_url:'https://evil.example/pay'})).not.toHaveProperty('payment_url');expect(safePaymentOperation({...row,state:'customer_action_required',expires_at:new Date(Date.now()+3600000).toISOString(),provider_url:'https://credential@checkout.stripe.com/pay'})).not.toHaveProperty('payment_url');});
});
