import {describe,it,expect} from 'vitest';
import {parsePaymentRequestIntent,buildPaymentRequestCommand,parseCanonicalPaymentRequestCommand} from './request-command.ts';
const invoice={id:'11111111-1111-4111-8111-111111111111',tenant_id:'22222222-2222-4222-8222-222222222222',client_id:'33333333-3333-4333-8333-333333333333',lifecycle_version:3,issued_snapshot_version:1,status:'issued',currency:'usd',outstanding_minor:350000};
const merchant={tenant_id:invoice.tenant_id,provider:'stripe' as const,merchant_id:'acct_testA',environment:'test' as const,version:1};
const now=Date.parse('2026-10-05T12:00:00Z');
const facts={...merchant,binding_version:1,observed_at:new Date(now).toISOString(),charges_enabled:true,payouts_enabled:true,details_submitted:true,payment_permission:true,email_confirmed:false,partner_authorized:false,disabled_reason:null};
const intent={action:'invoice.payment_request',invoice_id:invoice.id,expected_version:3,provider:'stripe',purpose:'full'};
describe('canonical payment request assembly',()=>{
 it('round-trips exact server approval facts but never accepts them as caller intent',()=>{const command=buildPaymentRequestCommand(intent,invoice,merchant,facts,now);expect(parseCanonicalPaymentRequestCommand(command)).toEqual(command);expect(()=>parsePaymentRequestIntent(command)).toThrow();});
 it.each([{approved:true},{currency:'USD'},{client_id:'not-a-client'},{merchant_binding_version:0},{issued_snapshot_version:0},{amount_minor:0},{environment:'sandbox'}])('rejects corrupted stored approval tuple %j',patch=>expect(()=>parseCanonicalPaymentRequestCommand({...buildPaymentRequestCommand(intent,invoice,merchant,facts,now),...patch})).toThrow());
 it('derives full amount, client, currency and merchant exclusively from canonical context',()=>expect(buildPaymentRequestCommand(intent,invoice,merchant,facts,now)).toEqual({...intent,issued_snapshot_version:1,client_id:invoice.client_id,amount_minor:350000,currency:'usd',merchant_account_id:'acct_testA',merchant_binding_version:1,environment:'test'}));
 it('permits reviewed partial collection only within actual canonical balance',()=>expect(buildPaymentRequestCommand({...intent,purpose:'partial',amount_minor:50000},invoice,merchant,facts,now)).toMatchObject({amount_minor:50000,purpose:'partial'}));
 it.each([{client_id:invoice.client_id},{tenant_id:invoice.tenant_id},{merchant_account_id:'acct_other'},{currency:'eur'},{approved:true},{card_number:'forbidden'},{amount_minor:50000}])('refuses caller-authored authority/facts %j',patch=>expect(()=>parsePaymentRequestIntent({...intent,...patch})).toThrow('PAYMENT_REQUEST_INVALID'));
 it.each([0,-1,0.1,NaN,350001])('refuses unsafe partial amount %s',amount_minor=>expect(()=>buildPaymentRequestCommand({...intent,purpose:'partial',amount_minor},invoice,merchant,facts,now)).toThrow());
 it('refuses stale invoice before producing approval inputs',()=>expect(()=>buildPaymentRequestCommand({...intent,expected_version:2},invoice,merchant,facts,now)).toThrow('INVOICE_VERSION_CHANGED'));
 it('refuses merchant tenant mismatch',()=>expect(()=>buildPaymentRequestCommand(intent,invoice,{...merchant,tenant_id:'other'},facts,now)).toThrow('MERCHANT_TENANT_MISMATCH'));
 it('refuses readiness derived from declaration rather than provider readback',()=>expect(()=>buildPaymentRequestCommand(intent,invoice,merchant,null,now)).toThrow('MERCHANT_READBACK_REQUIRED'));
 it('refuses stale merchant readback',()=>expect(()=>buildPaymentRequestCommand(intent,invoice,merchant,{...facts,observed_at:new Date(now-300001).toISOString()},now)).toThrow('MERCHANT_READBACK_STALE'));
 it('refuses currency mismatch even if model omits currency',()=>expect(()=>buildPaymentRequestCommand(intent,{...invoice,currency:'USD'},merchant,facts,now)).toThrow('PAYMENT_REQUEST_INVALID'));
});
