import {describe,it,expect,vi} from 'vitest';
import {reconcileVerifiedSalesStripeEvent,type SalesStripeEventPorts} from './stripe-event.ts';
const id='11111111-1111-4111-8111-111111111111',tenant='22222222-2222-4222-8222-222222222222';
const request={id,tenant_id:tenant,invoice_id:id,invoice_version:3,issued_snapshot_version:1,client_id:id,commercial_package_id:null,amount_minor:50000,currency:'usd',purpose:'partial' as const,idempotency_key:'stable'};
const operation={id,tenant_id:tenant,request_id:id,provider:'stripe' as const,merchant_id:'acct_A',merchant_version:1,environment:'test' as const,idempotency_key:'stable',provider_operation_id:'cs_test_A',state:'customer_action_required' as const,application_fee_minor:0 as const};
const claim={request,operation,claimToken:'claim',dispatchStartedAt:'2026-10-05T12:00:00Z'};
const metadata={paige_operation_id:id,paige_request_id:id,tenant_id:tenant,invoice_id:id,client_id:id};
const session={id:'cs_test_A',livemode:false,mode:'payment',status:'open',payment_status:'unpaid',amount_total:50000,currency:'usd',client_reference_id:id,metadata,expires_at:Math.floor(Date.now()/1000)+3600,url:'https://checkout.stripe.com/pay/test'};
const event={id:'evt_A',account:'acct_A',livemode:false,type:'checkout.session.completed',data:{object:{id:'cs_test_A',metadata,payment_status:'paid',amount_total:1}}};
function ports():SalesStripeEventPorts{return {stripe:{environment:'test',createSession:vi.fn(),retrieveSession:vi.fn().mockResolvedValue(session),listSessions:vi.fn()},readOperation:vi.fn().mockResolvedValue(claim),merchantStillBound:vi.fn().mockResolvedValue(true),persistReadback:vi.fn().mockResolvedValue(undefined)};}
describe('signature-authenticated event then provider readback',()=>{
 it('ignores webhook success/amount and reads exact provider account object',async()=>{const p=ports();expect(await reconcileVerifiedSalesStripeEvent(event,'legacy',p)).toMatchObject({status:200});expect(p.persistReadback).toHaveBeenCalledWith(claim,expect.objectContaining({state:'customer_action_required'}),'evt_A');expect(p.stripe.retrieveSession).toHaveBeenCalledWith('cs_test_A',expect.anything(),{stripeAccount:'acct_A'});expect(p.stripe.createSession).not.toHaveBeenCalled();});
 it.each([{account:'acct_B'},{livemode:true},{account:null}])('refuses mismatched signed event scope %j',async patch=>{const p=ports();expect(await reconcileVerifiedSalesStripeEvent({...event,...patch},'legacy',p)).toMatchObject({status:400});expect(p.stripe.retrieveSession).not.toHaveBeenCalled();expect(p.persistReadback).not.toHaveBeenCalled();});
 it('another platform signing key cannot activate this merchant binding',async()=>{const p=ports();expect(await reconcileVerifiedSalesStripeEvent(event,'v2',p)).toMatchObject({status:400});expect(p.readOperation).not.toHaveBeenCalled();});
 it('merchant binding change refuses',async()=>{const p=ports();vi.mocked(p.merchantStillBound).mockResolvedValue(false);expect(await reconcileVerifiedSalesStripeEvent(event,'legacy',p)).toMatchObject({status:400});expect(p.stripe.retrieveSession).not.toHaveBeenCalled();});
 it('wrong checkout object cannot claim operation',async()=>{const p=ports();expect(await reconcileVerifiedSalesStripeEvent({...event,data:{object:{...event.data.object,id:'cs_test_other'}}},'legacy',p)).toMatchObject({status:400});expect(p.stripe.retrieveSession).not.toHaveBeenCalled();});
 it('provider timeout returns retryable uncertain result without another payment',async()=>{const p=ports();vi.mocked(p.stripe.retrieveSession).mockRejectedValue(new Error('secret'));expect(await reconcileVerifiedSalesStripeEvent(event,'legacy',p)).toMatchObject({status:503,code:'PAYMENT_READBACK_REQUIRED'});expect(p.persistReadback).toHaveBeenCalledWith(claim,{state:'outcome_unknown',code:'PROVIDER_READBACK_REQUIRED'},'evt_A');expect(p.stripe.createSession).not.toHaveBeenCalled();});
 it('receipt/allocation failure remains retryable instead of permanently consuming event',async()=>{const p=ports();vi.mocked(p.persistReadback).mockRejectedValue(new Error('rollback'));expect(await reconcileVerifiedSalesStripeEvent(event,'legacy',p)).toMatchObject({status:503});});
 it('does not route unrelated platform billing through Sales',async()=>{const p=ports();expect(await reconcileVerifiedSalesStripeEvent({...event,data:{object:{metadata:{}}}},'legacy',p)).toMatchObject({handled:false});expect(p.readOperation).not.toHaveBeenCalled();});
});
