import {it,expect,vi,beforeEach} from 'vitest';
import type {SalesPaymentAdmin} from './database-port.ts';
const h=vi.hoisted(()=>({read:vi.fn(),persist:vi.fn()}));
vi.mock('./stripe-client.ts',()=>({salesStripeClient:()=>({environment:'test'})}));
vi.mock('./stripe-hosted.ts',()=>({readStripeHostedRequest:h.read}));
vi.mock('./invoice-payment-adapter.ts',()=>({persistProviderPaymentReadback:h.persist}));
import {routeVerifiedSalesStripeEvent} from './stripe-event-adapter.ts';
const id='11111111-1111-4111-8111-111111111111',tenant='22222222-2222-4222-8222-222222222222',actor='33333333-3333-4333-8333-333333333333';
const command={action:'invoice.payment_request',invoice_id:id,expected_version:3,provider:'stripe',purpose:'partial',issued_snapshot_version:1,client_id:actor,amount_minor:50000,currency:'usd',merchant_account_id:'acct_A',merchant_binding_version:1,environment:'test'};
const row={id,tenant_id:tenant,actor_user_id:actor,invoice_id:id,client_id:actor,invoice_version:3,issued_snapshot_version:1,provider:'stripe',merchant_account_id:'acct_A',merchant_binding_version:1,environment:'test',amount_minor:50000,currency:'usd',purpose:'partial',command,idempotency_key:`sales-payment-${id}`,state:'provider_accepted',provider_object_id:'cs_test_fixture',dispatch_claim_token:'44444444-4444-4444-8444-444444444444',dispatch_started_at:'2026-10-05T12:00:00Z',reconciliation_status:'blocked',reconciliation_reason:'reconciliation_exhausted'};
const event={type:'balance.available',account:'acct_A',id:'evt_available',livemode:false,data:{object:{}}};
function fixture(rows:unknown[]=[row],more=false){const rpc=vi.fn(async(name:string)=>({data:name==='read_sales_balance_event_operations'?{rows,has_more:more}:null,error:null}));const query={eq:vi.fn().mockReturnThis(),maybeSingle:vi.fn(async()=>({data:{tenant_id:tenant,stripe_account_id:'acct_A',binding_version:1,provider_environment:'test'},error:null}))};return{rpc,admin:{rpc,from:()=>({select:()=>query})} as SalesPaymentAdmin};}
beforeEach(()=>{vi.clearAllMocks();h.read.mockResolvedValue({state:'settled'});h.persist.mockResolvedValue(undefined);});
it('signed balance event reads an exhausted existing operation and persists settlement without new dispatch',async()=>{const f=fixture();expect(await routeVerifiedSalesStripeEvent(f.admin,event,'legacy','unused')).toMatchObject({status:200,code:'PAYMENT_EVENT_RECONCILED'});expect(h.read).toHaveBeenCalledTimes(1);expect(h.persist).toHaveBeenCalledWith(f.admin,expect.objectContaining({operation:expect.objectContaining({id})}),{state:'settled'},event.id);expect(f.rpc).toHaveBeenCalledWith('complete_sales_balance_event_readback',expect.objectContaining({_operation_id:id,_event_id:event.id}));expect(f.rpc.mock.calls.some(([n])=>n.includes('claim')||n.includes('prepare'))).toBe(false);});
it('event replay with no unchecked operations has no additional provider readback',async()=>{const f=fixture([]);expect((await routeVerifiedSalesStripeEvent(f.admin,event,'legacy','unused')).status).toBe(200);expect(h.read).not.toHaveBeenCalled();expect(h.persist).not.toHaveBeenCalled();});
it('ambiguous provider result is retryable and never marks availability checked',async()=>{const f=fixture();h.read.mockResolvedValue({state:'outcome_unknown'});expect((await routeVerifiedSalesStripeEvent(f.admin,event,'legacy','unused')).status).toBe(503);expect(f.rpc.mock.calls.some(([n])=>n==='complete_sales_balance_event_readback')).toBe(false);});
it('event environment mismatch refuses without provider reads',async()=>{const f=fixture();expect((await routeVerifiedSalesStripeEvent(f.admin,{...event,livemode:true},'legacy','unused')).status).toBe(400);expect(h.read).not.toHaveBeenCalled();});
it('a larger event batch remains retryable so admission progresses',async()=>{const f=fixture([row],true);expect((await routeVerifiedSalesStripeEvent(f.admin,event,'legacy','unused')).status).toBe(503);expect(h.persist).toHaveBeenCalledTimes(1);});
