import {describe,it,expect} from 'vitest';import {readFileSync} from 'node:fs';import ts from 'typescript';
const source=readFileSync('supabase/functions/growth-process-submission/index.ts','utf8');const body=source.slice(source.indexOf('async function runExecutor('),source.indexOf("// -- A form's alert address"));
const run=new Function('s','extractIdentity','resolveIntakeOperator','extractCustomFields',ts.transpileModule(body,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText+';return runExecutor;')((v:unknown)=>typeof v==='string'?v:null,()=>({email:'person@example.test'}),async()=> 'actor',()=>({})) as (plan:unknown,context:unknown)=>Promise<{status:string;error?:string;result:Record<string,unknown>}>;
function harness(deal:Record<string,unknown>|null=null,pinError=false,pinMissing=false,currentPin={attempts:1,processing_state:'claimed',contact_id:null as string|null}){const writes:unknown[]=[];const reads:Record<string,unknown>[]=[];const admin={rpc:async(..._args:unknown[]):Promise<{data:unknown;error:unknown}>=>({data:'client',error:null}),from:(table:string)=>{const filters:Record<string,unknown>={table};const q={select:()=>q,eq:(k:string,v:unknown)=>{filters[k]=v;return q;},is:(k:string,v:unknown)=>{filters[k]=v;return q;},order:()=>q,limit:()=>q,update:(data:unknown)=>{writes.push({table,data});return q;},insert:(data:unknown)=>{writes.push({table,data});return q;},single:async()=>({data:{id:'new'},error:null}),maybeSingle:async()=>{reads.push(filters);return {data:table==='pipelines'?{id:'pipeline',tenant_id:'tenant'}:table==='pipeline_stages'?{id:'stage',pipeline_id:'pipeline',tenant_id:'tenant'}:table==='growth_form_submissions'&&!pinError&&!pinMissing&&filters.attempts===currentPin.attempts&&filters.processing_state===currentPin.processing_state&&filters.contact_id===currentPin.contact_id?{id:'submission'}:deal,error:table==='growth_form_submissions'&&pinError?{message:'pin failed'}:null};},then:(resolve:(value:unknown)=>unknown)=>Promise.resolve({error:pinError?{message:'pin failed'}:null}).then(resolve)};return q;}};return{writes,reads,ctx:{admin,tenantId:'tenant',submissionId:'submission',claimAttempt:1,submission:{deal_id:'original'},form:{pipeline_id:'pipeline',stage_id:'stage'},payload:{},contactId:'client',setContactId:()=>{}}};}
const plan={executor:'pipeline_attach',config:{},targetConfig:{}};
describe('actual form executor contact/deal retry integrity',()=>{
 it('refuses success when durable contact pin fails',async()=>{const h=harness(null,true);const result=await run({...plan,executor:'contact_upsert'},{...h.ctx,contactId:null});expect(result.status).toBe('error');expect(result.error).toContain('submission_contact_link_failed');});
 it('publishes resolved contact only after tenant-scoped pin succeeds',async()=>{const h=harness();const seen:string[]=[];const result=await run({...plan,executor:'contact_upsert'},{...h.ctx,contactId:null,setContactId:(id:string)=>seen.push(id)});expect(result.status).toBe('done');expect(seen).toEqual(['client']);expect(h.reads).toContainEqual({table:'growth_form_submissions',id:'submission',tenant_id:'tenant',processing_state:'claimed',attempts:1,contact_id:null});});
 it('refuses an empty pin readback without publishing resolved state',async()=>{const h=harness(null,false,true);const published:string[]=[];const result=await run({...plan,executor:'contact_upsert'},{...h.ctx,contactId:null,setContactId:(id:string)=>published.push(id)});expect(result.status).toBe('error');expect(published).toEqual([]);expect(h.reads).toContainEqual({table:'growth_form_submissions',id:'submission',tenant_id:'tenant',processing_state:'claimed',attempts:1,contact_id:null});});
 it.each([{attempts:2,processing_state:'claimed',contact_id:null},{attempts:1,processing_state:'done',contact_id:null},{attempts:1,processing_state:'claimed',contact_id:'successor-client'}])('refuses stale or superseded contact pin %j',async current=>{const h=harness(null,false,false,current);const published:string[]=[];const result=await run({...plan,executor:'contact_upsert'},{...h.ctx,contactId:null,setContactId:(id:string)=>published.push(id)});expect(result.status).toBe('error');expect(published).toEqual([]);});
 it('uses only durable admission identity, not request routing/contact authority',async()=>{const h=harness();const calls:unknown[]=[];h.ctx.admin.rpc=async(...args:unknown[])=>{calls.push(args);return {data:{deal_id:'original',replayed:true},error:null};};const result=await run({...plan,automationId:'automation'},{...h.ctx,claimAttempt:3});expect(result.status).toBe('done');expect(calls).toEqual([['growth_attach_submission_deal',{p_submission_id:'submission',p_claim_attempt:3,p_automation_id:'automation'}]]);expect(h.writes).toEqual([]);});
 it('reports admission refusal without direct fallback deal writes',async()=>{const h=harness();h.ctx.admin.rpc=async()=>({data:null,error:{code:'42501'}});expect((await run({...plan,automationId:null},{...h.ctx,claimAttempt:1})).status).toBe('error');expect(h.writes).toEqual([]);});
});
