import { describe,it,expect,vi,afterEach } from 'vitest';
import { downloadKnowledgeText,runKnowledgeExtraction,sourceHash,submitKnowledgeExtraction } from '../../supabase/functions/_shared/knowledge-extraction';
const actor='10000000-0000-0000-0000-000000000001';const tenant='00000000-0000-0000-0000-000000000001';const work='70000000-0000-0000-0000-000000000001';const doc='20000000-0000-0000-0000-000000000001';
function caller(){return {auth:{getUser:vi.fn(async()=>({data:{user:{id:actor}},error:null}))},from:vi.fn(()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{active_tenant_id:tenant},error:null})})})})),rpc:vi.fn(async()=>({data:true,error:null}))};}
function port(fn:(name:string,args:Record<string,unknown>)=>unknown){return {rpc:vi.fn(async(name:string,args:Record<string,unknown>)=>({data:fn(name,args),error:null}))};}
const paste={intent_id:work,expected_tenant:tenant,title:'Source',kind:'paste',content:'Neutral source text'};
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
describe('bounded native Knowledge intake',()=>{
 it('uses verified caller actor and current tenant, not request authority',async()=>{const admin=port(()=>({work_id:work,document_id:doc,status:'claimed',revision:1,replayed:false}));await submitKnowledgeExtraction(paste,caller(),admin,vi.fn());expect(admin.rpc).toHaveBeenCalledWith('submit_knowledge_extraction',expect.objectContaining({_actor:actor,_tenant:tenant,_input:paste.content}));});
 it.each(['actor_id','approval','source_binding','sha256'])('refuses caller-supplied %s',async key=>{const admin=port(()=>null);await expect(submitKnowledgeExtraction({...paste,[key]:'forged'},caller(),admin,vi.fn())).rejects.toThrow('input_invalid');expect(admin.rpc).not.toHaveBeenCalled();});
 it.each(['url','pdf','image','docx'])('reports %s unsupported before writing',async kind=>{const admin=port(()=>null);await expect(submitKnowledgeExtraction({...paste,kind},caller(),admin,vi.fn())).rejects.toThrow('unsupported_source');expect(admin.rpc).not.toHaveBeenCalled();});
 it('rejects changed selected workspace',async()=>{const c=caller();c.from=vi.fn(()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{active_tenant_id:doc},error:null})})})}));const admin=port(()=>null);await expect(submitKnowledgeExtraction(paste,c,admin,vi.fn())).rejects.toThrow();expect(admin.rpc).not.toHaveBeenCalled();});
 it('binds object identity and actual downloaded bytes',async()=>{const path=tenant+'/source.txt';const hash=await sourceHash(new TextEncoder().encode('File'));const admin=port(n=>n==='resolve_knowledge_extraction_source'?{object_id:doc,object_name:path,bucket:'tenant-knowledge'}:{work_id:work,document_id:doc,status:'claimed',revision:1,replayed:false});const download=vi.fn(async()=>({text:'File',sha256:hash,byte_size:4,mime_type:'text/plain'}));await submitKnowledgeExtraction({intent_id:work,expected_tenant:tenant,title:'File',kind:'file',path},caller(),admin,download);expect(admin.rpc).toHaveBeenLastCalledWith('submit_knowledge_extraction',expect.objectContaining({_input:null,_source:expect.objectContaining({object_id:doc,sha256:hash,byte_size:4})}));});
 it('refuses replacement object id after capture',async()=>{let reads=0;const path=tenant+'/source.txt';const admin=port(()=>({object_id:++reads===1?doc:work,object_name:path,bucket:'tenant-knowledge'}));await expect(submitKnowledgeExtraction({intent_id:work,expected_tenant:tenant,title:'File',kind:'file',path},caller(),admin,async()=>({text:'a',sha256:'a'.repeat(64),byte_size:1,mime_type:'text/plain'}))).rejects.toThrow('source_changed');expect(admin.rpc.mock.calls.some(([n])=>n==='submit_knowledge_extraction')).toBe(false);});
});
describe('server byte capture',()=>{
 it('preserves UTF-8 BOM bytes for the frozen hash',async()=>{const bytes=new Uint8Array([239,187,191,65]);const out=await downloadKnowledgeText('https://storage.invalid/file',{},vi.fn(async()=>new Response(bytes,{headers:{'content-type':'text/plain'}})) as typeof fetch);expect(out.text.charCodeAt(0)).toBe(0xfeff);expect(out.sha256).toBe(await sourceHash(bytes));});
 it('caps streaming data without trusting Content-Length',async()=>{const response=new Response(new Uint8Array(2097153),{headers:{'content-type':'text/plain'}});await expect(downloadKnowledgeText('https://storage.invalid/file',{},vi.fn(async()=>response) as typeof fetch)).rejects.toThrow('input_invalid');});
 it.each([new Uint8Array([255]),new Uint8Array([0])])('rejects binary/invalid UTF8 %j',async bytes=>{await expect(downloadKnowledgeText('https://storage.invalid/file',{},vi.fn(async()=>new Response(bytes,{headers:{'content-type':'text/plain'}})) as typeof fetch)).rejects.toThrow('input_invalid');});
 it('rejects PDF MIME even on a text path',async()=>{await expect(downloadKnowledgeText('https://storage.invalid/file',{},vi.fn(async()=>new Response('x',{headers:{'content-type':'application/pdf'}})) as typeof fetch)).rejects.toThrow('input_invalid');});
 it('rejects overlong extracted text',async()=>{await expect(downloadKnowledgeText('https://storage.invalid/file',{},vi.fn(async()=>new Response('x'.repeat(480001),{headers:{'content-type':'text/plain'}})) as typeof fetch)).rejects.toThrow('input_invalid');});
});
describe('native worker core',()=>{
 async function started(){return {status:'claimed',work_id:work,server_key:'server',attempt:1,revision:1,tenant_id:tenant,actor_id:actor,document_id:doc,input:'Source',input_hash:await sourceHash(new TextEncoder().encode('Source')),source:null};}
 it('completes paste into awaiting review without download or embedding',async()=>{const start=await started();const admin=port(n=>n==='start_knowledge_extraction'?start:{verified_readback:true,phase:'awaiting_review',document_id:doc,outcome:'capability_succeeded'});const download=vi.fn();expect(await runKnowledgeExtraction(admin,work,download)).toMatchObject({status:'succeeded',phase:'awaiting_review'});expect(download).not.toHaveBeenCalled();expect(admin.rpc.mock.calls.map(([n])=>n)).toEqual(['start_knowledge_extraction','complete_knowledge_extraction']);});
 it('retains completed_unrecorded distinctly',async()=>{const start=await started();const admin=port(n=>n==='start_knowledge_extraction'?start:{verified_readback:true,phase:'awaiting_review',document_id:doc,outcome:'capability_completed_unrecorded'});expect(await runKnowledgeExtraction(admin,work,vi.fn())).toMatchObject({outcome:'capability_completed_unrecorded'});});
 it('changed file bytes never reach completion',async()=>{const start=await started();start.source={object_name:tenant+'/file.txt',object_id:doc,sha256:start.input_hash,byte_size:6} as never;const admin=port(n=>n==='start_knowledge_extraction'?start:n==='resolve_knowledge_extraction_source'?{object_id:doc}:null);const result=await runKnowledgeExtraction(admin,work,async()=>({text:'Changed',sha256:'a'.repeat(64),byte_size:7,mime_type:'text/plain'}));expect(result).toMatchObject({status:'failed',error_code:'source_changed'});expect(admin.rpc.mock.calls.some(([n])=>n==='complete_knowledge_extraction')).toBe(false);});
 it('lost completion acknowledgement yields unknown without blind retry',async()=>{const start=await started();const admin=port(n=>{if(n==='start_knowledge_extraction')return start;if(n==='complete_knowledge_extraction')throw new Error('connection lost');return null;});expect(await runKnowledgeExtraction(admin,work,vi.fn())).toMatchObject({status:'outcome_unknown'});expect(admin.rpc.mock.calls.filter(([n])=>n==='complete_knowledge_extraction')).toHaveLength(1);expect(admin.rpc).toHaveBeenLastCalledWith('settle_knowledge_extraction_failure',expect.objectContaining({_unknown:true,_attempt:1}));});
 it('blocked work never reads sources',async()=>{const download=vi.fn();expect(await runKnowledgeExtraction(port(()=>({status:'blocked'})),work,download)).toMatchObject({status:'blocked'});expect(download).not.toHaveBeenCalled();});
});
