// @vitest-environment jsdom
import React, { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
const api = vi.hoisted(() => ({ tenant: 'tenant-a', rpc: vi.fn(), legacy: vi.fn() }));
vi.mock('@/integrations/supabase/client', () => ({ supabase: { rpc: api.rpc, from: () => ({ delete: () => ({eq: () => ({eq: api.legacy})}) }) } }));
vi.mock('@/hooks/useTenantContext', () => ({ useTenantContext: () => ({ activeTenantId: api.tenant, activeTenant: { name: 'Workspace' } }) }));
vi.mock('@/components/paige/PaigeWorkspaceContext', () => ({ usePaigeWorkspace: () => ({ activeTenantId: api.tenant, notifyKnowledgeAdded: vi.fn() }) }));
vi.mock('@/components/knowledge/KnowledgeMetadataEditor', () => ({ KnowledgeMetadataEditor: () => null }));
vi.mock('@/components/ui/dropdown-menu', () => ({ DropdownMenu: ({children}:React.PropsWithChildren)=><div>{children}</div>, DropdownMenuContent: ({children}:React.PropsWithChildren)=><div>{children}</div>, DropdownMenuTrigger:()=>null, DropdownMenuItem:({children,onClick,disabled}:React.PropsWithChildren<{onClick:()=>void;disabled?:boolean}>)=><button disabled={disabled} onClick={onClick}>{children}</button> }));
import TenantKnowledgeAdmin from '@/pages/admin/TenantKnowledgeAdmin';
import { KnowledgePanel } from '@/components/paige/KnowledgePanel';
const doc={id:'document-a',tenant_id:'tenant-a',revision:2,title:'Guide',summary:null,category:null,tags:[],source:'paste',source_url:null,chunk_count:3,created_at:'2026-09-01',updated_at:'2026-09-01',share_to_network:false,network_review_status:'none'};
const receipt={tenant_id:'tenant-a',document_id:doc.id,deleted_revision:2,document_absent:true,chunks_absent:true,source_cleanup:{status:'not_attempted',reason:'canonical_source_binding_unavailable'},outcome:'capability_succeeded',run_id:'run-a'};
let host:HTMLDivElement,root:Root,rows:typeof doc[],deleteReply:()=>Promise<unknown>;
const deletes=()=>api.rpc.mock.calls.filter(c=>c[0]==='delete_tenant_knowledge');
async function click(text:string){const el=[...document.querySelectorAll('button')].find(b=>b.textContent?.trim()===text);expect(el).toBeTruthy();await act(async()=>el!.click());}
beforeEach(()=>{globalThis.IS_REACT_ACT_ENVIRONMENT=true;api.tenant='tenant-a';rows=[doc];api.rpc.mockReset();api.legacy.mockReset().mockResolvedValue({error:null});deleteReply=async()=>{rows=[];return {data:receipt,error:null};};api.rpc.mockImplementation(async(name:string)=>name==='delete_tenant_knowledge'?deleteReply():{data:{tenant_id:api.tenant,documents:rows.map(d=>({...d,tenant_id:api.tenant}))},error:null});host=document.createElement('div');document.body.append(host);root=createRoot(host);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();});
for(const surface of ['admin','panel'] as const)describe(`${surface} canonical deletion`,()=>{
 async function render(){await act(async()=>root.render(surface==='admin'?<TenantKnowledgeAdmin/>:<KnowledgePanel tenantName="Workspace"/>));}
 async function begin(){if(surface==='panel')await click('Delete');else{const b=[...host.querySelectorAll('tbody tr button')].at(-1) as HTMLButtonElement;expect(b).toBeTruthy();await act(async()=>b!.click());}}
 async function approve(){await click(surface==='panel'?'Remove':'Delete');}
 it('cancels without any write',async()=>{await render();await begin();await click(surface==='panel'?'Keep it':'Cancel');expect(deletes()).toHaveLength(0);expect(api.legacy).not.toHaveBeenCalled();});
 it('uses revision CAS and reloads canonical counts after verified deletion',async()=>{await render();await begin();await approve();expect(deletes()).toEqual([['delete_tenant_knowledge',{p_expected_tenant:'tenant-a',p_doc_id:doc.id,p_expected_revision:2}]]);expect(api.legacy).not.toHaveBeenCalled();expect(host.textContent).toContain('Original uploaded files were retained');expect(host.textContent).not.toContain('Guide');});
 it('reports receipt failure without another deletion',async()=>{deleteReply=async()=>({data:{...receipt,outcome:'capability_completed_unrecorded'},error:null});await render();await begin();await approve();expect(host.textContent).toContain('receipt could not be recorded');expect(deletes()).toHaveLength(1);});
 it.each([null,{}, {tenant_id:'tenant-a'}, {...receipt,document_absent:false}])('rejects empty or unverified outcome %j',async(data)=>{deleteReply=async()=>({data,error:null});await render();await begin();await approve();expect(host.textContent).toContain('Check document status');expect(host.textContent).not.toContain('Document removed.');expect(deletes()).toHaveLength(1);});
 it('requires explicit readback after conflict, then uses the fresh revision',async()=>{deleteReply=async()=>({data:null,error:{code:'KNOWLEDGE_REVISION_CONFLICT',message:'conflict'}});await render();await begin();await approve();rows=[{...doc,revision:3}];await click('Check document status');expect(deletes()).toHaveLength(1);await begin();await approve();expect(deletes()[1][1]).toMatchObject({p_expected_revision:3});});
 it('does not attribute missing readback to the unacknowledged deletion',async()=>{deleteReply=async()=>{throw Error('lost');};await render();await begin();await approve();rows=[];await click('Check document status');expect(host.textContent).toContain('earlier operation and its receipt could not be confirmed');expect(host.textContent).not.toContain('Document removed.');expect(deletes()).toHaveLength(1);});
 it('keeps deletion blocked while its response is pending',async()=>{let resolve!:(v:unknown)=>void;deleteReply=()=>new Promise(r=>{resolve=r;});await render();await begin();await approve();await begin();expect(deletes()).toHaveLength(1);await act(async()=>resolve({data:receipt,error:null}));});
 it('keeps unknown readback failure blocked without retrying the write',async()=>{deleteReply=async()=>{throw Error('lost');};await render();await begin();await approve();api.rpc.mockRejectedValueOnce(Error('offline'));await click('Check document status');expect(host.textContent).toContain('Document status could not be read');await begin();expect(deletes()).toHaveLength(1);});
 it('discards readback after a workspace incarnation change',async()=>{deleteReply=async()=>{throw Error('lost');};await render();await begin();await approve();let resolve!:(v:unknown)=>void;api.rpc.mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));await click('Check document status');api.tenant='tenant-b';await render();api.tenant='tenant-a';await render();await act(async()=>resolve({data:{tenant_id:'tenant-a',documents:[]},error:null}));expect(host.textContent).not.toContain('earlier operation');expect(host.textContent).toContain('Guide');});
 it('fences A to B to A while confirmation is open',async()=>{await render();await begin();api.tenant='tenant-b';await render();api.tenant='tenant-a';await render();const action=[...document.querySelectorAll('[role="alertdialog"] button')].find(b=>b.textContent?.trim()===(surface==='panel'?'Remove':'Delete'));if(action)await act(async()=>(action as HTMLButtonElement).click());expect(deletes()).toHaveLength(0);expect(api.legacy).not.toHaveBeenCalled();});
 it('suppresses a late deletion response after A to B to A',async()=>{let resolve!:(v:unknown)=>void;deleteReply=()=>new Promise(r=>{resolve=r;});await render();await begin();await approve();api.tenant='tenant-b';await render();api.tenant='tenant-a';await render();await act(async()=>resolve({data:receipt,error:null}));expect(host.textContent).not.toContain('Document removed.');expect(host.textContent).toContain('Guide');});
});


