import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {sourceHash} from '../../supabase/functions/_shared/knowledge-extraction';
const state=vi.hoisted(()=>({rpc:vi.fn(),authorized:true,model:vi.fn(),handler:null as null|((r:Request)=>Promise<Response>)}));
vi.mock('../../supabase/functions/_shared/systems-check-http.ts',()=>({adminClient:()=>({rpc:state.rpc}),isAuthorizedInternalCaller:async()=>state.authorized,json:(status:number,body:unknown)=>new Response(JSON.stringify(body),{status})}));
vi.mock('../../supabase/functions/_shared/model-router.ts',()=>({callModel:state.model}));
vi.mock('../../supabase/functions/_shared/document-production.ts',()=>({validateDocumentBrief:()=>({ok:true,value:{}}),buildDocumentAuthoringPrompt:()=>[],parseDocumentModelOutput:()=>({docType:'guide',title:'Guide',blocks:[]})}));
const work='70000000-0000-0000-0000-000000000001';const doc='20000000-0000-0000-0000-000000000001';
beforeEach(async()=>{vi.resetModules();state.rpc.mockReset();state.model.mockReset();state.authorized=true;vi.stubGlobal('Deno',{env:{get:()=> 'local-test-only'},serve:(handler:typeof state.handler)=>{state.handler=handler;}});await import('../../supabase/functions/paige-document-worker/index');});
afterEach(()=>vi.unstubAllGlobals());
const request=(body:unknown)=>new Request('https://worker.invalid',{method:'POST',body:JSON.stringify(body)});
describe('actual native worker handler with fake ports',()=>{
 it('refuses untrusted callers before dispatch',async()=>{state.authorized=false;const response=await state.handler!(request({mode:'knowledge-run',work_id:work}));expect(response.status).toBe(401);expect(state.rpc).not.toHaveBeenCalled();expect(state.model).not.toHaveBeenCalled();});
 it('routes knowledge-run to pending-review RPCs without a provider',async()=>{const hash=await sourceHash(new TextEncoder().encode('Text'));state.rpc.mockImplementation(async(n:string)=>({error:null,data:n==='start_knowledge_extraction'?{status:'claimed',work_id:work,document_id:doc,server_key:'key',attempt:1,revision:1,source:null,input:'Text',input_hash:hash}:{verified_readback:true,phase:'awaiting_review',document_id:doc,outcome:'capability_succeeded'}}));const response=await state.handler!(request({mode:'knowledge-run',work_id:work}));expect(await response.json()).toMatchObject({status:'succeeded',phase:'awaiting_review'});expect(state.model).not.toHaveBeenCalled();expect(state.rpc.mock.calls.map(([n])=>n)).toEqual(['start_knowledge_extraction','complete_knowledge_extraction']);});
 it('existing sweep drains Knowledge from the same handler',async()=>{state.rpc.mockImplementation(async(n:string)=>({error:null,data:n==='recover_paige_document_work'?[]:n==='recover_knowledge_extraction'?[{work_id:work}]:{status:'blocked'}}));const response=await state.handler!(request({mode:'sweep'}));expect(await response.json()).toMatchObject({recovered:0,results:[],knowledge_results:[{status:'blocked'}]});expect(state.rpc.mock.calls.map(([n])=>n)).toEqual(['recover_paige_document_work','recover_knowledge_extraction','start_knowledge_extraction']);});
 it('legacy document route still uses its own provider and completion',async()=>{state.model.mockResolvedValue({content:'fixture',provider:'fake',model:'fake'});state.rpc.mockImplementation(async(n:string)=>({error:null,data:n==='start_paige_document_work_execution'?[{work_id:work,work_status:'claimed',server_idempotency_key:'key',attempt_count:1,request_payload:{}}]:[{work_status:'succeeded',content_id:doc}]}));const response=await state.handler!(request({mode:'run',work_id:work}));expect(await response.json()).toMatchObject({status:'succeeded',content_id:doc});expect(state.model).toHaveBeenCalledTimes(1);expect(state.rpc.mock.calls.map(([n])=>n)).toEqual(['start_paige_document_work_execution','complete_paige_document_work']);});
});
