import {describe,it,expect} from 'vitest';
import {merchantChatSafeResult} from '../../supabase/functions/_shared/sales-payments/merchant-chat.ts';
import {dispatchSalesInvoiceChat,SALES_INVOICE_TOOLS} from '../../supabase/functions/_shared/sales-invoice-chat.ts';
const tenant='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',op='33333333-3333-4333-8333-333333333333',fp='abcdef0123456789';
const command={action:'merchant.start_onboarding',provider:'stripe'};
const ctx={tenantId:tenant,userId:actor,toolName:'sales_start_merchant_onboarding',args:{},approved:new Set<string>(),sameToolCalls:1,turn:{thread_id:null,user_turn_ordinal:1,user_turn:'set up merchant'}};
function harness(rows:unknown[]=[],data:unknown={ok:true,tenant_id:tenant,state:'setup_incomplete',url:'https://connect.stripe.com/SECRET'}){
 const calls:{name:string;body:Record<string,unknown>}[]=[],predicates:unknown[][]=[];const q:Record<string,unknown>={};for(const k of ['select','eq','in','is','not','gt'])q[k]=(...a:unknown[])=>{predicates.push([k,...a]);return q};q.limit=async(n:number)=>{predicates.push(['limit',n]);return {data:rows,error:null}};
 const deps={admin:{from:()=>q as never},caller:{rpc:async()=>{throw Error('no SQL door')},functions:{invoke:async(name:string,options:{body:Record<string,unknown>})=>{calls.push({name,...options});return {data,error:null}}}}};return {calls,predicates,deps};
}
function approvalHarness(extra:Record<string,unknown>={}){const h=harness();h.deps.caller.functions.invoke=async(name,options)=>{h.calls.push({name,...options});return {data:{ok:false,outcome:'approval_required',tenant_id:tenant,state:'not_connected',provider_environment:'test',binding_version:null,operation_id:options.body.operation_id,capability:'sales_start_merchant_onboarding',fingerprint:fp,expires_at:new Date(Date.now()+60000).toISOString(),preview:{action:'merchant.start_onboarding',provider:'stripe',environment:'test',binding_version:null},...extra},error:null}};return h;}
describe('merchant Chat shared door',()=>{
 it.each([{tenant_id:op},{operation_id:op},{provider_environment:null},{provider_environment:'other'},{capability:'sales_create_merchant_login_link'},{expires_at:'2000-01-01T00:00:00Z'},{preview:{action:'merchant.login_link',provider:'stripe',environment:'test',binding_version:null}},{preview:{action:'merchant.start_onboarding',provider:'stripe',environment:'live',binding_version:null}},{preview:{action:'merchant.start_onboarding',provider:'stripe',environment:'test',binding_version:2}},{preview:{action:'merchant.start_onboarding',provider:'stripe',environment:'test',binding_version:null,url:'SECRET'}}])('refuses cross-scope/malformed approval readback %j',async(extra)=>{const h=approvalHarness(extra);const r=await dispatchSalesInvoiceChat(ctx,h.deps);expect(r.content.success).toBe(false);expect(r.content).not.toHaveProperty('needs_confirm');expect(JSON.stringify(r)).not.toContain('SECRET')});
 it.each([{checked_at:new Date(Date.now()-300001).toISOString()},{checked_at:new Date(Date.now()+60000).toISOString()},{checked_at:null},{sales_payment_permission:false},{charges_enabled:false},{details_submitted:false},{connected:false},{binding_version:null},{provider_environment:null}])('downgrades unsafe ready status %j',extra=>{expect(merchantChatSafeResult({state:'ready',connected:true,binding_version:1,provider_environment:'test',charges_enabled:true,details_submitted:true,sales_payment_permission:true,checked_at:new Date().toISOString(),...extra}).state).toBe('unverified')});
 it('stale ready status cannot reach the model as ready',async()=>{const h=harness([],{ok:true,tenant_id:tenant,state:'ready',connected:true,binding_version:1,provider_environment:'test',charges_enabled:true,details_submitted:true,sales_payment_permission:true,checked_at:'2000-01-01T00:00:00Z'});expect((await dispatchSalesInvoiceChat({...ctx,toolName:'read_sales_merchant_status'},h.deps)).content).toMatchObject({state:'unverified',recovery_reason:'MERCHANT_READBACK_REQUIRED'});});
 it('retains fresh permission-proven ready state',()=>{expect(merchantChatSafeResult({state:'ready',connected:true,binding_version:1,provider_environment:'test',charges_enabled:true,details_submitted:true,sales_payment_permission:true,checked_at:new Date().toISOString()}).state).toBe('ready')});

 it('registers four closed tools with no authority fields',()=>{for(const name of ['read_sales_merchant_status','read_sales_merchant_refresh','sales_start_merchant_onboarding','sales_create_merchant_login_link']){const tool=SALES_INVOICE_TOOLS.find(t=>t.function.name===name);expect(tool).toBeDefined();expect(tool?.function.parameters).toMatchObject({additionalProperties:false});expect(JSON.stringify(tool?.function.parameters)).not.toMatch(/approved|tenant_id|operation_id|url/);}});
 it('reads active workspace through shared merchant endpoint and omits bearer/actor data',async()=>{const h=harness([], {ok:true,tenant_id:tenant,state:'ready',connected:true,binding_version:1,provider_environment:'test',charges_enabled:true,details_submitted:true,sales_payment_permission:true,checked_at:new Date().toISOString(),url:'SECRET',account_id:'SECRET',actor_id:actor});const r=await dispatchSalesInvoiceChat({...ctx,toolName:'read_sales_merchant_status'},h.deps);expect(h.calls[0]).toMatchObject({name:'tenant-stripe-connect',body:{expected_tenant_id:tenant,action:'status'}});expect(r.content).toMatchObject({success:true,state:'ready',connected:true});expect(JSON.stringify(r)).not.toContain('SECRET');expect(JSON.stringify(r)).not.toContain(actor);});
 it('fresh preparation uses stable operation but never exposes hosted link',async()=>{const h=harness();const a=await dispatchSalesInvoiceChat(ctx,h.deps);await dispatchSalesInvoiceChat(ctx,h.deps);expect(h.calls[0]).toEqual(h.calls[1]);expect(h.calls[0]).toMatchObject({name:'tenant-stripe-connect',body:{command,expected_tenant_id:tenant}});expect(JSON.stringify(a)).not.toContain('SECRET');expect(a.content.note).toContain('Integrations');expect(a.content).not.toHaveProperty('url');});
 it('pinned approval uses exact stored act, no lookup and sole endpoint consumes',async()=>{const h=harness();const r=await dispatchSalesInvoiceChat({...ctx,args:{provider:'stripe'},pinned:{fingerprint:fp,args:{command,operation_id:op,expected_tenant_id:tenant}}},h.deps);expect(h.predicates).toEqual([]);expect(h.calls).toEqual([{name:'tenant-stripe-connect',body:{command,operation_id:op,expected_tenant_id:tenant,approved_fingerprint:fp}}]);expect(r.spent).toBe(fp);});
 it('lookup binds actor/tenant/tool/null scopes and bounded server approval',async()=>{const h=harness([{fingerprint:fp,args:{command,operation_id:op,expected_tenant_id:tenant}}]);await dispatchSalesInvoiceChat({...ctx,approved:new Set([fp])},h.deps);for(const p of [['eq','tenant_id',tenant],['eq','user_id',actor],['eq','tool_name',ctx.toolName],['is','thread_id',null],['is','scoped_client_id',null],['is','consumed_at',null],['not','server_issued_at','is',null],['not','issued_in_request','is',null]])expect(h.predicates).toContainEqual(p);expect(h.predicates).toContainEqual(['limit',9]);});
 it.each([{expected_tenant_id:op},{operation_id:'bad'},{command:{action:'merchant.login_link',provider:'stripe'}},{command:{...command,approved:true}}])('refuses malformed/cross-scope pinned args %j',async(extra)=>{const h=harness();const r=await dispatchSalesInvoiceChat({...ctx,pinned:{fingerprint:fp,args:{command,operation_id:op,expected_tenant_id:tenant,...extra}}},h.deps);expect(r.content.success).toBe(false);expect(h.calls).toEqual([]);expect(r.spent).toBeUndefined();});
 it.each([{provider:'paypal'},{approved:true},{url:'SECRET'},{action:'merchant.login_link'}])('rejects model authority/unsupported provider %j',async(args)=>{const h=harness();await dispatchSalesInvoiceChat({...ctx,args},h.deps);expect(h.calls).toEqual([])});
 it('does not fall through to fresh act when approvals are absent/ambiguous',async()=>{for(const rows of [[],[{fingerprint:fp,args:{command,operation_id:op,expected_tenant_id:tenant}},{fingerprint:fp,args:{command,operation_id:op,expected_tenant_id:tenant}}]]){const h=harness(rows);await dispatchSalesInvoiceChat({...ctx,approved:new Set([fp])},h.deps);expect(h.calls).toEqual([])}});
 it('approval cards never expose remote summary or preview bearer',async()=>{const h=approvalHarness({summary:'SECRET https://connect.stripe.com/SECRET',url:'SECRET'});const r=await dispatchSalesInvoiceChat(ctx,h.deps);expect(r.content).toMatchObject({needs_confirm:true,confirm_fingerprint:fp});expect(JSON.stringify(r)).not.toContain('SECRET');});
 it('explicit refresh is GET-only intent and does not establish setup completion',async()=>{const h=harness([],{ok:true,tenant_id:tenant,state:'outcome_unknown',connected:false});const r=await dispatchSalesInvoiceChat({...ctx,toolName:'read_sales_merchant_refresh'},h.deps);expect(h.calls[0]).toMatchObject({body:{action:'refresh_status',expected_tenant_id:tenant}});expect(h.calls[0].body).not.toHaveProperty('operation_id');expect(r.content).toMatchObject({success:true,state:'outcome_unknown',connected:false})});
 it('actor and workspace bind stable operation identity',async()=>{const h=harness();await dispatchSalesInvoiceChat(ctx,h.deps);await dispatchSalesInvoiceChat({...ctx,userId:op},h.deps);await dispatchSalesInvoiceChat({...ctx,tenantId:op},h.deps);expect(new Set(h.calls.map(c=>c.body.operation_id)).size).toBe(3);});
 it('missing actor/workspace and scoped approval token fail before dispatch',async()=>{for(const extra of [{userId:''},{tenantId:null},{approved:new Set([fp+':scope'])}]){const h=harness([{fingerprint:fp,args:{command,operation_id:op,expected_tenant_id:tenant}}]);const r=await dispatchSalesInvoiceChat({...ctx,...extra},h.deps);expect(r.content.success).toBe(false);expect(h.calls).toHaveLength(0)}});
 it('login uses its own stored action and stable operation',async()=>{const h=harness();const login={action:'merchant.login_link',provider:'stripe'};await dispatchSalesInvoiceChat({...ctx,toolName:'sales_create_merchant_login_link',pinned:{fingerprint:fp,args:{command:login,operation_id:op,expected_tenant_id:tenant}}},h.deps);expect(h.calls[0].body).toMatchObject({command:login,operation_id:op,approved_fingerprint:fp})});
 it('HTTP approval-required body is projected through the same safe channel',async()=>{const h=approvalHarness({url:'SECRET',summary:'SECRET'});const invoke=h.deps.caller.functions.invoke;h.deps.caller.functions.invoke=async(name,options)=>{const reply=await invoke(name,options);return {data:null,error:{context:{json:async()=>reply.data}}} as never};const r=await dispatchSalesInvoiceChat(ctx,h.deps);expect(r.content.needs_confirm).toBe(true);expect(JSON.stringify(r)).not.toContain('SECRET')});
 it('missing canonical status readback never claims success',async()=>{const h=harness([],{ok:true,tenant_id:tenant,url:'SECRET'});const r=await dispatchSalesInvoiceChat({...ctx,toolName:'read_sales_merchant_status'},h.deps);expect(r.content).toMatchObject({success:false,outcome:'outcome_unknown'});expect(JSON.stringify(r)).not.toContain('SECRET')});
 it('cross-tenant readback refuses and transport unknown never claims success',async()=>{const h=harness([],{ok:true,tenant_id:op,state:'ready'});expect((await dispatchSalesInvoiceChat({...ctx,toolName:'read_sales_merchant_status'},h.deps)).content.success).toBe(false);h.deps.caller.functions.invoke=async()=>{throw Error('SECRET')};const r=await dispatchSalesInvoiceChat(ctx,h.deps);expect(r.content).toMatchObject({success:false,outcome:'outcome_unknown'});expect(JSON.stringify(r)).not.toContain('SECRET');});
});
