// @vitest-environment node
import {expect,it} from 'vitest';
import {classifyAction} from '../../supabase/functions/_shared/action-risk';
import {SALES_INVOICE_CAPABILITIES,SALES_INVOICE_KIT_CAPABILITIES,SALES_INVOICE_CREATE_LINK_CAPABILITY,SALES_INVOICE_RECORD_PAYMENT_CAPABILITY,SALES_INVOICE_KIT_BY_ACTION,SALES_INVOICE_READ_CAPABILITY,SALES_INVOICE_EMAIL_CAPABILITY,SALES_INVOICE_SETTINGS_CAPABILITY,SALES_INVOICE_PREFERENCES_READ_CAPABILITY} from '../../supabase/functions/_shared/paige-spine/domains/sales_invoice';
import {parseSalesInvoiceCommand} from '../../supabase/functions/_shared/sales-invoice-command/contract';
import {SALES_DRAFT_CREATE,SALES_DRAFT_REVISE} from '../../supabase/functions/_shared/sales-commercial/draft-capabilities';
import {SALES_INVOICE_TOOLS} from '../../supabase/functions/_shared/sales-invoice-chat';
it('all six business actions cold-start as high confirm declarations for the existing execution/readback/Rail seams',()=>{expect(SALES_INVOICE_KIT_CAPABILITIES.map(c=>c.governance.actionRiskKey)).toEqual(['sales_update_invoice_settings','sales_publish_invoice','sales_record_manual_payment','sales_reverse_manual_payment','sales_void_invoice','sales_create_invoice_link']);for(const c of SALES_INVOICE_KIT_CAPABILITIES){expect(c.governance.risk).toBe(classifyAction(c.governance.actionRiskKey!));expect(c.governance.risk).toBe('high');expect(c.governance.approval).toBe('confirm');expect(c.providerBinding.operation).toBe('public.execute_sales_invoice_command');expect(c.idempotency).toMatchObject({mode:'required',readback:'public.read_sales_invoice_command_result',replay:'return_recorded_result'});expect(c.receipt).toMatchObject({rail:true,recorder:'record_capability_run',redaction:'tenant_safe'});expect(c.tenantScope.revalidateAt).toEqual(['before_availability','before_execution','before_receipt']);expect(c.input.additionalProperties).toBe(false);expect(Object.isFrozen(c)).toBe(true);}});
it('human-only customer link declaration adds no Chat tool or live Chat Spine binding',()=>{expect(SALES_INVOICE_CREATE_LINK_CAPABILITY.effect).toBe('external_effect');expect(SALES_INVOICE_CREATE_LINK_CAPABILITY.input.properties).not.toHaveProperty('token');expect(SALES_INVOICE_CREATE_LINK_CAPABILITY.input.properties).not.toHaveProperty('governance');expect(SALES_INVOICE_CAPABILITIES.some(c=>c.action?.chatTool==='sales_create_invoice_link')).toBe(false);expect(new Set<string>(SALES_INVOICE_TOOLS.map(t=>t.function.name)).has('sales_create_invoice_link')).toBe(false);});
it('receipt declaration bounds financial facts and leaves exact semantic validation in canonical parser',()=>{const input=SALES_INVOICE_RECORD_PAYMENT_CAPABILITY.input;expect(input.required).toEqual(['action','invoice_id','expected_version','amount_cents','currency','method','received_at']);expect(input.properties.amount_cents).toEqual({type:'integer',minimum:1,maximum:2147483647});expect(input.properties.method).toMatchObject({enum:['zelle','cash','wire','check','bank_transfer','other']});expect(input.properties.notes).toEqual({anyOf:[{type:'string',maxLength:2000},{type:'null'}]});const base={action:'invoice.record_manual_payment',invoice_id:'11111111-1111-4111-8111-111111111111',expected_version:1,amount_cents:500,currency:'usd',method:'cash',received_at:'2026-10-03T12:00:00Z'};expect(parseSalesInvoiceCommand(base).amount_cents).toBe(500);expect(()=>parseSalesInvoiceCommand({...base,amount_cents:0})).toThrow();expect(()=>parseSalesInvoiceCommand({...base,governance:{approval:true}})).toThrow();});

it('closed Chat schemas preserve fields and source their saved-version contract from real declarations',()=>{expect(SALES_INVOICE_TOOLS.map(t=>t.function.name)).toEqual(['billing_create_invoice','sales_revise_invoice_draft','read_sales_commercial_offers','sales_create_payment_request','read_sales_invoice_preferences','sales_update_invoice_settings','read_sales_invoice','sales_publish_invoice','sales_record_manual_payment','sales_reverse_manual_payment','sales_void_invoice','billing_send_invoice']);const read=SALES_INVOICE_TOOLS.find(t=>t.function.name==='read_sales_invoice')!.function.parameters;expect(read).toBe(SALES_INVOICE_READ_CAPABILITY.input);expect(read.required).toEqual(['invoice_id']);for(const tool of SALES_INVOICE_TOOLS.filter(t=>!t.function.name.startsWith('read_'))){const declaration=tool.function.name==='billing_create_invoice'?SALES_DRAFT_CREATE:tool.function.name==='sales_revise_invoice_draft'?SALES_DRAFT_REVISE:SALES_INVOICE_KIT_BY_ACTION[tool.function.name as keyof typeof SALES_INVOICE_KIT_BY_ACTION];expect(tool.function.parameters.required).toEqual(declaration.input.required.filter(key=>key!=='action'));expect(Object.keys(tool.function.parameters.properties)).toEqual(expect.arrayContaining(Object.keys(declaration.input.properties).filter(key=>key!=='action')));expect(tool.function.parameters.additionalProperties).toBe(false);expect(tool.function.parameters.properties).not.toHaveProperty('expected_tenant_id');expect(tool.function.parameters.properties).not.toHaveProperty('governance');expect(tool.function.parameters.properties).not.toHaveProperty('approved_fingerprint');}expect((SALES_INVOICE_TOOLS.find(t=>t.function.name==='sales_record_manual_payment')!.function.parameters.properties as Readonly<Record<string,unknown>>).reference).toEqual({type:['string','null'],maxLength:200});expect((SALES_INVOICE_TOOLS.find(t=>t.function.name==='sales_record_manual_payment')!.function.parameters.properties as Readonly<Record<string,unknown>>).notes).toEqual({type:['string','null'],maxLength:2000});expect(SALES_INVOICE_EMAIL_CAPABILITY.governance).toMatchObject({actionRiskKey:'billing_send_invoice',risk:'high',approval:'confirm'});expect(SALES_INVOICE_EMAIL_CAPABILITY.idempotency).toMatchObject({readback:'public.read_sales_invoice_delivery_result',replay:'reconcile_then_return'});});

it('settings read has no write authority and settings mutation has no invented invoice reference',()=>{
 const read=SALES_INVOICE_TOOLS.find(t=>t.function.name==='read_sales_invoice_preferences')!;
 expect(read.function.parameters).toBe(SALES_INVOICE_PREFERENCES_READ_CAPABILITY.input);
 expect(SALES_INVOICE_PREFERENCES_READ_CAPABILITY.governance).toMatchObject({actionRiskKey:null,risk:'read_only',approval:'none'});
 expect(SALES_INVOICE_PREFERENCES_READ_CAPABILITY.providerBinding.operation).toBe('public.read_sales_invoice_preferences');
 expect(SALES_INVOICE_SETTINGS_CAPABILITY.input.required).toEqual(['action','expected_version','settings']);
 expect(SALES_INVOICE_SETTINGS_CAPABILITY.input.properties).not.toHaveProperty('invoice_id');
 expect(SALES_INVOICE_SETTINGS_CAPABILITY.input.properties.expected_version).toEqual({type:'integer',minimum:0});
 expect(SALES_INVOICE_SETTINGS_CAPABILITY.governance).toMatchObject({actionRiskKey:'sales_update_invoice_settings',risk:'high',approval:'confirm'});
 expect(SALES_INVOICE_CAPABILITIES.find(c=>c.key==='sales_invoice.settings_update')?.action).toMatchObject({chatTool:'sales_update_invoice_settings',approvalAuthority:'chat-canonical',executor:'public.execute_sales_invoice_command'});
});

it('internal preference read and update use the existing no-provider readiness resolver',()=>{
 for(const key of ['sales_invoice.preferences_read','sales_invoice.settings_update']){
  expect(SALES_INVOICE_CAPABILITIES.find(c=>c.key===key)?.readiness).toBe('none');
 }
});

it('hosted request is high confirm and accepts only caller intent, never merchant/currency/authority/card facts',()=>{
 const c=SALES_INVOICE_KIT_BY_ACTION.sales_create_payment_request;
 expect(c.governance).toMatchObject({risk:'high',approval:'confirm',actionRiskKey:'sales_create_payment_request'});
 expect(classifyAction('sales_create_payment_request')).toBe('high');
 expect(c.providerBinding.operation).toBe('public.prepare_sales_invoice_payment_request');
 expect(c.idempotency).toMatchObject({mode:'required',replay:'reconcile_then_return'});
 expect(c.input.additionalProperties).toBe(false);
 for(const key of ['tenant_id','client_id','currency','merchant_account_id','approved','card_number','cvv'])expect(c.input.properties).not.toHaveProperty(key);
 expect(SALES_INVOICE_CAPABILITIES.find(x=>x.key==='sales_invoice.payment_request')?.action?.chatTool).toBe('sales_create_payment_request');
});
