import {readFileSync} from 'node:fs';
import {transpileModule,ModuleKind,ScriptTarget} from 'typescript';
import {describe,it,expect} from 'vitest';
import {aggregateInvoiceItems} from '../solo/sales/invoiceDraftSnapshot';
import {UUID,FINGERPRINT} from '../../supabase/functions/_shared/sales-invoice-command/contract';
import {parseCommercialDraftCommand} from '../../supabase/functions/_shared/sales-commercial/draft-command';
import {validateCatalogPriceFacts} from '../../supabase/functions/_shared/sales-commercial/catalog-facts';
import {commercialDraftWorkOrder} from '../../supabase/functions/_shared/sales-commercial/draft-work-order';
import {admitCommercialDraft} from '../../supabase/functions/_shared/sales-commercial/draft-admission';
import {SALES_DRAFT_SPINE} from '../../supabase/functions/_shared/sales-commercial/draft-capabilities';
import {projectCapabilities} from '../../supabase/functions/_shared/paige-capability-status/projection';
const tenant='20000000-0000-0000-0000-000000000001',actor='10000000-0000-0000-0000-000000000001',op='70000000-0000-0000-0000-000000000001';
const draft={schema_version:3,client_id:'30000000-0000-0000-0000-000000000001',items:[{price_id:null,item:'Service',unit_minor:350000,quantity:1}],kind:'deposit',deposit_basis_points:null,deposit_minor:50000,currency:'usd',cadence:null,recipient_email:null,recipient_phone:null,email_source_method_id:null,phone_source_method_id:null,billing_address:null,agreement_id:null,processor_intent:null,payment_method_intents:[],delivery_channel_intents:['email'],due_date:'2026-11-01',memo:null};
const intent={action:'invoice.draft_create' as const,draft};
const body={expected_tenant_id:tenant,operation_id:op,intent};
const source=readFileSync('supabase/functions/sales-invoice-draft-command/index.ts','utf8').replace(/^import .*;\r?\n/gm,'');
const compiled=transpileModule(source,{compilerOptions:{module:ModuleKind.None,target:ScriptTarget.ES2022}}).outputText;
type Options={authenticated?:boolean;role?:string;lane?:string;current?:string;currentSequence?:string[];claimed?:unknown;replay?:unknown;clientMissing?:boolean;auditFails?:boolean;executeError?:unknown;pending?:unknown;catalog?:unknown};
function setup(options:Options={}){
 let handler:(r:Request)=>Promise<Response>=async()=>new Response();
 const calls:{name:string;args:unknown}[]=[];
 let currentRead=0;
 const caller={auth:{getUser:async()=>({data:{user:options.authenticated===false?null:{id:actor}},error:null})},rpc:async(name:string)=>({data:name==='current_user_tenant_id'?options.currentSequence?.[currentRead++]??options.current??tenant:options.lane??'confirm',error:null})};
 const admin={rpc:async(name:string,args:unknown)=>{calls.push({name,args});return {data:['read_sales_invoice_command_result','read_sales_invoice_draft_intent_result'].includes(name)?options.replay??null:name==='read_sales_invoice_draft_catalog'?options.catalog??null:{ok:true,outcome:'draft_created',row:{id:'60000000-0000-0000-0000-000000000001',status:'draft',version:1}},error:name==='execute_sales_invoice_draft_command'?options.executeError??null:null}},from:(table:string)=>{
  let mutation='';const filters:unknown[]=[];const q:Record<string,unknown>={};
  for(const method of ['eq','is','not','neq','gt','contains','limit'])q[method]=(...args:unknown[])=>{filters.push([method,...args]);return q};
  q.select=()=>q;q.update=()=>{mutation='update';return q};q.insert=(args:unknown)=>{mutation='insert';calls.push({name:'insert:'+table,args});return q};
  q.maybeSingle=async()=>{if(table==='paige_pending_confirmations')calls.push({name:`query:${mutation||'select'}:${table}`,args:filters});return {data:table==='tenant_members'?{role:options.role??'owner',status:'active'}:table==='clients'?options.clientMissing?null:{first_name:'Test',last_name:'Customer',entity_name:null,entity_type:null}:mutation==='update'?options.claimed?{args:options.claimed}:null:options.pending??null,error:null}};
  q.then=(resolve:(value:unknown)=>unknown,reject:(reason:unknown)=>unknown)=>Promise.resolve({error:table==='paige_audit_log'&&options.auditFails?{code:'failure'}:null}).then(resolve,reject);
  return q;
 }};
 const scope={Deno:{env:{get:(k:string)=>k},serve:(fn:typeof handler)=>handler=fn},createClient:(_url:string,key:string)=>key==='SUPABASE_ANON_KEY'?caller:admin,
  confirmFingerprint:async()=> '0123456789abcdef',databaseAnswered:(e:unknown)=>!!e&&typeof e==='object'&&'code' in e&&e.code==='23514',UUID,FINGERPRINT,parseCommercialDraftCommand,commercialDraftWorkOrder,admitCommercialDraft,SALES_DRAFT_SPINE,projectCapabilities,aggregateInvoiceItems,validateCatalogPriceFacts};
 new Function(...Object.keys(scope),compiled)(...Object.values(scope));
 return {calls,invoke:async(patch:Record<string,unknown>={})=>{const response=await handler(new Request('http://localhost',{method:'POST',body:JSON.stringify({...body,...patch})}));return {status:response.status,body:await response.json()}}};
}
describe('actual draft endpoint with network/auth fixtures, not hosted proof',()=>{
 it('unauthenticated and non-owner calls never perform a business RPC',async()=>{for(const options of [{authenticated:false},{role:'member'},{current:actor}]){const h=setup(options);expect((await h.invoke()).status).toBeGreaterThanOrEqual(400);expect(h.calls).toEqual([])}});
 it('rejects request-supplied authority before business work',async()=>{const h=setup();expect((await h.invoke({approved:true})).status).toBe(400);expect(h.calls).toEqual([])});
 it('proposes exact dollars and stores server invoice identity through the existing confirmation store',async()=>{const h=setup();const r=await h.invoke();expect(r.body.outcome).toBe('approval_required');expect(r.body.summary).toContain('$3,500.00');expect(r.body.summary).toContain('$500.00');expect(r.body.summary).toContain('$3,000.00');expect(r.body.summary).toContain('Test Customer');expect(h.calls.some(c=>c.name==='execute_sales_invoice_draft_command')).toBe(false);const card=h.calls.find(c=>c.name==='insert:paige_pending_confirmations')?.args as {args:{command:{expected_version:number;invoice_id:string}}};expect(card.args.command.expected_version).toBe(0);expect(UUID.test(card.args.command.invoice_id)).toBe(true)});
 it('current ordinary AUTO executes only the canonical draft RPC with standing authority',async()=>{const h=setup({lane:'auto'});const r=await h.invoke();expect(r.body.outcome).toBe('draft_created');const execution=h.calls.find(c=>c.name==='execute_sales_invoice_draft_command')?.args as Record<string,unknown>;expect(execution._governance).toMatchObject({approval_channel:'standing_autonomy_setting',tool:'billing_create_invoice',decision_receipt_recorded:true})});
 it('failed claim never falls through current AUTO',async()=>{const h=setup({lane:'auto'});const r=await h.invoke({approved_fingerprint:'0123456789abcdef'});expect(r.body.outcome).toBe('approval_required');expect(h.calls.some(c=>c.name==='execute_sales_invoice_draft_command')).toBe(false)});
 it('executes original stored commercial terms after the model changes its memo',async()=>{const command=await commercialDraftWorkOrder(intent,{tenantId:tenant,actorId:actor,operationId:op});const h=setup({claimed:{expected_tenant_id:tenant,operation_id:op,command}});expect((await h.invoke({intent:{...intent,draft:{...draft,memo:'Changed'}},approved_fingerprint:'0123456789abcdef'})).body.ok).toBe(true);expect((h.calls.find(c=>c.name==='execute_sales_invoice_draft_command')?.args as {_command:{draft:{memo:unknown}}})._command.draft.memo).toBeNull()});
 it('off and audit failure prevent business mutation',async()=>{for(const options of [{lane:'off'},{lane:'auto',auditFails:true}]){const h=setup(options);expect((await h.invoke()).status).toBeGreaterThanOrEqual(400);expect(h.calls.some(c=>c.name==='execute_sales_invoice_draft_command')).toBe(false)}});
 it('historical replay precedes current client/catalog eligibility and consumes no approval',async()=>{const h=setup({clientMissing:true,replay:{ok:true,outcome:'draft_created'}});expect((await h.invoke()).body.replayed).toBe(true);expect(h.calls).toHaveLength(1)});
 it('approval redemption is one scoped unconsumed unexpired server-issued claim',async()=>{const command=await commercialDraftWorkOrder(intent,{tenantId:tenant,actorId:actor,operationId:op});const h=setup({claimed:{expected_tenant_id:tenant,operation_id:op,command}});await h.invoke({approved_fingerprint:'0123456789abcdef'});const filters=h.calls.find(c=>c.name==='query:update:paige_pending_confirmations')?.args as unknown[][];for(const expected of [['eq','user_id',actor],['eq','tenant_id',tenant],['eq','tool_name','billing_create_invoice'],['eq','fingerprint','0123456789abcdef'],['is','consumed_at',null],['is','thread_id',null],['is','scoped_client_id',null],['not','server_issued_at','is',null],['not','issued_in_request','is',null]])expect(filters).toContainEqual(expected);expect(filters.some(f=>f[0]==='gt'&&f[1]==='expires_at')).toBe(true);expect(filters.some(f=>f[0]==='neq'&&f[1]==='issued_in_request')).toBe(true)});
 it('workspace switching before replay, proposal, claim or execution fails closed',async()=>{for(const options of [{currentSequence:[tenant,actor]},{currentSequence:[tenant,tenant,actor]},{lane:'auto',currentSequence:[tenant,tenant,actor]}]){const h=setup(options);expect((await h.invoke()).body.code).toBe('WORKSPACE_CHANGED');expect(h.calls.some(c=>c.name==='execute_sales_invoice_draft_command'||c.name==='insert:paige_pending_confirmations')).toBe(false)}const command=await commercialDraftWorkOrder(intent,{tenantId:tenant,actorId:actor,operationId:op});const h=setup({claimed:{expected_tenant_id:tenant,operation_id:op,command},currentSequence:[tenant,tenant,tenant,actor]});expect((await h.invoke({approved_fingerprint:'0123456789abcdef'})).body.code).toBe('WORKSPACE_CHANGED');expect(h.calls.some(c=>c.name==='execute_sales_invoice_draft_command')).toBe(false)});
 it('unresolved catalog pricing requires input without claiming approval',async()=>{const h=setup({lane:'auto'});expect((await h.invoke({intent:{...intent,draft:{...draft,items:[{...draft.items[0],price_id:actor,unit_minor:null}]}}})).body.code).toBe('CATALOG_PRICE_REVIEW_REQUIRED');expect(h.calls.some(c=>c.name.startsWith('query:')||c.name==='execute_sales_invoice_draft_command')).toBe(false)});
 it('revision preserves the canonical identity and exact optimistic version',async()=>{const h=setup({lane:'auto'});await h.invoke({intent:{action:'invoice.draft_revise',invoice_id:actor,expected_version:7,draft}});const execution=h.calls.find(c=>c.name==='execute_sales_invoice_draft_command')?.args as {_command:{invoice_id:string;expected_version:number};_governance:{tool:string}};expect(execution._command).toMatchObject({invoice_id:actor,expected_version:7});expect(execution._governance.tool).toBe('sales_revise_invoice_draft')});
 it('missing client and invalid/excess deposit never reach approval or mutation',async()=>{for(const test of [{options:{clientMissing:true},patch:{}},{options:{},patch:{intent:{...intent,draft:{...draft,deposit_minor:350000}}}}]){const h=setup(test.options);expect((await h.invoke(test.patch)).status).toBe(422);expect(h.calls.some(c=>c.name==='execute_sales_invoice_draft_command'||c.name==='insert:paige_pending_confirmations')).toBe(false)}});
 it('ambiguous database transport preserves outcome_unknown and the existing operation',async()=>{const h=setup({lane:'auto',executeError:{message:'network'}});const r=await h.invoke();expect(r.body).toMatchObject({outcome:'outcome_unknown',operation_id:op});expect(h.calls.filter(c=>c.name==='execute_sales_invoice_draft_command')).toHaveLength(1)});
});

const catalogPrice={price_id:'40000000-0000-4000-8000-000000000001',product_id:'50000000-0000-4000-8000-000000000001',product_name:'Catalog service',unit_minor:175000,currency:'usd',kind:'one_time',billing_interval:'one_time',interval_count:null,installments_total:null,active:true,product_status:'active'};
const catalogIntent={...intent,draft:{...draft,items:[{price_id:catalogPrice.price_id,item:'Catalog service',unit_minor:null,quantity:2}]}};
describe('catalog-backed actual draft endpoint',()=>{
 it('reviews frozen facts and deterministic quantity arithmetic without execution',async()=>{const h=setup({catalog:{tenant_id:tenant,prices:[catalogPrice]}});const r=await h.invoke({intent:catalogIntent});expect(r.body.outcome).toBe('approval_required');expect(r.body.summary).toContain('2 × $1,750.00 per unit = $3,500.00');expect(r.body.summary).toContain('$500.00');const row=h.calls.find(c=>c.name==='insert:paige_pending_confirmations')?.args as {args:{command:{catalog_prices:unknown}}};expect(row.args.command.catalog_prices).toEqual([catalogPrice]);expect(h.calls.some(c=>c.name==='execute_sales_invoice_draft_command')).toBe(false)});
 it('catalog historical replay does not depend on current price or customer',async()=>{const h=setup({clientMissing:true,replay:{ok:true,outcome:'draft_created'}});expect((await h.invoke({intent:catalogIntent})).body.replayed).toBe(true);expect(h.calls.map(c=>c.name)).toEqual(['read_sales_invoice_draft_intent_result'])});
 it('foreign tenant, missing price, paused price and unsafe source fields refuse before approval',async()=>{for(const catalog of [{tenant_id:actor,prices:[catalogPrice]},{tenant_id:tenant,prices:[]},{tenant_id:tenant,prices:[{...catalogPrice,active:false}]},{tenant_id:tenant,prices:[{...catalogPrice,stripe_price_id:'unsafe'}]}]){const h=setup({catalog,lane:'auto'});expect((await h.invoke({intent:catalogIntent})).body.code).toBe('CATALOG_PRICE_REVIEW_REQUIRED');expect(h.calls.some(c=>c.name==='execute_sales_invoice_draft_command'||c.name==='insert:paige_pending_confirmations')).toBe(false)}});
});

describe('definitive stale review recovery',()=>{
 it('a rolled-back SQL version/source conflict requests fresh review instead of ambiguous retry',async()=>{const h=setup({lane:'auto',catalog:{tenant_id:tenant,prices:[catalogPrice]},executeError:{code:'40001'}});const r=await h.invoke({intent:catalogIntent});expect(r.status).toBe(409);expect(r.body).toMatchObject({outcome:'needs_input',code:'DRAFT_REVIEW_CHANGED',operation_id:op});expect(r.body.message).toContain('fresh review');expect(h.calls.filter(c=>c.name==='execute_sales_invoice_draft_command')).toHaveLength(1)});
});
