import {describe,it,expect,vi} from 'vitest';
import {SALES_COLLECTIONS_TOOLS,dispatchSalesCollectionsChat,salesCollectionsOperationId,salesCollectionsSafeResult} from '../../supabase/functions/_shared/sales-collections-chat.ts';
const tenant='11111111-1111-4111-8111-111111111111',batch='22222222-2222-4222-8222-222222222222',op='33333333-3333-4333-8333-333333333333',fingerprint='abcdef0123456789',digest='a'.repeat(64);
const command={action:'collection.commit_import',batch_id:batch,expected_digest:digest};
const ctx={tenantId:tenant,userId:'actor',toolName:'sales_commit_collection_import',args:{batch_id:batch,expected_digest:digest},approved:new Set<string>(),sameToolCalls:1,turn:{thread_id:null,user_turn_ordinal:1,user_turn:'Commit reviewed batch'}};
function harness(rows:unknown[]=[]){const predicates:unknown[]=[],calls:unknown[]=[];const q:Record<string,unknown>={};for(const name of ['eq','in','is','not','gt'])q[name]=(...a:unknown[])=>{predicates.push([name,...a]);return q};q.limit=async()=>({data:rows,error:null});const deps={admin:{from:()=>({select:()=>q})},caller:{rpc:async():Promise<{data:unknown;error:unknown}>=>({data:{tenant_id:tenant,receipt_id:op,rows:[{id:batch,status:'recorded',amount_cents:100,currency:'jpy',remaining_cents:50,record_kind:'imported',client_id:'private',client_name:'private',memo:'private'}],has_more:false,next_cursor:null},error:null}),functions:{invoke:async(name:string,options:unknown):Promise<{data:unknown;error:unknown}>=>{calls.push({name,...options as object});return{data:{ok:true,batch:{id:batch,state:'committed',written:2,matched:1,rows:[{client_id:'private'}],source_account:'private'}},error:null}}}}};return{deps,calls,predicates};}
describe('canonical Collections Chat adapter',()=>{
 it('requires caller workspace and a canonical read receipt before returning any facts',async()=>{for(const change of [{tenant_id:batch},{receipt_id:null},{receipt_id:'private'}]){const h=harness();h.deps.caller.rpc=async()=>({data:{tenant_id:tenant,receipt_id:op,rows:[],has_more:false,next_cursor:null,...change},error:null});const r=await dispatchSalesCollectionsChat({...ctx,toolName:'read_sales_collections',args:{entity:'agreement'}},h.deps as never);expect(r.content.success).toBe(false);expect(r.content).not.toHaveProperty('rows')}});
 it('resolves the recorded commercial owner and client without claiming a signed agreement',async()=>{const h=harness();h.deps.caller.rpc=async()=>({data:{tenant_id:tenant,receipt_id:op,rows:[{id:batch,tenant_id:tenant,client_id:op,offer_id:null,title:'Recorded terms',title_truncated:false,client_name:'Client X',client_name_truncated:false,status:'draft',agreed_amount_minor:null,agreed_currency:null,collection_terms:null,collection_terms_version:0,terms_current:false,notes:'PRIVATE'}],has_more:false,next_cursor:null},error:null});const r=await dispatchSalesCollectionsChat({...ctx,toolName:'read_sales_collections',args:{entity:'agreement'}},h.deps as never);expect(r.content).toMatchObject({success:true,receipt_id:op,rows:[{client_id:op,title:'Recorded terms',terms_state:'absent',record_owner:'commercial_collection_terms',signing_agreement_resolved:false}]});expect(JSON.stringify(r)).not.toContain('PRIVATE');expect(h.calls).toHaveLength(0)});
 it('offers canonical commercial creation, existing collection mutators and bounded read, no duplicate receipt or link tool',()=>{expect(SALES_COLLECTIONS_TOOLS.map(t=>t.function.name)).toEqual(['sales_create_commercial_terms','read_sales_collections','sales_save_collection_terms','sales_stage_collection_import','sales_commit_collection_import']);for(const t of SALES_COLLECTIONS_TOOLS)expect(t.function.parameters.properties).not.toHaveProperty('approved_fingerprint')});
 it('uses deterministic tenant/actor/action operation and endpoint only',async()=>{const h=harness();await dispatchSalesCollectionsChat(ctx,h.deps as never);expect(h.calls[0]).toMatchObject({name:'sales-collection-command',body:{command,expected_tenant_id:tenant}});const a=await salesCollectionsOperationId(tenant,'actor',command,ctx.turn);expect(await salesCollectionsOperationId(tenant,'actor',command,ctx.turn)).toBe(a);expect(await salesCollectionsOperationId(batch,'actor',command,ctx.turn)).not.toBe(a)});
 it('selects stored human-approved exact command and original operation; endpoint alone consumes',async()=>{const h=harness([{fingerprint,args:{command,operation_id:op,expected_tenant_id:tenant,approval_subject:'collection.commit_import:'+batch}}]);await dispatchSalesCollectionsChat({...ctx,approved:new Set([fingerprint]),args:{batch_id:batch,expected_digest:'b'.repeat(64)}},h.deps as never);expect(h.calls[0]).toMatchObject({body:{command,operation_id:op,approved_fingerprint:fingerprint}});expect(h.predicates).toContainEqual(['is','thread_id',null]);expect(h.predicates).toContainEqual(['is','consumed_at',null])});
 it('refuses scoped, ambiguous and foreign approval candidates without dispatch',async()=>{for(const [rows,approved] of [[[{fingerprint,args:{command,operation_id:op,expected_tenant_id:tenant}}],new Set([fingerprint+':'+batch])],[[{fingerprint,args:{}},{fingerprint:'0123456789abcdef',args:{}}],new Set([fingerprint,'0123456789abcdef'])],[[{fingerprint,args:{command,operation_id:op,expected_tenant_id:batch}}],new Set([fingerprint])]] as const){const h=harness([...rows]);expect((await dispatchSalesCollectionsChat({...ctx,approved},h.deps as never)).refusal).toBeTruthy();expect(h.calls).toHaveLength(0)}});
 it('rejects model authority/action/operation injection and malformed scope',async()=>{for(const args of [{...ctx.args,action:'collection.stage_import'},{...ctx.args,approved_fingerprint:fingerprint},{...ctx.args,operation_id:op},null,[]]){const h=harness();expect((await dispatchSalesCollectionsChat({...ctx,args:args as never},h.deps as never)).content.success).toBe(false);expect(h.calls).toHaveLength(0)}});
 it('returns bounded canonical reads without client identifiers, names or free text',async()=>{const h=harness();const rpc=vi.spyOn(h.deps.caller,'rpc');const r=await dispatchSalesCollectionsChat({...ctx,toolName:'read_sales_collections',args:{entity:'invoice',limit:10}},h.deps as never);expect(r.content).toMatchObject({success:true,rows:[{id:batch,currency:'jpy',remaining_cents:50,record_kind:'imported'}]});expect(JSON.stringify(r)).not.toContain('private');expect(h.calls).toHaveLength(0);expect(rpc).toHaveBeenCalledWith('read_sales_collections',{_expected_tenant_id:tenant,_entity:'invoice',_limit:10,_cursor:null,_before_id:null})});
 it('omits unrecognized record kinds instead of inferring one',async()=>{const h=harness();h.deps.caller.rpc=async()=>({data:{tenant_id:tenant,receipt_id:op,rows:[{id:batch,status:'recorded',record_kind:'invented'}],has_more:false,next_cursor:null},error:null});const r=await dispatchSalesCollectionsChat({...ctx,toolName:'read_sales_collections',args:{entity:'invoice'}},h.deps as never);expect(r.content.success).toBe(true);expect(r.content.rows).toEqual([{id:batch,status:'recorded'}]);});
 it('refuses excessive limits and malformed cursor before reads',async()=>{for(const args of [{entity:'invoice',limit:51},{entity:'invoice',cursor:{snapshot_id:batch,after_position:1,entity:'receipt'}},{entity:'agreement',cursor:{snapshot_id:batch,after_position:1,entity:'agreement'}}]){expect((await dispatchSalesCollectionsChat({...ctx,toolName:'read_sales_collections',args},harness().deps as never)).content.success).toBe(false)}});
 it('projects stage/commit summaries without raw rows, references or free text',()=>{const safe=salesCollectionsSafeResult({ok:true,batch:{id:batch,content_digest:digest,state:'staged',rows:[{memo:'private',client_id:'private'}],review:{conflicts:[{raw:'private'}]}}});expect(safe).toMatchObject({batch_id:batch,digest,status:'staged',row_count:1,conflict_count:1});expect(JSON.stringify(safe)).not.toContain('private')});
 it('forwards only real canonical proposal identity and refuses unanswered result',async()=>{const h=harness();h.deps.caller.functions.invoke=async()=>({data:{outcome:'approval_required',fingerprint,summary:'Review import',rows:'private'},error:null});expect((await dispatchSalesCollectionsChat(ctx,h.deps as never)).content).toMatchObject({needs_confirm:true,confirm_fingerprint:fingerprint});h.deps.caller.functions.invoke=async()=>{throw Error('private')};const r=await dispatchSalesCollectionsChat(ctx,h.deps as never);expect(r.content).toMatchObject({success:false,outcome:'outcome_unknown'});expect(JSON.stringify(r)).not.toContain('private')});
});







const commercial={action:'collection.create_commercial_terms',client_id:batch,offer_id:op,term_kind:'installment',agreed_amount_minor:350000,agreed_currency:'usd',billing_interval:'month',interval_count:1,installments_total:10,payment_schedule:'custom',starts_on:'2026-11-01',ends_on:null,title:null,notes:null} as const;
describe('canonical commercial creation Chat readback',()=>{
 it('dispatches the exact new draft-obligation act and returns safe canonical references',async()=>{const h=harness();h.deps.caller.functions.invoke=async(_name,options)=>{const body=(options as {body:{operation_id:string}}).body;return{data:{ok:true,outcome:'commercial_terms_created',row:{id:op,tenant_id:tenant,client_id:batch,offer_id:op,status:'draft',amount_cents:350000,currency:'usd',notes:'PRIVATE'},operation:{id:body.operation_id,action:commercial.action}},error:null}};const {action,...args}=commercial;const r=await dispatchSalesCollectionsChat({...ctx,toolName:'sales_create_commercial_terms',args},h.deps as never);expect(r.content).toMatchObject({success:true,commercial_terms_id:op,status:'draft',amount_cents:350000});expect(JSON.stringify(r)).not.toContain('PRIVATE');});
 it.each([{tenant_id:batch},{client_id:op},{offer_id:batch},{amount_cents:350001},{currency:'jpy'},{status:'active'},{id:'not-a-reference'}])('refuses mismatched commercial readback %j',async(change)=>{const h=harness();h.deps.caller.functions.invoke=async(_name,options)=>({data:{ok:true,outcome:'commercial_terms_created',row:{id:op,tenant_id:tenant,client_id:batch,offer_id:op,status:'draft',amount_cents:350000,currency:'usd',...change},operation:{id:(options as {body:{operation_id:string}}).body.operation_id,action:commercial.action}},error:null});const {action,...args}=commercial;const r=await dispatchSalesCollectionsChat({...ctx,toolName:'sales_create_commercial_terms',args},h.deps as never);expect(r.content).toMatchObject({success:false,outcome:'outcome_unknown'});expect(r.content).not.toHaveProperty('commercial_terms_id');});
});
