import React from 'react';
import {supabase} from '@/integrations/supabase/client';
import type {BillingRpc} from './billingDrafts';
import {readInvoiceRecord,type InvoiceRecord} from './invoiceLifecycleApi';
import {InvoiceCommandReview} from './InvoiceCommandReview';
import type {SalesInvoiceCommand} from '../../../supabase/functions/_shared/sales-invoice-command/contract';
import {PAIGE_APP_ORIGIN} from '../../../supabase/functions/_shared/canonical-app-url';
import {useSalesDraftExit} from '../sales-dialog';
import {readInvoicePdf,downloadInvoicePdf} from './invoicePdf';
import {useTheme} from 'next-themes';
import {invoiceDeliveryReadinessCopy} from './invoiceDeliveryCopy';
import {invoiceDisplayNumber,invoicePaymentStatus} from './invoicePaymentCopy';
const cash=(n:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(n/100);
export function InvoiceLifecycleActions({tenantId,invoiceId,version,canManage,onChanged,workspaceCloseEvent,onWorkspaceClose}:{tenantId:string;invoiceId:string;version:number;canManage:boolean;onChanged():void;workspaceCloseEvent?:string;onWorkspaceClose?:()=>void}){
  const [pane,setPane]=React.useState<'records'|'send'>('records');
  const [row,setRow]=React.useState<InvoiceRecord|null>(null),[error,setError]=React.useState(false),[refresh,setRefresh]=React.useState(0);
  const [correctionReceipt,setCorrectionReceipt]=React.useState<string|null>(null);
  const [command,setCommand]=React.useState<SalesInvoiceCommand|null>(null),[link,setLink]=React.useState('');
  const [amount,setAmount]=React.useState(''),[method,setMethod]=React.useState('cash'),[date,setDate]=React.useState(()=>new Date().toISOString().slice(0,10)),[reference,setReference]=React.useState(''),[notes,setNotes]=React.useState(''),[reason,setReason]=React.useState('');
  const [form,setForm]=React.useState<'payment'|'void'|'correction'|null>(null),[notice,setNotice]=React.useState('');
  const formReview=React.useRef<HTMLButtonElement>(null),restoreFormFocus=React.useRef(false),returnFocusLabel=React.useRef(''),actionWrapper=React.useRef<HTMLDivElement>(null);
  const [deliveryChannel,setDeliveryChannel]=React.useState<'email'|'sms'>('email');
  const [senders,setSenders]=React.useState<{id:string;provider:string;from_address:string}[]>([]),[sender,setSender]=React.useState(''),[senderStatus,setSenderStatus]=React.useState('Reading email connections…'),[emailEligible,setEmailEligible]=React.useState(false),[emailBusy,setEmailBusy]=React.useState(false);
  const alive=React.useRef(true),scope=React.useRef(`${tenantId}:${invoiceId}`);scope.current=`${tenantId}:${invoiceId}`;
  const deliveryRequest=React.useRef(0);
  const emailScope=React.useRef('');emailScope.current=`${tenantId}:${invoiceId}:${version}:${row?.version??''}:${sender}:${deliveryChannel}`;
  React.useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
  React.useLayoutEffect(()=>{if(command||form||!returnFocusLabel.current)return;const button=[...(actionWrapper.current?.querySelectorAll<HTMLButtonElement>('button')??[])].find(b=>b.textContent===returnFocusLabel.current);button?.focus();},[command,form]);
  const exit=useSalesDraftExit(form?{amount,method,date,reference,notes,reason}:null,!!command,()=>setForm(null));
  const requestFormExit=exit.request;
  React.useLayoutEffect(()=>{if(!form||command)return;const target=[...(actionWrapper.current?.querySelectorAll<HTMLElement>('input,textarea,select')??[])].find(el=>el.offsetParent!==null);target?.focus();target?.scrollIntoView({block:'nearest'});},[form,command]);
  React.useEffect(()=>{if(!workspaceCloseEvent||!onWorkspaceClose)return;const close=()=>{if(!command)exit.request(onWorkspaceClose);};window.addEventListener(workspaceCloseEvent,close);return()=>window.removeEventListener(workspaceCloseEvent,close);},[workspaceCloseEvent,onWorkspaceClose,command,exit.request]);
  const navigationAllowed=React.useRef(false);
  React.useEffect(()=>{if(!form)return;const intercept=(event:MouseEvent)=>{if(navigationAllowed.current||!(event.target instanceof Element))return;const target=event.target.closest<HTMLButtonElement>('.sales-tabs button,.sales-payments-tabs button,.sb-toolbar button,.sb-row-link');if(!target||target.disabled)return;event.preventDefault();event.stopImmediatePropagation();requestFormExit(()=>{navigationAllowed.current=true;try{target.click()}finally{navigationAllowed.current=false}});};window.document.addEventListener('click',intercept,true);return()=>window.document.removeEventListener('click',intercept,true);},[form,requestFormExit]);
  React.useEffect(()=>{let alive=true;deliveryRequest.current++;setRow(null);setError(false);setCommand(null);setLink('');setForm(null);
    const rpc:BillingRpc=(name,args)=>(supabase.rpc as unknown as BillingRpc).call(supabase,name,args);
    void Promise.resolve(rpc('read_sales_invoice',{_expected_tenant_id:tenantId,_invoice_id:invoiceId})).then(({data,error})=>{if(!alive)return;const record=!error?readInvoiceRecord(data,tenantId):null;setRow(record);setError(!record);}).catch(()=>{if(alive)setError(true)});
    return()=>{alive=false};
  },[tenantId,invoiceId,version,refresh]);
  React.useEffect(()=>{let current=true;setSenders([]);setSender('');setEmailEligible(false);setEmailBusy(false);if(!row||row.status!=='issued'){setSenderStatus('Publish an invoice before preparing its email.');return;}
    setSenderStatus('Reading email connections…');
    const rpc:BillingRpc=(name,args)=>(supabase.rpc as unknown as BillingRpc).call(supabase,name,args);
    void Promise.resolve(rpc('list_sales_invoice_senders',{_expected_tenant_id:tenantId})).then(({data,error})=>{if(!current)return;if(error||!Array.isArray(data)||data.some(s=>!s||typeof s.id!=='string'||typeof s.provider!=='string'||typeof s.from_address!=='string')){setSenderStatus('Email connections could not be read.');return;}setSenders(data);if(data.length===1)setSender(data[0].id);setSenderStatus(data.length?'Choose the business email connection to prepare delivery.':'Connect a business email sender before preparing delivery.');}).catch(()=>{if(current)setSenderStatus('Email connections could not be read.');});
    return()=>{current=false};
  },[tenantId,row]);
  const checkEmail=async()=>{if(!row||(deliveryChannel==='email'&&!sender)||emailBusy)return;const request=++deliveryRequest.current;const opened=emailScope.current;setEmailBusy(true);setEmailEligible(false);try{const {data,error}=await supabase.functions.invoke('sales-invoice-delivery',{body:{expected_tenant_id:tenantId,command:{action:deliveryChannel==='email'?'invoice.email_send':'invoice.sms_send',invoice_id:row.id,expected_version:row.version,connector_id:deliveryChannel==='email'?sender:null}}});if(!alive.current||emailScope.current!==opened||deliveryRequest.current!==request)return;setEmailEligible(!error&&data?.eligible===true);setSenderStatus(invoiceDeliveryReadinessCopy(data?.readiness?.reason));}catch{if(alive.current&&emailScope.current===opened&&deliveryRequest.current===request)setSenderStatus('Email eligibility could not be read. Retry.');}finally{if(alive.current&&emailScope.current===opened&&deliveryRequest.current===request)setEmailBusy(false);}};
  const action=(action:Exclude<SalesInvoiceCommand['action'],'invoice.settings_update'>,extra:Record<string,unknown>={})=>{if(!row||!canManage)return;const open=()=>{returnFocusLabel.current=window.document.activeElement?.textContent??'';setCommand({action,invoice_id:row.id,expected_version:row.version,...extra});};if(form&& !['invoice.record_manual_payment','invoice.reverse_manual_payment','invoice.void'].includes(action))exit.request(open);else open();};
  const [pdfBusy,setPdfBusy]=React.useState(false);
  const downloadDocument=async(print=false)=>{
    if(pdfBusy)return;const opened=scope.current;const popup=print?window.open('about:blank','_blank'):null;if(popup)popup.opener=null;
    setPdfBusy(true);setNotice('');
    try{const {data}=await supabase.auth.getSession();if(!data.session||!alive.current||scope.current!==opened){popup?.close();return;}
      const blob=await readInvoicePdf(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/sales-invoice-document?invoice_id=${encodeURIComponent(invoiceId)}&tenant_id=${encodeURIComponent(tenantId)}&format=pdf`,{Authorization:`Bearer ${data.session.access_token}`,apikey:import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY});
      if(!alive.current||scope.current!==opened){popup?.close();return;}
      if(print){if(!popup)throw Error('POPUP_BLOCKED');const url=URL.createObjectURL(blob);popup.location.replace(url);setTimeout(()=>URL.revokeObjectURL(url),60000);}else downloadInvoicePdf(blob,row?.number??'document');
    }catch{popup?.close();if(alive.current&&scope.current===opened)setNotice('PDF could not be opened. Retry, or allow the PDF window to open.');}
    finally{if(alive.current&&scope.current===opened)setPdfBusy(false);}
  };
  if(error)return <p role="alert">Invoice lifecycle could not be read. <button className="btn" onClick={()=>setRefresh(n=>n+1)}>Retry invoice</button></p>;
  if(!row)return <p role="status">Reading invoice status…</p>;
  if(command)return <InvoiceCommandReview key={`${tenantId}:${invoiceId}`} tenantId={tenantId} command={command} onClose={()=>{restoreFormFocus.current=true;setCommand(null);}} onComplete={result=>{setCommand(null);setForm(null);if(typeof result.access_token==='string'){setLink(`${PAIGE_APP_ORIGIN}/invoice?token=${encodeURIComponent(result.access_token)}`);const saved=readInvoiceRecord(result.row,tenantId);if(saved)setRow(saved);}else{setRefresh(n=>n+1);onChanged();}}}/>;
  return <div className="sb-paper sb-invoice-actions" ref={actionWrapper}>
    <p><strong>{invoicePaymentStatus(row.status,row.totalMinor,row.manualRecordedMinor,row.remainingMinor)}</strong></p><dl><dt>Invoice number</dt><dd>{invoiceDisplayNumber(row.number,row.status!=="draft")}</dd><dt>Invoice total</dt><dd>{cash(row.totalMinor)}</dd><dt>Less net recorded payments</dt><dd>− {cash(row.manualRecordedMinor)}</dd><dt>Outstanding balance</dt><dd>{cash(row.remainingMinor)}</dd></dl><p>{cash(row.totalMinor)} − {cash(row.manualRecordedMinor)} = {cash(row.remainingMinor)}. Recorded payments include payment corrections; provider settlement is separate.</p>
    {row.status==='issued'&&<nav className="sb-invoice-action-tabs" aria-label="Invoice workspace views">{(['records','send'] as const).map(tab=><button key={tab} className="btn" aria-pressed={pane===tab} onClick={()=>{const change=()=>{setForm(null);setPane(tab);};if(form)exit.request(change);else change();}}>{tab==='records'?'Payments & records':'Send invoice'}</button>)}</nav>}
    {row.status==='draft'?<button className="btn btn-p" disabled={!canManage} onClick={()=>action('invoice.publish')}>Review and publish invoice</button>:<><button className="btn" disabled={pdfBusy} onClick={()=>void downloadDocument()}>Download PDF</button><button className="btn" disabled={pdfBusy} onClick={()=>void downloadDocument(true)}>Open PDF / print</button></>}
    {row.status==='issued'&&pane==='records'&&<><button className="btn btn-p" disabled={!canManage||row.remainingMinor===0} onClick={()=>setForm('payment')}>Record received payment</button><button className="btn" disabled={!canManage} onClick={()=>action('invoice.link_create',{expires_in_days:30,grant_scope:'share'})}>Create / replace share link</button><button className="btn" disabled={!canManage} onClick={()=>setForm('void')}>Void invoice</button></>}
    {row.status==='issued'&&pane==='send'&&<section><h4>Send invoice</h4><div role="group" aria-label="Invoice delivery channel">{(['email','sms'] as const).map(channel=><button className="btn" key={channel} aria-pressed={deliveryChannel===channel} onClick={()=>{deliveryRequest.current++;setDeliveryChannel(channel);setEmailEligible(false);setEmailBusy(false);setSenderStatus(channel==='sms'?'Check A2P registration, business number and this recipient’s consent.':'Check this business email connection.');}}>{channel==='email'?'Email':'SMS'}</button>)}<button className="btn" disabled aria-describedby="invoice-imessage-unavailable">iMessage · unavailable</button></div><p id="invoice-imessage-unavailable">iMessage requires a supported business messaging adapter; no connection is currently available.</p><p>{senderStatus}</p>{deliveryChannel==='email'&&senders.length>0&&<label>Business email connection<select disabled={emailBusy} value={sender} onChange={e=>{deliveryRequest.current++;setSender(e.target.value);setEmailBusy(false);setEmailEligible(false);}}><option value="">Choose a connected sender</option>{senders.map(s=><option value={s.id} key={s.id}>{s.from_address} · {s.provider}</option>)}</select></label>}<button className="btn" disabled={(deliveryChannel==='email'&&!sender)||emailBusy||!canManage||row.remainingMinor===0} onClick={checkEmail}>{emailBusy?'Checking…':'Check delivery readiness'}</button><button className="btn btn-p" disabled={!emailEligible||!canManage||emailBusy} onClick={()=>action(deliveryChannel==='email'?'invoice.email_send':'invoice.sms_send',{connector_id:deliveryChannel==='email'?sender:null})}>Review invoice delivery</button><p>Uses the frozen invoice recipient and customer link. This check sends nothing. Provider acceptance does not prove delivery or payment.</p></section>}
    {link&&<div><label>Copy this share link now<input readOnly value={link}/></label><p>This link is shown once. If lost, explicitly create a replacement.</p><button className="btn" onClick={()=>{setLink('');onChanged();}}>Done with link</button></div>}
<section hidden={!form} aria-label="Invoice payment editor"><div className="sb-paper">{exit.confirmation}    {form==='payment'&&<form onSubmit={e=>{e.preventDefault();const cents=Math.round(Number(amount)*100);if(!/^\d+(\.\d{1,2})?$/.test(amount)||cents<=0||cents>row.remainingMinor){setNotice('Enter a positive amount within the outstanding balance.');return;}if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(`${date}T12:00:00Z`))||new Date(`${date}T12:00:00Z`).toISOString().slice(0,10)!==date){setNotice('Choose a valid received date.');return;}action('invoice.record_manual_payment',{amount_cents:cents,currency:'usd',method,received_at:new Date(`${date}T12:00:00Z`).toISOString(),reference:reference||null,notes:notes||null});}}><label>Amount received (USD)<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}>{['cash','zelle','wire','check','bank_transfer','other'].map(m=><option key={m} value={m}>{m.replace(/_/g,' ')}</option>)}</select></label><label>Date received<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Reference<input maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Notes<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><p>This records a payment you received. It does not verify collection with a provider.</p><button ref={formReview} className="btn btn-p">Review received payment</button><button className="btn" type="button" onClick={exit.close}>Cancel</button></form>}
    {form==='void'&&<form onSubmit={e=>{e.preventDefault();action('invoice.void',{reason});}}><label>Reason for voiding<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>Recorded receipts remain visible. Voiding does not refund money.</p><button ref={formReview} className="btn">Review void</button><button className="btn" type="button" onClick={exit.close}>Cancel</button></form>}
    {notice&&<p role="alert">{notice}</p>}</div></section>
    {notice&&<p role="alert">{notice}</p>}
    {pane==='records'&&row.payments.length>0&&<><h4>Recorded payment history</h4>{row.payments.map(p=><article key={p.id}><p>{p.kind==='reversal'?'Reversal':'Human-recorded receipt'} · {cash(p.amount_cents)} · {p.method} · {p.received_at.slice(0,10)}</p><p>Recorded by {p.actor_label||'workspace member (name unavailable)'}</p><p>{p.reference} {p.notes} {p.reason}</p>{p.kind==='receipt'&&row.status==='issued'&&<><button className="btn" disabled={!canManage||row.payments.some(r=>r.reverses_payment_id===p.id)} onClick={()=>{setReason('');setCorrectionReceipt(p.id);setForm('correction');}}>Correct payment</button>{form==='correction'&&correctionReceipt===p.id&&<div className="sb-correction-editor"><label>Correction reason<textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>The original receipt remains. This appends a reversal; record a replacement separately if needed.</p><button ref={formReview} className="btn btn-p" disabled={!reason.trim()} onClick={()=>action('invoice.reverse_manual_payment',{payment_id:p.id,reason})}>Review correction / reversal</button><button className="btn" onClick={exit.close}>Cancel correction</button></div>}</>}</article>)}{row.paymentsHasMore&&<p>Showing the latest {row.payments.length} of {row.paymentsCount} payment facts. Older history is retained.</p>}</>}
  </div>;
}
