/** PDF is generated by the scoped server document path, never HTML renamed to .pdf. */
export async function readInvoicePdf(url:string,headers:HeadersInit,signal?:AbortSignal):Promise<Blob>{
  const response=await fetch(url,{headers,signal,cache:'no-store',referrerPolicy:'no-referrer'});
  if(!response.ok||!response.headers.get('content-type')?.startsWith('application/pdf'))throw Error('PDF_UNAVAILABLE');
  const bytes=await response.arrayBuffer();
  if(bytes.byteLength>8_000_000||new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw Error('PDF_INVALID');
  return new Blob([bytes],{type:'application/pdf'});
}
export function downloadInvoicePdf(blob:Blob,number:string){
  const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;
  a.download=`invoice-${/^DRAFT-/i.test(number)?'document':number.replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,100)||'document'}.pdf`;
  a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
