import React from 'react';
import {ArrowLeft,Upload,FileText,Check} from 'lucide-react';
import {supabase} from '@/integrations/supabase/client';
import {useSoloBusiness} from '../data/useSoloBusiness';
import {useSalesDraftExit} from '../sales-dialog';
import {InvoiceCommandReview} from './InvoiceCommandReview';
import {parseSalesInvoiceCommand,type SalesInvoiceCommand} from '../../../supabase/functions/_shared/sales-invoice-command/contract';
import {renderSalesInvoiceDocument} from '../../../supabase/functions/_shared/sales-invoice-document';
import {DEFAULT_INVOICE_APPEARANCE,readInvoicePreferences,invoiceNumberExample,type InvoiceAppearance,type InvoicePreferences} from './invoicePreferences';
import './invoice-appearance.css';
const TEMPLATES=[['classic','Classic','A clean accounting document.'],['modern','Modern','A stronger branded header.'],['service','Service detail','More room for scope and descriptions.']] as const;
export function InvoiceAppearanceWorkspace({tenantId,onClose}:{tenantId:string;onClose():void}){
 const business=useSoloBusiness();
 const [record,setRecord]=React.useState<InvoicePreferences|null>(null),[error,setError]=React.useState(false),[attempt,setAttempt]=React.useState(0);
 React.useEffect(()=>{let alive=true;setRecord(null);setError(false);void supabase.rpc('read_sales_invoice_preferences' as never,{_expected_tenant_id:tenantId} as never).then(({data,error})=>{if(!alive)return;const parsed=!error&&readInvoicePreferences(data,tenantId);if(parsed)setRecord(parsed);else setError(true);},()=>{if(alive)setError(true)});return()=>{alive=false}},[tenantId,attempt]);
 if(!record)return <section className="ia-state"><button className="btn" onClick={onClose}><ArrowLeft size={16}/>Back to invoices</button><p role={error?'alert':'status'}>{error?'Invoice preferences could not be read. Your invoices remain unchanged.':'Reading invoice preferences…'}</p>{error&&<button className="btn" onClick={()=>setAttempt(a=>a+1)}>Retry preferences</button>}</section>;
 return <AppearanceEditor key={`${tenantId}:${record.version}`} tenantId={tenantId} record={record} issuer={business.name||'Your business'} issuerEmail={business.brand.support_email} issuerPhone={business.brand.business_phone} issuerWebsite={business.brand.website} onClose={onClose} onSaved={()=>setAttempt(a=>a+1)}/>;
}
function AppearanceEditor({tenantId,record,issuer,issuerEmail,issuerPhone,issuerWebsite,onClose,onSaved}:{tenantId:string;record:InvoicePreferences;issuer:string;issuerEmail:string|null;issuerPhone:string|null;issuerWebsite:string|null;onClose():void;onSaved():void}){
 const [value,setValue]=React.useState<InvoiceAppearance>(record.settings),[command,setCommand]=React.useState<SalesInvoiceCommand|null>(null),[notice,setNotice]=React.useState(''),[device,setDevice]=React.useState('paper'),[paper,setPaper]=React.useState('letter');
 const exit=useSalesDraftExit(value,!!command,onClose),header=React.useRef<HTMLHeadingElement>(null),uploadEpoch=React.useRef(0);
 React.useEffect(()=>{header.current?.focus();return()=>{uploadEpoch.current++}},[]);
 const requestExit=exit.request;
 React.useEffect(()=>{const intercept=(event:Event)=>{const e=event as CustomEvent<{proceed:()=>void}>;e.preventDefault();requestExit(e.detail.proceed)};window.addEventListener('paige:sales-before-navigation',intercept);return()=>window.removeEventListener('paige:sales-before-navigation',intercept)},[requestExit]);
 const set=<K extends keyof InvoiceAppearance>(key:K,v:InvoiceAppearance[K])=>{if(!record.can_manage||command)return;setValue(old=>({...old,[key]:v}));setNotice('')};
 const loadLogo=async(file:File|undefined)=>{if(!file)return;const epoch=++uploadEpoch.current;if(!['image/png','image/jpeg'].includes(file.type)||file.size>131072){setNotice('Choose a PNG or JPEG logo no larger than 128 KB.');return;}const reader=new FileReader();reader.onload=()=>{if(uploadEpoch.current!==epoch)return;const data=String(reader.result);try{parseSalesInvoiceCommand({action:'invoice.settings_update',expected_version:record.version,settings:{...value,logo_data_uri:data}});set('logo_data_uri',data)}catch{setNotice('This file is not a valid PNG or JPEG logo. Choose another file.')}};reader.onerror=()=>{if(uploadEpoch.current===epoch)setNotice('Logo could not be read. Try selecting the file again.')};reader.readAsDataURL(file)};
 const preview=renderSalesInvoiceDocument({document_input_digest:'0'.repeat(64),remaining_cents:250000,manual_recorded_cents:0,document:{renderer_version:'paige-invoice-html-v2',invoice_number:invoiceNumberExample(value),published_at:'2026-10-04',issuer_name:issuer,client_name:'Example Client',total_cents:250000,currency:'usd',presentation:{...value,issuer_email:issuerEmail,issuer_phone:issuerPhone,issuer_website:issuerWebsite},snapshot:{items:[{item:'Advisory services',description:'Example scope: discovery, delivery and a project handoff. Your actual offer descriptions appear here.',quantity:1,unit_minor:250000}],recipient_email:'client@example.com',billing_address:null,due_now_minor:250000,remainder_minor:0,due_date:'2026-10-18',memo:'Example invoice · preview only',payment_method_intents:['bank_transfer'],kind:'one_time'}}});
 const review=()=>{try{setCommand(parseSalesInvoiceCommand({action:'invoice.settings_update',expected_version:record.version,settings:value}));setNotice('')}catch{setNotice('Check numbering, brand color and logo. The next number must be 1–999999999, with 1–9 digits and a prefix of up to 20 uppercase letters, numbers or hyphens.')}};
 return <section className="ia-workspace"><header className="ia-toolbar"><div><button className="btn" onClick={exit.close}><ArrowLeft size={16}/>Back to invoices</button><h2 ref={header} tabIndex={-1}>Invoice appearance & numbering</h2></div><button className="btn btn-p" disabled={!record.can_manage||!!command||JSON.stringify(value)===JSON.stringify(record.settings)} onClick={review}>Review changes</button></header>
 {!record.can_manage&&<p role="status">Read-only. An owner or admin can change invoice defaults.</p>}
 <div className="ia-layout"><form className="ia-controls" onSubmit={e=>{e.preventDefault();review()}}><fieldset disabled={!record.can_manage||!!command}><legend>Layout</legend><div className="ia-template-options">{TEMPLATES.map(([key,label,description])=><button key={key} type="button" aria-pressed={value.template===key} onClick={()=>set('template',key)}><FileText size={19}/><span><strong>{label}</strong><small>{description}</small></span>{value.template===key&&<Check size={16}/>}</button>)}</div></fieldset><fieldset disabled={!record.can_manage||!!command}><legend>Branding</legend><label className="ia-upload"><Upload size={17}/>Choose your logo<input type="file" accept="image/png,image/jpeg" onChange={e=>{void loadLogo(e.target.files?.[0]);e.target.value=''}}/></label><small>PNG or JPEG · up to 128 KB. Saved with future issued invoices.</small>{value.logo_data_uri&&<div className="ia-logo"><img src={value.logo_data_uri} alt="Invoice logo preview"/><button className="btn" type="button" onClick={()=>{uploadEpoch.current++;set('logo_data_uri',null)}}>Remove logo</button></div>}<label>Brand color<div className="ia-color"><input aria-label="Choose brand color" type="color" value={/^#[a-f0-9]{6}$/i.test(value.accent)?value.accent:DEFAULT_INVOICE_APPEARANCE.accent} onChange={e=>set('accent',e.target.value)}/><input value={value.accent} maxLength={7} onChange={e=>set('accent',e.target.value)} aria-label="Brand color hex"/></div></label></fieldset>
 <fieldset disabled={!record.can_manage||!!command}><legend>Numbering</legend><label>Prefix<input value={value.prefix} maxLength={20} onChange={e=>set('prefix',e.target.value.toUpperCase())} placeholder="INV-"/></label><div className="ia-number-fields"><label>Next number<input type="number" min={1} max={999999999} step={1} value={Number.isNaN(value.next_number)?'':value.next_number} onChange={e=>set('next_number',e.target.value===''?NaN:Number(e.target.value))}/></label><label>Minimum digits<select value={value.padding} onChange={e=>set('padding',Number(e.target.value))}>{[1,2,3,4,5,6,7,8,9].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div><p className="ia-number-preview"><span>Next invoice example</span><strong>{invoiceNumberExample(value)}</strong></p><small>The final number is reserved when you issue an invoice. Already-used numbers are skipped. Existing invoices keep their numbers.</small></fieldset>
 <fieldset disabled={!record.can_manage||!!command}><legend>Customer-facing details</legend><label>Payment instructions<textarea aria-label="Payment instructions" rows={4} value={value.payment_instructions} maxLength={2000} onChange={e=>set('payment_instructions',e.target.value)} placeholder="How should your customer pay? Include the reference they should use."/></label><label>Footer<textarea aria-label="Footer" rows={3} value={value.footer} maxLength={1000} onChange={e=>set('footer',e.target.value)} placeholder="Thank-you note, business registration or other approved details."/></label></fieldset><p className="ia-hint">Changes apply to future invoices. Issued documents keep the appearance and terms saved when they were issued.</p>{notice&&<p role="alert" className="ia-error">{notice}</p>}<div className="ia-bottom"><button className="btn" type="button" onClick={exit.close}>Cancel</button><button className="btn btn-p" disabled={!record.can_manage||!!command||JSON.stringify(value)===JSON.stringify(record.settings)}>Review changes</button></div></form>
 <section className="ia-preview" aria-label="Invoice document preview"><header><span>Example invoice · preview only</span><div><button className="btn" aria-pressed={device==='paper'} onClick={()=>setDevice('paper')}>Print</button><button className="btn" aria-pressed={device==='phone'} onClick={()=>setDevice('phone')}>Phone</button>{device==='paper'&&<label className="ia-paper-size"><span className="campaigns-sr-only">Print page size</span><select value={paper} onChange={e=>setPaper(e.target.value)}><option value="letter">US Letter</option><option value="a4">A4</option></select></label>}</div></header>{preview?<iframe title="Customer invoice preview" sandbox="" referrerPolicy="no-referrer" srcDoc={preview} className={`ia-document ia-${device} ia-${paper}`}/>:<p role="status" className="ia-error">Complete the valid appearance settings to render your preview.</p>}</section></div>{exit.confirmation}{command&&<InvoiceCommandReview tenantId={tenantId} command={command} onClose={()=>setCommand(null)} onComplete={()=>{setCommand(null);onSaved()}}/>}</section>;
}
