import {it,expect,vi} from 'vitest';
import {readInvoiceRecord,listInvoiceRecords} from './invoiceLifecycleApi';
const tenant='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222';
const snapshot={schema_version:2,client_id:'33333333-3333-4333-8333-333333333333',items:[{price_id:null,item:'Service',description:'Original\nUnicode 日本語',unit_minor:1000,quantity:1,price_snapshot:null}],kind:'one_time',deposit_basis_points:null,currency:'usd',cadence:null,recipient_email:'client@example.test',recipient_phone:null,email_source_method_id:null,phone_source_method_id:null,billing_address:null,agreement_id:null,agreement_snapshot:null,processor_intent:null,payment_method_intents:['cash'],delivery_channel_intents:['email'],due_date:'2026-10-10',memo:null,total_minor:1000,due_now_minor:1000,remainder_minor:0};
const row=(patch:Record<string,unknown>={})=>({id,tenant_id:tenant,status:'issued',invoice_number:'INV1',billing_draft_version:1,version:2,amount_total_cents:1000,billing_draft:snapshot,issued_snapshot_version:1,document:{renderer_version:'paige-invoice-html-v1',snapshot},document_input_digest:'a'.repeat(64),manual_recorded_cents:400,remaining_cents:600,payments:[],payments_count:1,payments_has_more:true,...patch});
it('reads immutable issued facts and aggregate balance even when register omits history',()=>{expect(readInvoiceRecord(row(),tenant)).toMatchObject({status:'issued',version:2,remainingMinor:600,manualRecordedMinor:400,payments:[],paymentsCount:1,paymentsHasMore:true,snapshot:{items:[{description:'Original\nUnicode 日本語'}]}});});
it.each([{payments_count:-1},{payments_has_more:false},{remaining_cents:700},{manual_recorded_cents:1001},{issued_snapshot_version:2},{document_input_digest:''},{status:'paid'},{tenant_id:id},{billing_draft:{...snapshot,schema_version:3}}])('fails closed invalid lifecycle projection %j',patch=>expect(readInvoiceRecord(row(patch),tenant)).toBeNull());
it('readable drafts remain editable v2 facts without requiring issued document',()=>expect(readInvoiceRecord(row({status:'draft',version:1,issued_snapshot_version:null,document:null,document_input_digest:null,manual_recorded_cents:0,remaining_cents:1000,payments_count:0,payments_has_more:false}),tenant)).toMatchObject({status:'draft',version:1}));
it('fails entire page for foreign projection and uses canonical page reader',async()=>{const rpc=vi.fn().mockResolvedValue({data:{rows:[row(),row({tenant_id:id})],has_more:false,next_cursor:null},error:null});expect(await listInvoiceRecords(rpc,tenant)).toMatchObject({ok:false});expect(rpc).toHaveBeenCalledWith('list_sales_invoices',{_expected_tenant_id:tenant,_limit:50,_before_id:null});});
