import React,{act,useState} from 'react';import{createRoot,type Root}from'react-dom/client';import{beforeEach,afterEach,it,expect,vi}from'vitest';import{InvoiceDraftEditor,type InvoiceDraftEditorProps}from'./InvoiceDraftEditor';import type{InvoiceSnapshotInput}from'./invoiceDraftSnapshot';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;let host:HTMLDivElement,root:Root;let last:InvoiceSnapshotInput;const changed=vi.fn(),saved=vi.fn(),reviewed=vi.fn();
const initial:InvoiceSnapshotInput={schema_version:2,client_id:'',items:[{price_id:null,item:'Service',unit_minor:10000,quantity:1}],kind:'one_time',deposit_basis_points:null,currency:'usd',cadence:null,recipient_email:null,recipient_phone:null,email_source_method_id:null,phone_source_method_id:null,billing_address:null,agreement_id:null,processor_intent:null,payment_method_intents:[],delivery_channel_intents:['email'],due_date:'2026-10-20',memo:null};
const customers=[{id:'client-a',name:'Test client',methods:[{id:'email-a',kind:'email' as const,value:'primary@example.test',label:'Work',isPrimary:true},{id:'email-b',kind:'email' as const,value:'billing@example.test',label:'Billing',isPrimary:false},{id:'phone-a',kind:'phone' as const,value:'+12025550142',label:'Mobile',isPrimary:true}],address:{line1:'Test street',line2:null,city:'Test city',region:'Test region',postal_code:'00000',country:null}},{id:'client-b',name:'Other test client',methods:[],address:null}];
function Fixture({locked=false,review=false,agreements=[],catalog=[],value=initial}:{value?:InvoiceSnapshotInput;locked?:boolean;review?:boolean;agreements?:InvoiceDraftEditorProps['agreements'];catalog?:InvoiceDraftEditorProps['catalog']}){const[v,setV]=useState(value);last=v;return <InvoiceDraftEditor value={v} onChange={next=>{changed(next);setV(next)}} customers={customers} catalog={catalog} agreements={agreements} processors={[]} busy={false} frozen={locked} canManage={!locked} notice="" review={review} onReview={reviewed} onEdit={()=>{}} onSave={saved} onClose={()=>{}}/>}
beforeEach(()=>{changed.mockClear();saved.mockClear();reviewed.mockClear();host=document.createElement('div');document.body.append(host);root=createRoot(host);act(()=>root.render(<Fixture/>))});afterEach(()=>{act(()=>root.unmount());host.remove()});
function label(name:string){return [...host.querySelectorAll('label')].find(e=>e.textContent?.startsWith(name))!.querySelector('input,select,textarea') as HTMLInputElement}
function set(el:Element,value:string){act(()=>{const proto=el instanceof HTMLSelectElement?HTMLSelectElement.prototype:el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(el,value);el.dispatchEvent(new Event(el instanceof HTMLSelectElement?'change':'input',{bubbles:true}))})}
function click(name:string){act(()=>[...host.querySelectorAll('button')].find(e=>e.textContent?.includes(name))!.click())}
it('atomically prefills primary contacts/address and clears absent client facts',()=>{set(label('Client'),'client-a');expect(last).toMatchObject({recipient_email:'primary@example.test',recipient_phone:'+12025550142',billing_address:{country:null}});set(label('Client'),'client-b');expect(last).toMatchObject({recipient_email:null,recipient_phone:null,billing_address:null,agreement_id:null})});
it('known secondary choice and manual override update provenance without CRM mutation',()=>{set(label('Client'),'client-a');set(host.querySelector('[aria-label="Choose known email"]')!,'email-b');expect(last.email_source_method_id).toBe('email-b');set(label('Billing email'),'manual@example.test');expect(last.email_source_method_id).toBeNull();click('Custom item');expect(last.recipient_email).toBe('manual@example.test')});
it('preserves separate address fields and both delivery intents',()=>{set(label('Client'),'client-a');set(label('Apt / Suite'),'Suite 5');set(label('City'),'Manual city');const sms=label('SMS payment link');act(()=>sms.click());expect(last.delivery_channel_intents).toEqual(['email','sms']);expect(last.billing_address).toMatchObject({line2:'Suite 5',city:'Manual city',country:null})});
it('locks all fields and prevents callbacks under unknown outcome',()=>{act(()=>root.render(<Fixture locked/>));for(const e of host.querySelectorAll('input,select,textarea'))expect(e.matches(':disabled')).toBe(true);click('Save draft');click('Review invoice');expect(saved).not.toHaveBeenCalled();expect(reviewed).not.toHaveBeenCalled();expect(changed).not.toHaveBeenCalled()});
it('refuses invalid financial input before review/save and leaves values recoverable',()=>{set(label('Client'),'client-a');set(host.querySelector('[aria-label="Quantity for item 1"]')!,'0');click('Save draft');expect(saved).not.toHaveBeenCalled();expect(host.textContent).toContain('Check item amounts and quantities');expect(last.items[0].quantity).toBe(0)});
it('shows absent connection and iMessage honestly while delegate save only fires once',()=>{set(label('Client'),'client-a');click('Save draft');expect(saved).toHaveBeenCalledTimes(1);expect(host.textContent).toContain('No verified merchant connection');expect(host.textContent).toContain('iMessage · unavailable')});

it('filters expired voided ineligible and foreign agreements while permitting no agreement',()=>{const choices=[{id:'valid',clientId:'client-a',title:'Current agreement',version:1,status:'completed',eligible:true,expiresAt:null},{id:'expired',clientId:'client-a',title:'Expired agreement',version:1,status:'sent',eligible:true,expiresAt:'2000-01-01T00:00:00Z'},{id:'voided',clientId:'client-a',title:'Voided agreement',version:1,status:'voided',eligible:true,expiresAt:null},{id:'ineligible',clientId:'client-a',title:'Ineligible agreement',version:1,status:'draft',eligible:false,expiresAt:null},{id:'bad-expiry',clientId:'client-a',title:'Invalid expiry',version:1,status:'sent',eligible:true,expiresAt:'bad'},{id:'foreign',clientId:'client-b',title:'Foreign agreement',version:1,status:'sent',eligible:true,expiresAt:null}];act(()=>root.render(<Fixture agreements={choices}/>));set(label('Client'),'client-a');const select=label('Optional client agreement');expect([...select.querySelectorAll('option')].map(e=>e.value)).toEqual(['','valid']);click('Save draft');expect(saved).toHaveBeenCalledOnce()});
it('requires delivery selection for Review while permitting incomplete draft Save',()=>{set(label('Client'),'client-a');const email=label('Email invoice');act(()=>email.click());expect(last.delivery_channel_intents).toEqual([]);click('Review invoice');expect(reviewed).not.toHaveBeenCalled();expect(host.textContent).toContain('Select at least one delivery channel');click('Save draft');expect(saved).toHaveBeenCalledOnce()});

it('records off-platform preferences without granting processor or received-payment authority',()=>{act(()=>label('Zelle').click());act(()=>label('Cash').click());expect(last.payment_method_intents).toEqual(['zelle','cash']);expect(last.processor_intent).toBeNull();expect(host.textContent).toContain('do not record a received payment');act(()=>label('Zelle').click());expect(last.payment_method_intents).toEqual(['cash']);});
it('prefills editable line description only on explicit Catalog selection and preserves user text on refresh',()=>{const offer={priceId:'price-a',productId:'product-a',name:'Offer A',description:'Canonical scope\nSecond line',unitMinor:1000,currency:'usd',billingInterval:'one_time',intervalCount:null,active:true};act(()=>root.render(<Fixture catalog={[offer]}/>));set(label('Add a Catalog offer'),'price-a');click('Add offer');expect(last.items[1]).toMatchObject({item:'Offer A',description:offer.description,price_id:'price-a'});set(host.querySelector('[aria-label="Offer description 2"]')!,'Customer edited scope');act(()=>root.render(<Fixture catalog={[{...offer,description:'Changed canonical scope',unitMinor:1500}]}/>));expect(last.items[1].description).toBe('Customer edited scope');expect(last.items[1].price_id).toBe('price-a');set(label('Client'),'client-a');click('Review invoice');act(()=>root.render(<Fixture review catalog={[offer]}/>));expect(host.textContent).toContain('Customer edited scope');});
it('refuses oversized canonical description without truncating or adding the line',()=>{act(()=>root.render(<Fixture catalog={[{priceId:'price-a',productId:'product-a',name:'Offer A',description:'x'.repeat(10001),unitMinor:1000,currency:'usd',billingInterval:'one_time',intervalCount:null,active:true}]}/>));set(label('Add a Catalog offer'),'price-a');click('Add offer');expect(last.items).toHaveLength(1);expect(host.textContent).toContain('nothing was truncated');});
it('does not render an empty eligible processor selector',()=>{expect([...host.querySelectorAll('label')].some(el=>el.textContent?.startsWith('Eligible processor'))).toBe(false);expect(host.textContent).toContain('No verified merchant connection');expect(label('Zelle')).toBeTruthy();});

it('reopens exact deposit without percentage rounding, edits and reviews the exact minor units',()=>{
 act(()=>root.unmount());root=createRoot(host);act(()=>root.render(<Fixture value={{...initial,schema_version:3,kind:'deposit',deposit_basis_points:null,deposit_minor:50000,client_id:'client-a',recipient_email:'client@example.test',items:[{price_id:null,item:'Service',unit_minor:350000,quantity:1}]}}/>));
 const amount=label('Deposit amount (USD)');expect(amount.value).toBe('500.00');expect(host.textContent).toContain('$500.00');expect(host.textContent).toContain('$3,000.00');expect(host.textContent).not.toContain('Overall deposit percentage');
 set(amount,'450.01');expect(last.deposit_minor).toBe(45001);expect(last.deposit_basis_points).toBeNull();click('Review invoice');expect(reviewed).toHaveBeenCalledOnce();
 set(amount,'3500');click('Save draft');expect(saved).not.toHaveBeenCalled();expect(host.textContent).toContain('must leave a positive balance');
});
it('drops exact-only metadata when switching invoice structure and preserves the legacy percentage path',()=>{
 act(()=>root.unmount());root=createRoot(host);act(()=>root.render(<Fixture value={{...initial,schema_version:3,kind:'deposit',deposit_basis_points:null,deposit_minor:5000}}/>));
 set(host.querySelector('[aria-label="Billing structure"]')!,'one_time');expect(last.schema_version).toBe(2);expect('deposit_minor' in last).toBe(false);expect(last.deposit_basis_points).toBeNull();
 set(host.querySelector('[aria-label="Billing structure"]')!,'deposit');expect(last.deposit_basis_points).toBe(5000);expect(label('Overall deposit percentage')).toBeTruthy();
});
it('requires explicit condition provenance and validates included charges before saving',()=>{set(label('Client'),'client-a');set(host.querySelector('[aria-label="Tax treatment"]')!,'recorded');click('Save draft');expect(saved).not.toHaveBeenCalled();expect(host.textContent).toContain('Tax: enter the recorded source');set(host.querySelector('[aria-label="Tax source"]')!,'Owner reviewed terms');set(host.querySelector('[aria-label="Tax policy"]')!,'Included in service line');set(host.querySelector('[aria-label="Tax included amount 1 (USD)"]')!,'100.01');click('Save draft');expect(saved).not.toHaveBeenCalled();expect(host.textContent).toContain('included amounts');set(host.querySelector('[aria-label="Tax included amount 1 (USD)"]')!,'10.00');click('Save draft');expect(saved).toHaveBeenCalledOnce();expect(last.commercial_conditions?.tax.charges[0].amount_minor).toBe(1000)});
it('keeps absent tax and fees unknown and never implies zero charges',()=>{expect(host.querySelector('[aria-label="Tax treatment"]')).not.toBeNull();expect(host.querySelector('[aria-label="Fees treatment"]')).not.toBeNull();expect(host.textContent).toContain('Unknown means unresolved');});
it('requires revising recorded annotations after invoice lines change rather than silently remapping',()=>{const conditions={schema_version:1 as const,tax:{state:'recorded' as const,source:'Invoice record',policy:'Included',charges:[{line_index:0,amount_minor:100,currency:'usd' as const}]},fees:{state:'unknown' as const,source:null,policy:null,charges:[]}};act(()=>root.unmount());root=createRoot(host);act(()=>root.render(<Fixture value={{...initial,client_id:'client-a',recipient_email:'owner@example.test',commercial_conditions:conditions}}/>));set(host.querySelector('[aria-label="Quantity for item 1"]')!,'2');click('Save draft');expect(saved).not.toHaveBeenCalled();expect(host.textContent).toContain('Invoice lines changed');set(host.querySelector('[aria-label="Tax policy"]')!,'Re-reviewed included tax against two units');click('Save draft');expect(saved).toHaveBeenCalledOnce()});
it('creates a new fixed USD deposit with exact canonical schema3 economics',()=>{set(label('Client'),'client-a');set(host.querySelector('[aria-label="Unit price for item 1"]')!,'3500');set(host.querySelector('[aria-label="Billing structure"]')!,'deposit');set(host.querySelector('[aria-label="Deposit basis"]')!,'fixed');expect(last.schema_version).toBe(3);expect(last.deposit_basis_points).toBeNull();set(host.querySelector('[aria-label="Deposit amount (USD)"]')!,'500');expect(last.deposit_minor).toBe(50000);expect(host.textContent).toContain('$3,000.00');click('Save draft');expect(saved).toHaveBeenCalledOnce();click('Review invoice');expect(reviewed).toHaveBeenCalledOnce();set(host.querySelector('[aria-label="Deposit basis"]')!,'percentage');expect(last.schema_version).toBe(2);expect('deposit_minor' in last).toBe(false);expect(label('Overall deposit percentage')).toBeTruthy()});
