import React,{act,useState} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {InvoiceCommercialConditions,commercialConditionsError,unknownCommercialConditions} from './InvoiceCommercialConditions';
import type {CommercialConditions} from '../../../supabase/functions/_shared/sales-commercial/conditions';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let root:Root,host:HTMLDivElement,last:CommercialConditions|undefined;const changed=vi.fn();
const lines=[{item:'Engagement',unit_minor:350000,quantity:1},{item:'Support',unit_minor:10000,quantity:1}];
function Fixture({value,disabled=false,readOnly=false}:{value?:CommercialConditions;disabled?:boolean;readOnly?:boolean}){const[v,setV]=useState(value);last=v;return <InvoiceCommercialConditions value={v} lines={lines} disabled={disabled} readOnly={readOnly} onChange={next=>{last=next;changed(next);setV(next)}}/>}
beforeEach(()=>{changed.mockClear();host=document.createElement('div');document.body.append(host);root=createRoot(host);act(()=>root.render(<Fixture/>))});afterEach(()=>{act(()=>root.unmount());host.remove()});
const field=(name:string)=>host.querySelector(`[aria-label="${name}"]`)!;
function set(name:string,value:string){act(()=>{const el=field(name);const proto=el instanceof HTMLSelectElement?HTMLSelectElement.prototype:el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(el,value);el.dispatchEvent(new Event(el instanceof HTMLSelectElement?'change':'input',{bubbles:true}))})}
function click(text:string){act(()=>[...host.querySelectorAll('button')].find(e=>e.textContent===text)!.click())}
it('does not fabricate conditions on initial render',()=>{expect(changed).not.toHaveBeenCalled();expect((field('Tax treatment') as HTMLSelectElement).value).toBe('unknown');expect((field('Fees treatment') as HTMLSelectElement).value).toBe('unknown');expect(commercialConditionsError(undefined,lines)).toBe('')});
it('records tax and fees independently with required provenance',()=>{set('Tax treatment','not_applicable');expect(last?.fees.state).toBe('unknown');expect(commercialConditionsError(last,lines)).toContain('source');set('Tax source','Owner reviewed contract');set('Tax policy','No tax applies');expect(commercialConditionsError(last,lines)).toBe('');set('Fees treatment','not_applicable');expect(commercialConditionsError(last,lines)).toContain('Fees');expect(last?.tax.policy).toBe('No tax applies')});
it('clears annotations only through an explicit unknown selection',()=>{set('Tax treatment','recorded');set('Tax source','Invoice');set('Tax policy','Included');set('Tax included amount 1 (USD)','5.00');set('Tax treatment','unknown');expect(last?.tax).toEqual({state:'unknown',source:null,policy:null,charges:[]})});
it('keeps invalid precision visible and reports correction without rounding',()=>{set('Tax treatment','recorded');set('Tax source','Invoice');set('Tax policy','Included');set('Tax included amount 1 (USD)','1.005');expect((field('Tax included amount 1 (USD)') as HTMLInputElement).value).toBe('1.005');expect(commercialConditionsError(last,lines)).toContain('two decimal');set('Tax included amount 1 (USD)','1.01');expect(last?.tax.charges[0].amount_minor).toBe(101);expect(commercialConditionsError(last,lines)).toBe('')});
it('uses the shared validator to refuse duplicate lines and combined over-allocation',()=>{const c=unknownCommercialConditions();c.tax={state:'recorded',source:'Invoice',policy:'Included',charges:[{line_index:0,amount_minor:350000,currency:'usd'}]};c.fees={state:'recorded',source:'Invoice',policy:'Included',charges:[{line_index:0,amount_minor:1,currency:'usd'}]};expect(commercialConditionsError(c,lines)).toContain('combined');c.fees=unknownCommercialConditions().fees;c.tax.charges.push({line_index:0,amount_minor:1,currency:'usd'});expect(commercialConditionsError(c,lines)).toContain('choose existing')});
it('preserves missing-line references instead of automatically mapping to a different line',()=>{const c=unknownCommercialConditions();c.tax={state:'recorded',source:'Invoice',policy:'Included',charges:[{line_index:4,amount_minor:1,currency:'usd'}]};act(()=>root.render(<Fixture value={c}/>));act(()=>root.unmount());root=createRoot(host);act(()=>root.render(<Fixture value={c}/>));expect(host.textContent).toContain('Unavailable line');expect(last?.tax.charges[0].line_index).toBe(4)});
it('supports adding and removing explicit included charge rows',()=>{set('Tax treatment','recorded');click('Add tax charge');expect(last?.tax.charges).toHaveLength(2);set('Tax invoice line 2','1');expect(last?.tax.charges[1].line_index).toBe(1);act(()=>(field('Remove tax charge 1') as HTMLButtonElement).click());expect(last?.tax.charges).toHaveLength(1);expect(last?.tax.charges[0].line_index).toBe(1)});
it('locks every editable control and callback when busy, frozen or unauthorized',()=>{act(()=>root.render(<Fixture disabled/>));for(const el of host.querySelectorAll('input,select,textarea,button'))expect(el.matches(':disabled')).toBe(true);set('Tax treatment','recorded');expect(changed).not.toHaveBeenCalled()});
it('renders persisted values in review without edit controls or collected-payment claims',()=>{const c=unknownCommercialConditions();c.fees={state:'recorded',source:'Owner record',policy:'Included support fee',charges:[{line_index:1,amount_minor:300,currency:'usd'}]};act(()=>root.unmount());root=createRoot(host);act(()=>root.render(<Fixture value={c} readOnly/>));expect(host.querySelector('input,select,textarea,button')).toBeNull();expect(host.textContent).toContain('$3.00');expect(host.textContent).toContain('Owner record');expect(host.textContent).toContain('Unknown');expect(host.textContent).not.toContain('Payment received')});
