import {describe,it,expect} from 'vitest';
import {renderSalesInvoiceDocument} from '../../../supabase/functions/_shared/sales-invoice-document';
describe('frozen invoice artifact',()=>{
  const input={document:{renderer_version:'paige-invoice-html-v1',invoice_number:'INV1',currency:'usd',issuer_name:'Business',client_name:'Client',total_cents:1000,snapshot:{items:[{item:'Service',description:'日本語\n<script>alert(1)</script>',quantity:1,unit_minor:1000}],due_now_minor:250,remainder_minor:750,due_date:'2026-10-10',payment_method_intents:['cash'],memo:'<img src=x onerror=alert(1)>'}},document_input_digest:'a'.repeat(64),manual_recorded_cents:400,remaining_cents:600};
  it('escapes all content and preserves Unicode/multiline, without executable resources',()=>{const html=renderSalesInvoiceDocument(input)!;expect(html).toContain('日本語\n&lt;script&gt;');expect(html).not.toContain('<script');expect(html).not.toContain('<img');expect(html).toContain('Original requested amount: $2.50 USD');expect(html).toContain('Current outstanding: $6.00 USD');expect(html).not.toContain('Due now');expect(html).toContain('not provider verification');});
  const ledger={rows:[{id:'a',kind:'receipt',amount_cents:500,currency:'usd',method:'cash',received_at:'2026-09-01',posted_at:'2026-10-01',provenance:'human_recorded'},{id:'b',kind:'reversal',amount_cents:100,currency:'usd',method:'cash',received_at:'2026-09-02',posted_at:'2026-10-02',provenance:'human_recorded',reverses_payment_id:'a'}],receipt_total_cents:500,reversal_total_cents:100,count:2,as_of:'2026-10-02T12:00:00Z',complete:true};
  it('shows dated receipts and corrections with reconciled formula and no internals',()=>{const html=renderSalesInvoiceDocument({...input,current_invoice_number:'INV-0042',payment_ledger:ledger})!;expect(html).toContain('Invoice INV-0042');expect(html).not.toContain('Original reference: INV1');expect(html).toContain('Partially paid (business-recorded)');expect(html).toContain('2026-09-01');expect(html).toContain('Posted 2026-10-01');expect(html).toContain('Payment correction / reversal');expect(html).toContain('− recorded receipts $5.00 USD + reversals $1.00 USD = outstanding $6.00 USD');expect(html).not.toContain('Document-input digest');expect(html).not.toContain('Renderer:');});
  it('labels incomplete history without a complete calculation claim',()=>{const html=renderSalesInvoiceDocument({...input,payment_ledger:{...ledger,rows:ledger.rows.slice(0,1),complete:false}})!;expect(html).toContain('Partial history: showing 1 of 2');expect(html).not.toContain('− recorded receipts');});
  it('refuses contradictory ledger and unsafe amount totals',()=>{expect(renderSalesInvoiceDocument({...input,payment_ledger:{...ledger,receipt_total_cents:600}})).toBeNull();expect(renderSalesInvoiceDocument({...input,payment_ledger:{...ledger,rows:[{...ledger.rows[0],amount_cents:Number.MAX_SAFE_INTEGER+1}]}})).toBeNull();expect(renderSalesInvoiceDocument({...input,payment_ledger:{...ledger,rows:ledger.rows.slice(0,1)}})).toBeNull();});
  it('never derives draft state from a historical number and labels fully paid business records',()=>{const html=renderSalesInvoiceDocument({...input,document:{...input.document,invoice_number:'DRAFT-legacy'},manual_recorded_cents:1000,remaining_cents:0})!;expect(html).toContain('Previously issued invoice');expect(html).not.toContain('DRAFT-legacy');expect(html).toContain('Paid (business-recorded)');});
  it('accepts canonical SQL receipt projection with posted ordinal and running balances',()=>{const payment_ledger={...ledger,rows:[{...ledger.rows[0],kind:'receipt',ordinal:1,running_received_cents:500,running_remaining_cents:500},{...ledger.rows[1],ordinal:2,running_received_cents:400,running_remaining_cents:600}]};const html=renderSalesInvoiceDocument({...input,current_invoice_number:'INV-0042',status:'partially_paid',payment_ledger});expect(html).not.toBeNull();expect(html).toContain('Payment recorded');expect(html).toContain('Payment correction / reversal');expect(html).toContain('Outstanding');expect(renderSalesInvoiceDocument({...input,payment_ledger:{...payment_ledger,rows:[{...payment_ledger.rows[0],kind:'payment'},payment_ledger.rows[1]]}})).toBeNull();});
  it('renders the same current reference and dated ledger for v2 without changing frozen branding',()=>{const html=renderSalesInvoiceDocument({...input,current_invoice_number:'INV-0042',payment_ledger:ledger,document:{...input.document,renderer_version:'paige-invoice-html-v2',currency:'usd',presentation:{template:'modern',accent:'#475569',footer:'Thank you',payment_instructions:'Cash by agreement'},published_at:'2026-09-01'}})!;expect(html).toContain('INV-0042');expect(html).not.toContain('Original reference: INV1');expect(html).toContain('Payment correction / reversal');expect(html).toContain('Thank you');expect(html).toContain('Partially paid (business-recorded)');});
  it('itemizes provider-confirmed and manual allocations without mixing evidence',()=>{const html=renderSalesInvoiceDocument({...input,manual_recorded_cents:100,provider_verified_cents:300,allocated_cents:400,payment_ledger:{...ledger,receipt_total_cents:400,reversal_total_cents:0,rows:[{...ledger.rows[0],amount_cents:100},{...ledger.rows[0],id:'p',amount_cents:300,method:'stripe',provenance:'provider_verified',provider:'stripe',provider_verified_at:'2026-10-05T12:00:00Z'}]}})!;expect(html).not.toBeNull();expect(html).toContain('Provider-confirmed payments: $3.00 USD');expect(html).toContain('Manually recorded payments: $1.00 USD');expect(html).toContain('Payment confirmed');expect(html).not.toContain('provider settlement is not verified');});
  it('refuses evidence-class totals that disagree with the complete ledger',()=>expect(renderSalesInvoiceDocument({...input,manual_recorded_cents:100,provider_verified_cents:300,allocated_cents:400,payment_ledger:{...ledger,receipt_total_cents:400,reversal_total_cents:0,count:1,rows:[{...ledger.rows[0],amount_cents:400}]}})).toBeNull());
  it('refuses a provider label without the canonical verification evidence',()=>expect(renderSalesInvoiceDocument({...input,manual_recorded_cents:0,provider_verified_cents:400,allocated_cents:400,payment_ledger:{...ledger,receipt_total_cents:400,reversal_total_cents:0,count:1,rows:[{...ledger.rows[0],amount_cents:400,provenance:'provider_verified'}]}})).toBeNull());
  it('escapes payment method content',()=>{const html=renderSalesInvoiceDocument({...input,payment_ledger:{...ledger,rows:[{...ledger.rows[0],method:'<script>x</script>'},ledger.rows[1]]}})!;expect(html).toContain('&lt;script&gt;x&lt;/script&gt;');expect(html).not.toContain('<script>');});
  it('refuses unknown renderer and missing digest',()=>{expect(renderSalesInvoiceDocument({...input,document_input_digest:''})).toBeNull();expect(renderSalesInvoiceDocument({...input,document:{...input.document,renderer_version:'unknown'}})).toBeNull();});
});
