import React from 'react';
import {supabase} from '@/integrations/supabase/client';
import {parseMinorAmount} from './billingAmounts';
import {customerPaymentRequestCopy,formatPaymentMinor} from './customerPaymentRequest';
import {UUID,type SalesInvoiceCommand} from '../../../supabase/functions/_shared/sales-invoice-command/contract';
type Operation={id:string;provider:'stripe'|'paypal';purpose:'full'|'partial'|'deposit'|'installment';invoice_version:number;amount_minor:number;currency:string;state:string;reconciliation_status?:string|null;reconciliation_reason?:string|null};
const states=['prepared','dispatching','provider_accepted','customer_action_required','outcome_unknown','settled','failed','expired','cancelled'];
function readRows(value:unknown):Operation[]|null{
 if(!value||typeof value!=='object'||!Array.isArray((value as {rows?:unknown}).rows))return null;
 const rows=(value as {rows:unknown[]}).rows;if(rows.length>25)return null;
 if(rows.some(v=>{if(!v||typeof v!=='object')return true;const r=v as Record<string,unknown>;return typeof r.id!=='string'||!UUID.test(r.id)||!['stripe','paypal'].includes(String(r.provider))||!['full','partial','deposit','installment'].includes(String(r.purpose))||!Number.isSafeInteger(r.invoice_version)||Number(r.invoice_version)<1||!Number.isSafeInteger(r.amount_minor)||Number(r.amount_minor)<1||typeof r.currency!=='string'||!/^[a-z]{3}$/.test(r.currency)||!states.includes(String(r.state));}))return null;
 return rows as Operation[];
}
export function InvoicePaymentRequests({tenantId,invoiceId,version,remaining,canManage,onReview,onActivity,onDraftChange}:{tenantId:string;invoiceId:string;version:number;remaining:number;canManage:boolean;onReview(command:SalesInvoiceCommand,operationId?:string):void;onActivity?(active:boolean):void;onDraftChange?(draft:{partial:boolean;amount:string}|null):void}){
 const [rows,setRows]=React.useState<Operation[]|null>(null),[error,setError]=React.useState(false),[refresh,setRefresh]=React.useState(0),[editing,setEditing]=React.useState(false),[amount,setAmount]=React.useState(''),[partial,setPartial]=React.useState(false),[notice,setNotice]=React.useState('');
 React.useEffect(()=>{let alive=true;setRows(null);setError(false);void Promise.resolve(supabase.rpc('list_sales_invoice_payment_operations' as never,{_expected_tenant_id:tenantId,_invoice_id:invoiceId} as never)).then(({data,error})=>{if(!alive)return;const parsed=error?null:readRows(data);setRows(parsed);setError(!parsed);}).catch(()=>{if(alive){setRows(null);setError(true);}});return()=>{alive=false;};},[tenantId,invoiceId,version,refresh]);
 React.useEffect(()=>{onDraftChange?.(editing?{partial,amount}:null);},[editing,partial,amount,onDraftChange]);
 const active=rows?.some(r=>!['settled','failed','expired','cancelled'].includes(r.state))??true;
 React.useEffect(()=>{onActivity?.(active);},[active,onActivity]);
 return <section aria-label="Customer payment requests"><h4>Customer payment requests</h4><p>Request a secure hosted payment. This does not record money received.</p>{error?<p role="alert">Payment requests could not be read. <button className="btn" onClick={()=>setRefresh(n=>n+1)}>Retry payment status</button></p>:!rows?<p role="status">Reading payment requests…</p>:<>{rows.map(r=><article key={r.id}><p>{customerPaymentRequestCopy(r.state)} · {formatPaymentMinor(r.amount_minor,r.currency)}</p>{r.reconciliation_reason==='reconciliation_exhausted'&&<p role="alert">Automatic payment checks need attention. Check this existing request; do not create another request while its outcome is unknown.</p>}{!['settled','failed','expired','cancelled'].includes(r.state)&&<button className="btn" disabled={!canManage} onClick={()=>onReview({action:'invoice.payment_request',invoice_id:invoiceId,expected_version:r.invoice_version,provider:r.provider,purpose:r.purpose,...(r.purpose==='full'?{}:{amount_minor:r.amount_minor})},r.id)}>Check existing request</button>}</article>)}{active&&<p>An existing request must be checked before another payment request can begin.</p>}<button className="btn" disabled={!canManage||remaining<=0||active} onClick={()=>setEditing(true)}>Request customer payment</button></>}{editing&&<form onSubmit={e=>{e.preventDefault();try{const minor=partial?parseMinorAmount(amount,2):remaining;if(minor<=0||minor>remaining)throw Error();onReview({action:'invoice.payment_request',invoice_id:invoiceId,expected_version:version,provider:'stripe',purpose:partial?'partial':'full',...(partial?{amount_minor:minor}:{})});setNotice('');}catch{setNotice('Enter a positive amount within the outstanding balance.');}}}><label><input type="checkbox" checked={partial} onChange={e=>setPartial(e.target.checked)}/>Request a partial payment</label>{partial&&<label>Amount requested (USD)<input inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)}/></label>}<p>Stripe readiness and the exact amount are verified by the server before review. PayPal execution is not available yet.</p><button className="btn btn-p">Prepare payment review</button><button className="btn" type="button" onClick={()=>setEditing(false)}>Cancel</button>{notice&&<p role="alert">{notice}</p>}</form>}</section>;
}
