import React,{act,useState} from 'react';import{createRoot,type Root}from'react-dom/client';import{beforeEach,afterEach,it,expect,vi}from'vitest';import{InvoiceDraftEditor,type InvoiceDraftEditorProps}from'./InvoiceDraftEditor';import type{InvoiceSnapshotInput}from'./invoiceDraftSnapshot';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;let host:HTMLDivElement,root:Root;let last:InvoiceSnapshotInput;const changed=vi.fn(),saved=vi.fn(),reviewed=vi.fn();
const initial:InvoiceSnapshotInput={schema_version:2,client_id:'',items:[{price_id:null,item:'Service',unit_minor:10000,quantity:1}],kind:'one_time',deposit_basis_points:null,currency:'usd',cadence:null,recipient_email:null,recipient_phone:null,email_source_method_id:null,phone_source_method_id:null,billing_address:null,agreement_id:null,processor_intent:null,payment_method_intents:[],delivery_channel_intents:['email'],due_date:'2026-10-20',memo:null};
const customers=[{id:'client-a',name:'Test client',methods:[{id:'email-a',kind:'email' as const,value:'primary@example.test',label:'Work',isPrimary:true},{id:'email-b',kind:'email' as const,value:'billing@example.test',label:'Billing',isPrimary:false},{id:'phone-a',kind:'phone' as const,value:'+12025550142',label:'Mobile',isPrimary:true}],address:{line1:'Test street',line2:null,city:'Test city',region:'Test region',postal_code:'00000',country:null}},{id:'client-b',name:'Other test client',methods:[],address:null}];
function Fixture({locked=false,review=false,agreements=[]}:{locked?:boolean;review?:boolean;agreements?:InvoiceDraftEditorProps['agreements']}){const[v,setV]=useState(initial);last=v;return <InvoiceDraftEditor value={v} onChange={next=>{changed(next);setV(next)}} customers={customers} catalog={[]} agreements={agreements} processors={[]} busy={false} frozen={locked} canManage={!locked} notice="" review={review} onReview={reviewed} onEdit={()=>{}} onSave={saved} onClose={()=>{}}/>}
beforeEach(()=>{changed.mockClear();saved.mockClear();reviewed.mockClear();host=document.createElement('div');document.body.append(host);root=createRoot(host);act(()=>root.render(<Fixture/>))});afterEach(()=>{act(()=>root.unmount());host.remove()});
function label(name:string){return [...host.querySelectorAll('label')].find(e=>e.textContent?.startsWith(name))!.querySelector('input,select,textarea') as HTMLInputElement}
function set(el:Element,value:string){act(()=>{const proto=el instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(el,value);el.dispatchEvent(new Event(el instanceof HTMLSelectElement?'change':'input',{bubbles:true}))})}
function click(name:string){act(()=>[...host.querySelectorAll('button')].find(e=>e.textContent?.includes(name))!.click())}
it('atomically prefills primary contacts/address and clears absent client facts',()=>{set(label('Client'),'client-a');expect(last).toMatchObject({recipient_email:'primary@example.test',recipient_phone:'+12025550142',billing_address:{country:null}});set(label('Client'),'client-b');expect(last).toMatchObject({recipient_email:null,recipient_phone:null,billing_address:null,agreement_id:null})});
it('known secondary choice and manual override update provenance without CRM mutation',()=>{set(label('Client'),'client-a');set(host.querySelector('[aria-label="Choose known email"]')!,'email-b');expect(last.email_source_method_id).toBe('email-b');set(label('Billing email'),'manual@example.test');expect(last.email_source_method_id).toBeNull();click('Custom item');expect(last.recipient_email).toBe('manual@example.test')});
it('preserves separate address fields and both delivery intents',()=>{set(label('Client'),'client-a');set(label('Apt / Suite'),'Suite 5');set(label('City'),'Manual city');const sms=[...host.querySelectorAll<HTMLInputElement>('input[type=checkbox]')][1];act(()=>sms.click());expect(last.delivery_channel_intents).toEqual(['email','sms']);expect(last.billing_address).toMatchObject({line2:'Suite 5',city:'Manual city',country:null})});
it('locks all fields and prevents callbacks under unknown outcome',()=>{act(()=>root.render(<Fixture locked/>));for(const e of host.querySelectorAll('input,select,textarea'))expect(e.matches(':disabled')).toBe(true);click('Save draft');click('Review invoice');expect(saved).not.toHaveBeenCalled();expect(reviewed).not.toHaveBeenCalled();expect(changed).not.toHaveBeenCalled()});
it('refuses invalid financial input before review/save and leaves values recoverable',()=>{set(label('Client'),'client-a');set(host.querySelector('[aria-label="Quantity for item 1"]')!,'0');click('Save draft');expect(saved).not.toHaveBeenCalled();expect(host.textContent).toContain('Check item amounts and quantities');expect(last.items[0].quantity).toBe(0)});
it('shows absent connection and iMessage honestly while delegate save only fires once',()=>{set(label('Client'),'client-a');click('Save draft');expect(saved).toHaveBeenCalledTimes(1);expect(host.textContent).toContain('No verified merchant connection');expect(host.textContent).toContain('iMessage · unavailable')});

it('filters expired voided ineligible and foreign agreements while permitting no agreement',()=>{const choices=[{id:'valid',clientId:'client-a',title:'Current agreement',version:1,status:'completed',eligible:true,expiresAt:null},{id:'expired',clientId:'client-a',title:'Expired agreement',version:1,status:'sent',eligible:true,expiresAt:'2000-01-01T00:00:00Z'},{id:'voided',clientId:'client-a',title:'Voided agreement',version:1,status:'voided',eligible:true,expiresAt:null},{id:'ineligible',clientId:'client-a',title:'Ineligible agreement',version:1,status:'draft',eligible:false,expiresAt:null},{id:'bad-expiry',clientId:'client-a',title:'Invalid expiry',version:1,status:'sent',eligible:true,expiresAt:'bad'},{id:'foreign',clientId:'client-b',title:'Foreign agreement',version:1,status:'sent',eligible:true,expiresAt:null}];act(()=>root.render(<Fixture agreements={choices}/>));set(label('Client'),'client-a');const select=label('Optional client agreement');expect([...select.querySelectorAll('option')].map(e=>e.value)).toEqual(['','valid']);click('Save draft');expect(saved).toHaveBeenCalledOnce()});
it('requires delivery selection for Review while permitting incomplete draft Save',()=>{set(label('Client'),'client-a');const email=host.querySelector('.ide-choices input[type=checkbox]') as HTMLInputElement;act(()=>email.click());expect(last.delivery_channel_intents).toEqual([]);click('Review invoice');expect(reviewed).not.toHaveBeenCalled();expect(host.textContent).toContain('Select at least one delivery channel');click('Save draft');expect(saved).toHaveBeenCalledOnce()});
