import React, {act} from 'react';
import {createRoot} from 'react-dom/client';
import {describe,it,expect,vi} from 'vitest';
const h=vi.hoisted(()=>({tenant:'tenant-a',resolving:false,from:vi.fn()}));
vi.mock('@/hooks/useTenantContext',()=>({useTenantContext:()=>({activeTenantId:h.tenant,accountContextLoading:h.resolving})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:h.from}}));
import {billingClientSearchFilter,invoiceCustomerFromRow,invoiceAgreementFromRow,useInvoiceBillingSources} from './useInvoiceBillingSources';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
describe('canonical invoice-only billing sources',()=>{
 it('retains primary and secondary kinds, structured postal and unknown country/unit',()=>{const r=invoiceCustomerFromRow({id:'a',first_name:'Afonso',last_name:'Macaia',street_address:' 10 Main St ',city:' City ',state:' Region ',zip_code:' 123 ',email:'unsafe@example.test',client_contact_methods:[{id:'e2',kind:'email',value:'secondary@example.test',label:'Other',is_primary:false,position:2},{id:'p',kind:'phone',value:'+15555550123',label:'Mobile',is_primary:true,position:0},{id:'e1',kind:'email',value:' primary@example.test ',label:'Billing',is_primary:true,position:1}]});expect(r.name).toBe('Afonso Macaia');expect(r.methods.map(m=>m.id)).toEqual(['e1','e2','p']);expect(r.address).toEqual({line1:'10 Main St',line2:null,city:'City',region:'Region',postal_code:'123',country:null});});
 it('does not pretend legacy email is a canonical primary or infer absent postal values',()=>{expect(invoiceCustomerFromRow({id:'a',email:'legacy@example.test'})).toMatchObject({methods:[],address:null});});
 it.each([{status:'voided',expires_at:null},{status:'completed',expires_at:'2000-01-01'},{status:'draft',expires_at:'not-a-date'}])('rejects invalid/expired agreement choice %j',r=>{expect(invoiceAgreementFromRow({id:'agreement',contact_id:'a',title:'Agreement',version:1,...r}).eligible).toBe(false);});
 it('filters every source by tenant and discards late A results on A-B-A epochs',async()=>{let resolve!: (v:unknown)=>void;const calls:{table:string;filters:unknown[]}[]=[];h.tenant='tenant-a';h.from.mockImplementation((table:string)=>{const call={table,filters:[] as unknown[]};calls.push(call);const result=table==='clients'&&calls.length===1?new Promise(r=>resolve=r):Promise.resolve({data:[],error:null});const q={select:()=>q,eq:(...args:unknown[])=>{call.filters.push(args);return q},order:()=>q,limit:()=>result,range:()=>result,or:()=>q};return q;});let latest:ReturnType<typeof useInvoiceBillingSources>;function Probe(){latest=useInvoiceBillingSources();return null;}const host=document.createElement('div'),root=createRoot(host);await act(async()=>root.render(<Probe/>));h.tenant='tenant-b';await act(async()=>root.render(<Probe/>));h.tenant='tenant-a';await act(async()=>root.render(<Probe/>));await act(async()=>resolve({data:[{id:'stale',first_name:'Stale'}],error:null}));expect(latest!.customers).toEqual([]);expect(calls.every(c=>c.filters.some(f=>(f as string[])[0]==='tenant_id'))).toBe(true);await act(async()=>root.unmount());});
});

it('resolves selected older customer and agreement outside bounded pages while retaining tenant/client predicates',async()=>{
 const calls:{table:string;filters:[string,string][];range?:number[]}[]=[];h.tenant='tenant-a';
 h.from.mockImplementation((table:string)=>{const call={table,filters:[] as [string,string][],range:undefined as number[]|undefined};calls.push(call);const respond=()=>{const id=call.filters.find(([column])=>column==='id')?.[1];return Promise.resolve({error:null,data:table==='clients'?(id?[{id,tenant_id:'tenant-a',first_name:'Older',client_contact_methods:[{id:'method-older',kind:'email',value:'older@example.test',is_primary:true,position:0,label:'Billing'}]}]:Array.from({length:51},(_,n)=>({id:'recent-'+n,tenant_id:'tenant-a',first_name:'Recent'}))):id?[{id,tenant_id:'tenant-a',contact_id:'older-client',title:'Older agreement',version:1,status:'completed',expires_at:null}]:[]});};const q={select:()=>q,eq:(column:string,value:string)=>{call.filters.push([column,value]);return q},order:()=>q,or:()=>q,range:(from:number,to:number)=>{call.range=[from,to];return respond()},limit:()=>respond()};return q;});
 let latest:ReturnType<typeof useInvoiceBillingSources>;function Probe(){latest=useInvoiceBillingSources({clientId:'older-client',agreementId:'older-agreement',customerPage:2});return null;}const root=createRoot(document.createElement('div'));await act(async()=>root.render(<Probe/>));expect(latest!.customers).toHaveLength(51);expect(latest!.customersHasMore).toBe(true);expect(latest!.customers.find(c=>c.id==='older-client')?.methods[0].value).toBe('older@example.test');expect(latest!.agreements[0].id).toBe('older-agreement');expect(calls.find(c=>c.table==='clients'&&c.range)?.range).toEqual([100,150]);expect(calls.filter(c=>c.table==='paige_agreements').every(c=>c.filters.some(([column,value])=>column==='contact_id'&&value==='older-client'))).toBe(true);await act(async()=>root.unmount());
});
it('fails the whole source read if exact selected lookup returns a foreign tenant/client',async()=>{
 h.tenant='tenant-a';h.from.mockImplementation((table:string)=>{const filters:string[]=[];const result=()=>Promise.resolve({error:null,data:filters.includes('id')?[{id:'older-client',tenant_id:'tenant-b',first_name:'Foreign'}]:[]});const q={select:()=>q,eq:(column:string)=>{filters.push(column);return q},order:()=>q,or:()=>q,range:result,limit:result};return q;});let latest:ReturnType<typeof useInvoiceBillingSources>;function Probe(){latest=useInvoiceBillingSources({clientId:'older-client'});return null;}const root=createRoot(document.createElement('div'));await act(async()=>root.render(<Probe/>));expect(latest!.phase).toBe('error');expect(latest!.customers).toEqual([]);await act(async()=>root.unmount());
});

it('searches full-name tokens as quoted literal regex values without untrusted filter operators',()=>{expect(billingClientSearchFilter('Afonso Macaia')).toContain('first_name.imatch."Afonso"');expect(billingClientSearchFilter('Afonso Macaia')).toContain('last_name.imatch."Macaia"');expect(billingClientSearchFilter('A.*')).toContain(JSON.stringify('A'+String.fromCharCode(92)+'.'+String.fromCharCode(92)+'*'));expect(billingClientSearchFilter('a",tenant_id.eq.foreign')).toContain(JSON.stringify('a",tenant_id'+String.fromCharCode(92)+'.eq'+String.fromCharCode(92)+'.foreign'));});
