/** Synthetic render fixtures only; this harness is excluded from the production build. */
export function analyticsFixture(args: Record<string, unknown>) {
  const key = String(args.p_metric_key);
  const asOf = new Date().toISOString();
  const unavailable = ["business.retention", "business.profitability", "business.nps", "team.performance_scorecards", "ai.voice_consumption"].includes(key);
  const diagnostic = key === "operations.recorded_workflow_activity" || key === "operations.current_system_exceptions";
  const partial = key.startsWith("ai.") && !unavailable || key === "business.onboarding_current" || diagnostic;
  const series = key.endsWith("_daily");
  const distribution = key.includes("lifecycle") || key.includes("onboarding") || key.includes("distribution") || key.includes("systems_check") || key.includes("recorded_workflow_runs");
  const samples = key.startsWith("team.") ? ["owner", "admin", "member"] : key.includes("workflow_runs") ? ["succeeded", "failed", "running"] : key.includes("systems_check") ? ["pass", "fail", "skip"] : key.includes("onboarding") ? ["pre_invite", "agreement_signed", "portal_active"] : ["client_active", "client_paused", "client_churned"];
  const points = Array.from({ length: 7 }, (_, i) => ({ at: new Date(Date.parse(String(args.p_range_start)) + i * 86400000).toISOString(), value: [8, 12, 16, 10, 25, 18, 13][i] }));
  const events = [{ source: key.endsWith("workflow_activity") ? "workflow_run" : "systems_check", at: new Date(Date.parse(String(args.p_range_end)) - 3600000).toISOString(), status: key.endsWith("workflow_activity") ? "failed" : "fail", severity: key.endsWith("workflow_activity") ? null : "blocking", retry_count: key.endsWith("workflow_activity") ? 2 : null, completed_at: null, check_key: key.endsWith("workflow_activity") ? null : "payment_processor_connected" }];
  const values = unavailable ? null : diagnostic ? { kind: "diagnostic_events", items: events } : series ? { kind: "series", points } : distribution ? { kind: "distribution", items: samples.map((label, i) => ({ key: label, label, count: [18, 3, 2][i] })) } : key.includes("cost") || key.includes("latency") ? { kind: "decimal", value: key.includes("cost") ? "12.73" : "873.5" } : { kind: "count", count: 23 };
  return { metric_key: key, metric_version: "1.0.0", owner_department: "operations_pmo", label: key.split(".")[1].replaceAll("_", " "), definition: "Synthetic harness measurement; not production data.", formula: "Synthetic fixture projection", range: { key: args.p_range_key, start: args.p_range_start, end: args.p_range_end, bounds: "[start,end)", timezone: "UTC", semantics: series || key.endsWith("workflow_activity") || key.startsWith("ai.") ? "event_timestamp_cohort" : "current_snapshot" }, dimensions: {}, values, unit: key.includes("cost") ? "estimated_usd" : key.includes("latency") ? "milliseconds" : "count", source_refs: unavailable ? [] : ["public.synthetic_harness"], as_of: asOf, freshness: { queried_at: asOf, source_updated_through: unavailable ? null : asOf }, coverage: { state: unavailable ? "unavailable" : partial ? "partial" : "complete", candidate_count: unavailable ? 0 : diagnostic ? 3 : partial ? 25 : 23, contributing_count: unavailable ? 0 : diagnostic ? 1 : 23, excluded_count: partial ? 2 : 0 }, exclusions: partial ? [{ reason: "Unknown source quantities", count: 2 }] : [], truth_state: unavailable ? "UNAVAILABLE" : partial ? "PARTIAL" : "LIVE", caveats: ["Synthetic render fixture only", ...(unavailable ? ["No supported canonical producer records this measurement."] : partial ? ["Telemetry is incomplete; unknown source quantities are excluded."] : [])], source_revision_ref: `sr_v1_${"a".repeat(64)}`, account_epoch: args.p_account_epoch, account_epoch_ref: `ae_v1_${"b".repeat(64)}`, evidence_ref: `aneb_v1_${"c".repeat(64)}`, reference_expires_at: new Date(Date.now() + 900000).toISOString() };
}
