import React from "react";
import { useTheme } from "next-themes";
import { ArrowUpRight, RefreshCw, AlertCircle, Sparkles } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { formatMetricMoney, chartMaximum, chartRatio, performanceDate } from "../../sales/performance/format";
import { DEBT_PRODUCT_LABELS, currentDebtSource, debtUtilization, debtSum, uniqueDebtRows, validDebtDate, validMinor } from "./types";
import type { DebtCreditObligation, DebtCreditReviewScope, DebtCreditWorkspaceProps } from "./types";
import "./debt-credit.css";
const date = (value: string | null) => validDebtDate(value) ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeZone: "UTC" }).format(new Date(value)) : "Not supplied";
const amount = (value: string | null, currency: string) => validMinor(value) ? formatMetricMoney(value, currency) : "Unavailable";
const revolving = (row: DebtCreditObligation) => row.product === "business_card" || row.product === "revolving_line";
export function DebtCreditWorkspace({ source, epoch, retry, onIntegrations, onReview }: DebtCreditWorkspaceProps) {
 const { resolvedTheme } = useTheme();
 const [entity, setEntity] = React.useState(""), [currency, setCurrency] = React.useState(""), [product, setProduct] = React.useState("all"), [horizon, setHorizon] = React.useState(30);
 const [now, setNow] = React.useState(Date.now), [selection, setSelection] = React.useState<{ epoch: string; identity: string; id: string } | null>(null);
 const [coverageOpen, setCoverageOpen] = React.useState<{ epoch: string; identity: string } | null>(null);
 const evaluatedNow = Math.max(now, Date.now());
 const opener = React.useRef<{ epoch: string; identity: string | null; node: HTMLElement } | null>(null);
 const current = !!epoch && source.scopeEpoch === epoch;
 const readable = current && !!source.readIdentity && ["ready", "partial"].includes(source.phase);
 const allRows = React.useMemo(() => readable ? source.rows : [], [readable, source.rows]);
 React.useEffect(() => { setEntity(""); setCurrency(""); setProduct("all"); setSelection(null); setCoverageOpen(null); setNow(Date.now()); }, [epoch]);
 React.useEffect(() => {
  const expiries = allRows.map(row => Date.parse(row.source.expiresAt ?? "")).filter(value => value > Date.now());
  if (!expiries.length) return;
  const timer = window.setTimeout(() => setNow(Date.now()), Math.min(Math.max(1, Math.min(...expiries) - Date.now() + 1), 2147483647));
  return () => window.clearTimeout(timer);
 }, [allRows, now]);
 const entities = [...new Map(allRows.map(row => [row.entity.id, row.entity.label])).entries()];
 const activeEntity = entity === "all" ? "all" : entities.some(([id]) => id === entity) ? entity : entities.some(([id]) => id === source.defaultEntityId) ? source.defaultEntityId! : entities[0]?.[0] ?? "";
 const currencies = [...new Set(allRows.filter(row => activeEntity === "all" || row.entity.id === activeEntity).map(row => row.currency))].sort();
 const activeCurrency = currencies.includes(currency) ? currency : source.defaultCurrency && currencies.includes(source.defaultCurrency) ? source.defaultCurrency : currencies[0] ?? null;
 const rows = allRows.filter(row => (activeEntity === "all" || row.entity.id === activeEntity) && row.currency === activeCurrency && (product === "all" || row.product === product)).sort((a, b) => a.institution.label.localeCompare(b.institution.label) || a.product.localeCompare(b.product) || a.originalLabel.localeCompare(b.originalLabel));
 const eligible = uniqueDebtRows(rows, evaluatedNow), owed = debtSum(eligible, "balanceMinor"), capacity = debtSum(eligible.filter(revolving), "availableMinor");
 const paymentRows = eligible.filter(row => row.nextPayment && validMinor(row.nextPayment.amountMinor) && validDebtDate(row.nextPayment.dueDate) && Date.parse(row.nextPayment.dueDate) >= new Date(new Date(evaluatedNow).toISOString().slice(0, 10)).getTime() && Date.parse(row.nextPayment.dueDate) <= evaluatedNow + horizon * 86400000).sort((a, b) => (a.nextPayment!.dueDate ?? "").localeCompare(b.nextPayment!.dueDate ?? ""));
 const service = paymentRows.length ? paymentRows.reduce((sum, row) => sum + BigInt(row.nextPayment!.amountMinor!), 0n).toString() : null;
 const selected = readable && selection?.epoch === epoch && selection.identity === source.readIdentity ? rows.find(row => row.obligationId === selection.id && currentDebtSource(row, evaluatedNow)) ?? null : null;
 const coverageShown = !!epoch && coverageOpen?.epoch === epoch && coverageOpen.identity === (source.readIdentity ?? "") && current && source.phase !== "denied";
 const rememberOpener = () => { if (epoch && document.activeElement instanceof HTMLElement) opener.current = { epoch, identity: source.readIdentity, node: document.activeElement }; };
 const inspect = (row: DebtCreditObligation) => { if (epoch && source.readIdentity && currentDebtSource(row, evaluatedNow)) { rememberOpener(); setSelection({ epoch, identity: source.readIdentity, id: row.obligationId }); } };
 const scope = (kind: DebtCreditReviewScope["kind"], selectedRows = eligible): DebtCreditReviewScope => ({ kind, obligationIds: selectedRows.map(row => row.match.canonicalObligationId ?? row.obligationId), evidenceRefs: [...new Set(selectedRows.map(row => row.source.evidenceRef).filter((ref): ref is string => !!ref))], entityIds: [...new Set(selectedRows.map(row => row.entity.id))], currency: activeCurrency });
 const canReview = current && !["denied", "loading", "resolving"].includes(source.phase);
 const excluded = rows.length - eligible.length;
 const sourceDates = [...new Set(eligible.map(row => row.source.asOf).filter((value): value is string => !!value))].sort();
 const temporalBasis = eligible.length && eligible.every(row => row.source.temporalBasis === "current_operational") ? "Current operational facts" : eligible.length && eligible.every(row => row.source.temporalBasis === "historical_statement") ? "Historical statement facts" : "Mixed or unspecified source periods";
 const temporalLabel = sourceDates.length ? `${temporalBasis} · ${performanceDate(sourceDates[0])}${sourceDates.length > 1 ? ` to ${performanceDate(sourceDates[sourceDates.length - 1])}` : ""}` : "Financial source period unavailable";
 const sourceStatus = !current || source.phase === "resolving" ? "Resolving your company scope" : source.phase === "loading" ? "Reading financial sources" : source.phase === "denied" ? "Financial access restricted" : source.phase === "error" ? "Financial sources could not load" : source.phase === "unavailable" ? "Company financing sources needed" : source.phase === "partial" ? "Partial source coverage" : "Selected source records";
 return <section className="debt-credit-workspace" aria-label="Debt and credit workspace">
  <header className="dc-header"><h1>Debt & Credit</h1><div className="dc-header-actions"><button className="dc-primary" onClick={() => onReview(scope("coverage"))} disabled={!canReview}><Sparkles size={15}/>Review with PAIGE</button><button onClick={() => { setSelection(null); setCoverageOpen(null); retry(); }} disabled={!current || ["loading", "resolving", "unavailable", "denied"].includes(source.phase)}><RefreshCw size={15}/>{source.phase === "loading" ? "Loading sources" : "Refresh sources"}</button></div></header>
  <div className="dc-filters"><label>Company entity<select value={activeEntity || "all"} disabled={!allRows.length} onChange={event => { setEntity(event.target.value); setSelection(null); }}><option value="all">All authorized entities</option>{entities.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Currency<select value={activeCurrency ?? ""} disabled={!currencies.length} onChange={event => { setCurrency(event.target.value); setSelection(null); }}>{!currencies.length && <option value="">Not supplied</option>}{currencies.map(value => <option key={value}>{value}</option>)}</select></label><label>Financing type<select value={product} onChange={event => { setProduct(event.target.value); setSelection(null); }}><option value="all">All financing</option>{Object.entries(DEBT_PRODUCT_LABELS).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><button onClick={() => { if (epoch && current && source.phase !== "denied") { rememberOpener(); setCoverageOpen({ epoch, identity: source.readIdentity ?? "" }); } }} disabled={!current || source.phase === "denied"}>Coverage & source matching</button></div>
  <p className="dc-source-status" role={source.phase === "error" || source.phase === "denied" ? "alert" : "status"}>{sourceStatus}{readable && source.asOf ? ` · as of ${performanceDate(source.asOf)}` : ""}{readable && excluded ? ` · ${excluded} records excluded from selected totals` : ""}</p>
  {current && source.phase === "denied" ? <div className="dc-access"><AlertCircle size={24}/><h2>Company financial records are restricted.</h2><p>No obligations, balances or account names are shown without authorized access.</p><button onClick={retry}>Retry access check</button></div> : <>
  <p className="dc-source-status">{temporalLabel}. Reference validity does not make a historical balance current.</p><div className="dc-metrics"><div><h2>Known owed balance</h2><strong>{activeCurrency ? amount(owed, activeCurrency) : "Unavailable"}</strong><p>Eligible selected balances{activeEntity === "all" && entities.length > 1 ? " across the selected authorized entities" : ""}; not cash or accounts payable.</p></div><div><h2>Revolving available capacity</h2><strong>{activeCurrency ? amount(capacity, activeCurrency) : "Unavailable"}</strong><p>Supported card and credit-line capacity only; not cash.</p></div><div><h2>Recorded next payments · {horizon} days</h2><strong>{activeCurrency ? amount(service, activeCurrency) : "Unavailable"}</strong><p>Supported next payments only; not a full recurring debt-service schedule.</p></div></div>
  <div className="dc-layout"><div className="dc-main"><div className="dc-section-heading"><h2>Financing register</h2><span>{readable ? `${rows.length} source accounts` : "Awaiting company sources"}</span></div><p className="dc-scroll-hint">Swipe or scroll horizontally for APR, payment dates and credit capacity.</p><div className="dc-table-scroll" tabIndex={0} role="region" aria-label="Financing register; scroll horizontally for all columns"><table><thead><tr><th>Original account label</th><th>Owed balance</th><th>APR / maturity</th><th>Next due</th><th>Capacity</th></tr></thead><tbody>{rows.map((row, index) => { const fresh = currentDebtSource(row, evaluatedNow); return <React.Fragment key={`${row.accountId}:${row.obligationId}`}>
   {(index === 0 || rows[index - 1].institution.id !== row.institution.id || rows[index - 1].product !== row.product) && <tr className="dc-group"><th colSpan={5}>{row.institution.label} · {DEBT_PRODUCT_LABELS[row.product]}</th></tr>}
   <tr><th scope="row"><button onClick={() => inspect(row)} disabled={!fresh}>{row.originalLabel}</button><small>{row.entity.label} · {row.accountId}</small><small>{fresh ? row.source.label : "Evidence expired or incomplete · refresh needed"}</small><small>{row.source.temporalBasis === "current_operational" ? "Current operational fact" : "Historical statement fact"} · as of {performanceDate(row.source.asOf)}</small><small>{row.match.status === "unresolved" ? "Unresolved match · excluded from totals" : row.match.status === "duplicate" ? "Duplicate source record · excluded from totals" : "Supported records count once per obligation"}</small></th><td>{fresh ? amount(row.balanceMinor, row.currency) : "Unavailable"}<small>{row.product === "business_card" ? "Card balance; not principal-only" : `Principal: ${fresh ? amount(row.principalMinor, row.currency) : "Unavailable"}`}</small></td><td>{fresh ? row.aprText ?? "APR not supplied" : "Unavailable"}<small>{fresh ? (revolving(row) && !row.maturityDate ? "No fixed maturity supplied" : date(row.maturityDate)) : "Evidence needed"}</small></td><td>{fresh ? amount(row.nextPayment?.amountMinor ?? null, row.currency) : "Unavailable"}<small className="dc-date">{fresh ? `Due ${date(row.nextPayment?.dueDate ?? null)}` : "Due date unavailable"}</small></td><td>{!revolving(row) ? "Not revolving" : <>{fresh ? amount(row.availableMinor, row.currency) : "Unavailable"} available<small>Limit: {fresh ? amount(row.limitMinor, row.currency) : "Unavailable"}</small>{fresh && debtUtilization(row.balanceMinor, row.limitMinor) !== null && <small>{debtUtilization(row.balanceMinor, row.limitMinor)}% utilized{validMinor(row.balanceMinor) && validMinor(row.limitMinor) && BigInt(row.balanceMinor) > BigInt(row.limitMinor) ? " · above recorded limit" : ""}</small>}{fresh && validMinor(row.balanceMinor) && validMinor(row.limitMinor) && BigInt(row.limitMinor) > 0n && <div className="dc-capacity-track" role="img" aria-label={`Recorded balance is ${debtUtilization(row.balanceMinor, row.limitMinor)} percent of supplied limit; visual bar capped at 100 percent`}><span style={{ width: `${chartRatio(row.balanceMinor, row.limitMinor)}%` }}/></div>}</>}</td></tr></React.Fragment>; })}{!rows.length && <tr><td colSpan={5}>{readable ? "No source accounts match this selection. Adjust the entity, currency or financing filter." : "Company card, line and loan records are not available. No missing balance is reported as zero."}</td></tr>}</tbody></table></div>
  <div className="dc-section-heading dc-payments-heading"><h2>Scheduled payments</h2><label>Payment horizon<select value={horizon} onChange={event => setHorizon(Number(event.target.value))}>{[14, 30, 90].map(value => <option key={value} value={value}>Next {value} days</option>)}</select></label></div>
  {paymentRows.length ? <><div className="dc-payment-chart" aria-label="Supported scheduled payment amounts">{paymentRows.map(row => { const payment = row.nextPayment!; const max = chartMaximum(paymentRows.map(item => item.nextPayment!.amountMinor!)); const components = validMinor(payment.principalMinor) && validMinor(payment.interestMinor) && BigInt(payment.principalMinor) + BigInt(payment.interestMinor) === BigInt(payment.amountMinor!); return <button key={row.obligationId} onClick={() => inspect(row)} aria-label={`Inspect ${row.originalLabel} payment ${amount(payment.amountMinor, row.currency)} due ${date(payment.dueDate)}`}><strong>{amount(payment.amountMinor, row.currency)}</strong><span className="dc-chart-space"><span className="dc-payment-bar" style={{ height: `${chartRatio(payment.amountMinor!, max)}%` }}>{components ? <><span className="dc-principal" style={{ height: `${chartRatio(payment.principalMinor!, payment.amountMinor!)}%` }}/><span className="dc-interest" style={{ height: `${chartRatio(payment.interestMinor!, payment.amountMinor!)}%` }}/></> : <span className="dc-unsplit"/>}</span></span><small>{date(payment.dueDate)}</small></button>; })}</div><p className="dc-chart-key">Champagne: principal · Violet: interest · Muted: payment amount without a supported split.</p><div className="dc-payment-list">{paymentRows.map(row => <button key={row.obligationId} onClick={() => inspect(row)}><span className="dc-date">{date(row.nextPayment!.dueDate)}</span><span>{row.originalLabel}<small>{amount(row.nextPayment!.principalMinor, row.currency)} principal · {amount(row.nextPayment!.interestMinor, row.currency)} interest</small></span><strong>{amount(row.nextPayment!.amountMinor, row.currency)}</strong></button>)}</div></> : <div className="dc-payment-gap"><h3>A schedule needs supported terms.</h3><p>{readable ? "No eligible next payments are recorded within this horizon. Missing or expired payment terms remain excluded." : "Payment dates and principal / interest schedules need company financing evidence. No payment curve or estimate is fabricated."}</p><button onClick={onIntegrations}>Review source connections <ArrowUpRight size={15}/></button></div>}
  <p className="dc-footnote">Credit availability is not a cash balance. Minimum card payments are not payoff amounts. Only each obligation’s recorded next payment is shown; repeated payments and full amortization schedules are not inferred. Unknown obligations or schedules may exist; these are selected source records, not complete company debt.</p></div>
  </div></>}
  <Sheet open={!!selected || coverageShown} onOpenChange={open => { if (!open) { setSelection(null); setCoverageOpen(null); } }}><SheetContent onCloseAutoFocus={event => { const target = opener.current; if (target && target.epoch === epoch && target.identity === source.readIdentity && target.node.isConnected) { event.preventDefault(); target.node.focus(); } }} className="dc-evidence" overlayClassName="dc-evidence-overlay" data-pg={resolvedTheme === "light" ? "light" : "dark"}><SheetHeader><SheetTitle>{selected?.originalLabel ?? "Coverage & source matching"}</SheetTitle><SheetDescription>Original company source wording, supported terms and financial boundaries.</SheetDescription></SheetHeader>{selected ? <><h2>{amount(selected.balanceMinor, selected.currency)} owed balance</h2><dl>{[["Stable account", selected.accountId], ["Canonical obligation", selected.match.canonicalObligationId ?? selected.obligationId], ["Company / currency", `${selected.entity.label} / ${selected.currency}`], ["Institution / product", `${selected.institution.label} / ${DEBT_PRODUCT_LABELS[selected.product]}`], ["Remaining principal", amount(selected.principalMinor, selected.currency)], ["APR", selected.aprText ?? "Not supplied"], ["Maturity", date(selected.maturityDate)], ["Limit", revolving(selected) ? amount(selected.limitMinor, selected.currency) : "Not revolving"], ["Available capacity", revolving(selected) ? amount(selected.availableMinor, selected.currency) : "Not revolving"], ["Next payment", amount(selected.nextPayment?.amountMinor ?? null, selected.currency)], ["Due", date(selected.nextPayment?.dueDate ?? null)], ["Source", selected.source.label], ["Temporal basis", selected.source.temporalBasis === "current_operational" ? "Current operational fact" : "Historical statement fact"], ["As of", performanceDate(selected.source.asOf)], ["Valid until", performanceDate(selected.source.expiresAt)], ["Coverage", selected.source.coverage ?? "Coverage not supplied"], ["Source matching", selected.match.status]].map(([label, value]) => <React.Fragment key={label}><dt>{label}</dt><dd>{value}</dd></React.Fragment>)}</dl></> : <><h2>{sourceStatus}</h2><p>{source.coverage ?? "Company financing coverage is not yet verified. Missing fields and balances remain unavailable."}</p><p>Multiple cards and lines at one institution remain distinct accounts. Only explicit verified matches identify duplicate sources of the same obligation; names or account masks never establish that match.</p><dl><dt>Excluded source records</dt><dd>{readable ? excluded : "Not established"}</dd><dt>Freshness</dt><dd>{source.asOf ? performanceDate(source.asOf) : "Not supplied"}</dd><dt>Investment capability</dt><dd>Not available in this financing view.</dd></dl><button onClick={onIntegrations}>Review company source connections</button></>}</SheetContent></Sheet>
 </section>;
}
