import React, { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { DebtCreditWorkspace } from "./DebtCreditWorkspace";
import { debtSum, debtUtilization, uniqueDebtRows, validDebtDate } from "./types";
import type { DebtCreditEnvelope, DebtCreditObligation } from "./types";
(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
const theme = vi.hoisted(() => ({ resolvedTheme: "dark" }));
vi.mock("next-themes", () => ({ useTheme: () => theme }));
const NOW = Date.parse("2026-10-10T12:00:00Z");
function row(id = "one", overrides: Partial<DebtCreditObligation> = {}): DebtCreditObligation { return { obligationId: id, accountId: `account-${id}`, entity: { id: "entity-1", label: "Test company" }, currency: "USD", institution: { id: "bank-1", label: "Test institution" }, product: "business_card", originalLabel: `Original label ${id}`, balanceMinor: "12345", principalMinor: null, limitMinor: "50000", availableMinor: "37655", aprText: "19.5% variable", maturityDate: null, nextPayment: { amountMinor: "500", principalMinor: "300", interestMinor: "200", dueDate: "2026-10-15" }, source: { temporalBasis: "historical_statement", evidenceRef: `ref-${id}`, asOf: "2026-10-10T11:00:00Z", expiresAt: "2026-10-10T13:00:00Z", label: "Original statement label" }, match: { status: "single_source" }, ...overrides }; }
let root: Root, host: HTMLDivElement;
const retry = vi.fn(), integrations = vi.fn(), review = vi.fn();
beforeEach(() => { theme.resolvedTheme = "dark"; vi.useFakeTimers(); vi.setSystemTime(NOW); retry.mockReset(); integrations.mockReset(); review.mockReset(); host = document.createElement("div"); document.body.append(host); root = createRoot(host); });
afterEach(() => { act(() => root.unmount()); host.remove(); vi.useRealTimers(); });
async function render(source: Partial<DebtCreditEnvelope> = {}, epoch = "epoch-1") { await act(async () => root.render(<DebtCreditWorkspace epoch={epoch} source={{ phase: "ready", scopeEpoch: "epoch-1", readIdentity: "read-1", rows: [row()], defaultEntityId: "entity-1", defaultCurrency: "USD", ...source }} retry={retry} onIntegrations={integrations} onReview={review}/>)); }
async function click(text: string) { const button = [...document.querySelectorAll("button")].find(node => node.textContent === text); expect(button).toBeTruthy(); await act(async () => button!.click()); }
describe("Debt evidence boundaries", () => {
 it("retains source exits without fabricated values for unavailable reads", async () => { await render({ phase: "unavailable", readIdentity: null, rows: [] }); expect(host.textContent).not.toContain("$0"); expect(host.querySelector(".dc-payment-chart")).toBeNull(); await click("Review company connections"); expect(integrations).toHaveBeenCalledOnce(); await click("Coverage & source matching"); expect(document.querySelector('[role="dialog"]')).not.toBeNull(); });
 it("withholds mismatched epoch and server-denied records", async () => { await render({}, "other"); expect(host.textContent).not.toContain("Original label one"); await render({ phase: "denied" }); expect(host.querySelector(".dc-metrics")).toBeNull(); expect(host.textContent).toContain("restricted"); });
 it("preserves multiple same-bank cards and separates currencies", async () => { await render({ rows: [row(), row("two"), row("cad", { currency: "CAD", entity: { id: "entity-2", label: "Foreign test company" } })] }); expect(host.textContent).toContain("Original label one"); expect(host.textContent).toContain("Original label two"); expect(host.textContent).not.toContain("Original label cad"); const entitySelect = host.querySelectorAll("select")[0]; await act(async () => { entitySelect.value = "all"; entitySelect.dispatchEvent(new Event("change", { bubbles: true })); }); const currencySelect = host.querySelectorAll("select")[1]; await act(async () => { currencySelect.value = "CAD"; currencySelect.dispatchEvent(new Event("change", { bubbles: true })); }); expect(host.textContent).toContain("Original label cad"); expect(host.textContent).not.toContain("Original label one"); });
 it("closes stale drawer identities and expires source values without a user refresh", async () => { await render(); await click("Original label one"); expect(document.querySelector('[role="dialog"]')).not.toBeNull(); await render({ readIdentity: "read-2" }); expect(document.querySelector('[role="dialog"]')).toBeNull(); await click("Original label one"); await act(async () => vi.advanceTimersByTime(3600001)); expect(document.querySelector('[role="dialog"]')).toBeNull(); expect(host.querySelector(".dc-metrics")?.textContent).not.toContain("123.45"); });
 it("routes fresh scoped references into existing review lane without fake persistence", async () => { await render(); await click("Prepare terms review"); expect(review).toHaveBeenCalledWith({ kind: "terms", obligationIds: ["one"], evidenceRefs: ["ref-one"], entityIds: ["entity-1"], currency: "USD" }); expect(host.textContent).not.toContain("saved"); });
 it("shows unmatched accounts while excluding their amounts from totals", async () => { await render({ rows: [row(), row("unmatched", { match: { status: "unresolved" } }), row("copy", { match: { status: "duplicate", duplicateOf: "one" } })] }); expect(host.textContent).toContain("Original label unmatched"); expect(host.textContent).toContain("2 records excluded"); expect(host.querySelector(".dc-metrics")?.textContent).not.toContain("370.35"); });
 it("never invents principal and interest splits", async () => { await render({ rows: [row("one", { nextPayment: { amountMinor: "500", principalMinor: null, interestMinor: null, dueDate: "2026-10-15" } })] }); expect(host.querySelector(".dc-unsplit")).not.toBeNull(); expect(host.querySelector(".dc-principal")).toBeNull(); });
 it("uses exact integer money and distinguishes unsupported values from zero", () => { expect(debtSum([row("huge", { balanceMinor: "900719925474099300" }), row("two", { balanceMinor: "7" })], "balanceMinor")).toBe("900719925474099307"); expect(debtSum([row("null", { balanceMinor: null })], "balanceMinor")).toBeNull(); expect(debtSum([row("zero", { balanceMinor: "0" })], "balanceMinor")).toBe("0"); expect(debtSum([row("invalid", { balanceMinor: "1.5" })], "balanceMinor")).toBeNull(); });
 it("restores account opener focus when the source drawer closes", async () => { await render(); const opener = [...host.querySelectorAll("button")].find(button => button.textContent === "Original label one")!; opener.focus(); await click("Original label one"); await click("Close"); await act(async () => vi.advanceTimersByTime(0)); expect(document.activeElement).toBe(opener); });
 it("assigns canonical portal theme attributes and a scoped overlay for both themes", async () => { for (const value of ["light", "dark"]) { theme.resolvedTheme = value; await render(); await click("Original label one"); expect(document.querySelector('[role="dialog"]')?.getAttribute("data-pg")).toBe(value); expect(document.querySelector(".dc-evidence-overlay")).not.toBeNull(); await click("Close"); await act(async () => vi.advanceTimersByTime(0)); } expect(host.querySelector(".dc-advisor-mark")).toBeNull(); });
 it("evaluates delayed incoming evidence against the current clock", async () => { await render({ phase: "loading", rows: [] }); await act(async () => vi.advanceTimersByTime(3600001)); await render(); expect(host.querySelector(".dc-metrics")?.textContent).not.toContain("123.45"); expect(host.querySelector(".dc-payment-chart")).toBeNull(); });
 it("refuses conflicting verified payment terms independent of row order", () => { const first = row("one", { match: { status: "verified", canonicalObligationId: "canonical-1" } }); const conflict = { ...first, obligationId: "copy", nextPayment: { ...first.nextPayment!, amountMinor: "999", dueDate: "2026-10-20" } }; expect(uniqueDebtRows([first, conflict], NOW)).toHaveLength(0); expect(uniqueDebtRows([conflict, first], NOW)).toHaveLength(0); const datedConflict = { ...first, obligationId: "dated-copy", source: { ...first.source, asOf: "2026-10-10T10:00:00Z" } }; expect(uniqueDebtRows([first, datedConflict], NOW)).toHaveLength(0); expect(uniqueDebtRows([datedConflict, first], NOW)).toHaveLength(0); const basisConflict = { ...first, obligationId: "basis-copy", source: { ...first.source, temporalBasis: "current_operational" as const } }; expect(uniqueDebtRows([first, basisConflict], NOW)).toHaveLength(0); });
 it("exposes uncapped over-limit semantics with capped geometry and dated source labels", async () => { await render({ rows: [row("one", { balanceMinor: "75000", limitMinor: "50000" })] }); expect(debtUtilization("75000", "50000")).toBe("150"); expect(host.textContent).toContain("150% utilized"); expect(host.querySelector('[aria-label*="150 percent"]')).not.toBeNull(); expect((host.querySelector(".dc-capacity-track span") as HTMLElement).style.width).toBe("100%"); expect(host.textContent).toContain("Historical statement facts"); expect(host.textContent).toContain("as of"); });
 it("rejects normalized impossible calendar dates", () => { expect(validDebtDate("2026-02-30")).toBe(false); expect(validDebtDate("2024-02-29")).toBe(true); expect(validDebtDate("2026-02-29")).toBe(false); });
 it("counts a verified duplicate once and refuses ambiguous different-account or amount collisions", () => { const first = row("one", { match: { status: "verified", canonicalObligationId: "canonical-1" } }); const copy = { ...first, obligationId: "copy" }; expect(uniqueDebtRows([first, copy], NOW)).toHaveLength(1); expect(uniqueDebtRows([first, { ...copy, accountId: "other" }], NOW)).toHaveLength(0); expect(uniqueDebtRows([first, { ...copy, balanceMinor: "99999" }], NOW)).toHaveLength(0); });
});
