import{it,expect,vi}from'vitest';import{handleAddressLookup,type LookupDependencies}from'./handler';
const tenant='11111111-1111-4111-8111-111111111111';const sample={result:{addressMatches:[{matchedAddress:'4600 SILVER HILL RD, WASHINGTON, DC, 20233',addressComponents:{fromAddress:'4500',toAddress:'4700',city:'WASHINGTON',state:'DC',zip:'20233'}}]}};
function setup(){const d:LookupDependencies={verifiedUser:vi.fn(async()=>({id:'actor',anonymous:false})),currentTenant:vi.fn(async()=>tenant),isAdmin:vi.fn(async()=>true),allowBucket:vi.fn(async()=>true),transport:vi.fn(async()=>({status:200,body:JSON.stringify(sample),truncated:false}))};return d}
function request(body:unknown={expected_tenant_id:tenant,country:'US',address:'4600 Silver Hill Rd, Washington, DC 20233'}){return new Request('https://edge.example.test/lookup',{method:'POST',headers:{Authorization:'Bearer test', 'Content-Type':'application/json'},body:JSON.stringify(body)})}
it('refuses unauthenticated anonymous mismatched and viewer before privileged limiter or transport',async()=>{for(const kind of['absent','anonymous','mismatch','viewer']){const d=setup();if(kind==='absent')d.verifiedUser=vi.fn(async()=>null);if(kind==='anonymous')d.verifiedUser=vi.fn(async()=>({id:'actor',anonymous:true}));if(kind==='mismatch')d.currentTenant=vi.fn(async()=>null);if(kind==='viewer')d.isAdmin=vi.fn(async()=>false);const r=await handleAddressLookup(request(),d);expect(r.status).toBeGreaterThanOrEqual(400);expect(d.allowBucket).not.toHaveBeenCalled();expect(d.transport).not.toHaveBeenCalled()}});
it('strict limiter rejects malformed and error verdicts without provider egress',async()=>{for(const verdict of[null,undefined,false,'true']){const d=setup();d.allowBucket=vi.fn(async()=>verdict);expect((await handleAddressLookup(request(),d)).status).toBe(429);expect(d.transport).not.toHaveBeenCalled()}const d=setup();d.allowBucket=vi.fn(async()=>{throw Error('private')});expect((await handleAddressLookup(request(),d)).status).toBe(503);expect(d.transport).not.toHaveBeenCalled()});
it('bounds request and refuses foreign country unknown fields and wrong tenant',async()=>{for(const body of[{expected_tenant_id:tenant,country:'CA',address:'Test address'},{expected_tenant_id:tenant,country:'US',address:'x'.repeat(301)},{expected_tenant_id:tenant,country:'US',address:'Test address',url:'https://private.test'},{expected_tenant_id:'22222222-2222-4222-8222-222222222222',country:'US',address:'Test address'}]){const d=setup();expect((await handleAddressLookup(request(body),d)).status).toBeGreaterThanOrEqual(400);expect(d.transport).not.toHaveBeenCalled()}});
it('normalizes matched house number not range endpoints through fixed host bounded transport',async()=>{const d=setup(),r=await handleAddressLookup(request(),d),b=await r.json();expect(b.candidates[0].line1).toBe('4600 SILVER HILL RD');expect(b.candidates[0].country).toBe('US');expect(b.source).toBe('census_geocoding_suggestion');expect(d.transport).toHaveBeenCalledWith(expect.stringContaining('https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?'),expect.objectContaining({credentials:'omit'}),{timeoutMs:10000,maxBytes:65536})});
it('returns honest no results and refuses malformed truncated oversize and provider errors without echoing body',async()=>{for(const res of[{status:200,body:'not json',truncated:false},{status:200,body:JSON.stringify({result:{addressMatches:[{matchedAddress:'unknown'}]}}),truncated:false},{status:200,body:'x'.repeat(65537),truncated:false},{status:200,body:JSON.stringify(sample),truncated:true},{status:302,body:'secret',truncated:false}]){const d=setup();d.transport=vi.fn(async()=>res);const r=await handleAddressLookup(request(),d);expect(r.status).toBe(502);expect(await r.text()).not.toContain('secret')}const d=setup();d.transport=vi.fn(async()=>({status:200,body:'{"result":{"addressMatches":[]}}',truncated:false}));expect((await(await handleAddressLookup(request(),d)).json()).candidates).toEqual([])});
it('timeout network failure and already cancelled request do not expose input',async()=>{const d=setup();d.transport=vi.fn(async()=>{throw Error('4600 private network timeout')});const r=await handleAddressLookup(request(),d);expect(r.status).toBe(503);expect(await r.text()).not.toContain('4600');const ctl=new AbortController();ctl.abort();const cancelled=new Request(request(),{signal:ctl.signal});const d2=setup();expect((await handleAddressLookup(cancelled,d2)).status).toBe(499);expect(d2.transport).not.toHaveBeenCalled()});
