-- Generated by Supabase CLI as 20261009234848; renumbered after the repository
-- future-version tail. Manual caller-JWT scope guard only; no executor activation.
begin;

create or replace function public.plan_update_item_scoped(
  p_item_id uuid,
  p_expected_actor_id uuid,
  p_expected_tenant_id uuid,
  p_status text default null,
  p_due_at timestamptz default null,
  p_assigned_to_user_id uuid default null
) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_actor uuid := auth.uid();
  v_tenant uuid;
  v_item_tenant uuid;
  v_result jsonb;
begin
  if v_actor is null or p_expected_actor_id is null
     or v_actor is distinct from p_expected_actor_id
     or p_expected_tenant_id is null then
    raise exception 'PLAN_SCOPE_CHANGED' using errcode = '42501';
  end if;

  -- Scope switches update this same profile row. Holding its lock through the
  -- canonical mutation serializes the precondition with a concurrent switch.
  perform 1 from public.profiles where user_id = v_actor for update;
  if not found then
    raise exception 'PLAN_SCOPE_CHANGED' using errcode = '42501';
  end if;
  -- Preserve the platform's canonical membership/delegated-scope resolver;
  -- do not replace it with a raw active_tenant_id or a second role authority.
  v_tenant := public.current_user_tenant_id();
  if v_tenant is distinct from p_expected_tenant_id then
    raise exception 'PLAN_SCOPE_CHANGED' using errcode = '42501';
  end if;

  select tenant_id into v_item_tenant from public.plan_items
    where id = p_item_id for update;
  if not found or v_item_tenant is distinct from v_tenant then
    raise exception 'PLAN_ITEM_UNAVAILABLE' using errcode = '42501';
  end if;

  -- The existing writer retains staff/creator/assignee authority, assignee
  -- membership, validation, completion timestamps and its canonical audit.
  v_result := public.plan_update_item(
    p_item_id := p_item_id, p_status := p_status, p_due_at := p_due_at,
    p_assigned_to_user_id := p_assigned_to_user_id, p_tenant_id := v_tenant
  );
  if (v_result->>'ok') is distinct from 'true'
     or (v_result->>'item_id') is distinct from p_item_id::text then
    raise exception 'PLAN_UPDATE_UNCONFIRMED' using errcode = 'P0001';
  end if;
  return jsonb_build_object('ok', true, 'item_id', p_item_id,
    'tenant_id', v_tenant, 'actor_id', v_actor);
end;
$$;

revoke all on function public.plan_update_item_scoped(uuid,uuid,uuid,text,timestamptz,uuid)
  from public, anon, authenticated, service_role;
grant execute on function public.plan_update_item_scoped(uuid,uuid,uuid,text,timestamptz,uuid)
  to authenticated;
comment on function public.plan_update_item_scoped(uuid,uuid,uuid,text,timestamptz,uuid)
  is 'Manual caller-JWT actor/workspace precondition around canonical plan_update_item. Acknowledgement is not client acceptance or a durable operation receipt.';
commit;
