import React,{act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {CollectionsWorkspace} from './CollectionsWorkspace';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const fixture=vi.hoisted(()=>({tenant:'11111111-1111-4111-8111-111111111111',agreement:'88888888-8888-4888-8888-888888888888'}));
vi.mock('next-themes',()=>({useTheme:()=>({resolvedTheme:'light'})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:vi.fn()}}));
vi.mock('../../useSoloCommercialTerms',()=>({useSoloCommercialTerms:()=>({phase:'ready',tenantId:fixture.tenant,canManage:true})}));
vi.mock('./useCollections',()=>({useCollections:()=>({state:'ready',invoices:[],receipts:[],agreements:[{id:fixture.agreement,client_name:'Example client',title:'Exact saved plan',collection_terms:{kind:'installment'},collection_terms_version:1,terms_current:true}],error:'',retry:vi.fn(),more:vi.fn(),loadingMore:false,invoiceHasMore:false,receiptHasMore:false,agreementHasMore:false})}));
vi.mock('./CollectionPlanBuilder',()=>({CollectionPlanBuilder:({onDirty,initialAgreementId}:{onDirty(d:boolean):void;initialAgreementId?:string})=><div data-agreement={initialAgreementId}><button onClick={()=>onDirty(true)}>Edit plan fixture</button></div>}));
let host:HTMLDivElement,root:Root;
beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host)});
afterEach(()=>{act(()=>root.unmount());host.remove()});
const render=async()=>act(async()=>root.render(<CollectionsWorkspace tenantId={fixture.tenant}/>));
const click=async(text:string)=>act(async()=>{[...document.querySelectorAll('button')].find(b=>b.textContent===text)!.click()});
it('opens the exact selected saved agreement rather than the default builder row',async()=>{await render();await click('Plans');await click('Review plan terms');expect(document.querySelector('[data-agreement]')?.getAttribute('data-agreement')).toBe(fixture.agreement)});
it('protects shell navigation until explicit discard of dirty builder entries',async()=>{await render();await click('Create collection');await click('Edit plan fixture');const proceed=vi.fn();const event=new CustomEvent('paige:sales-before-navigation',{cancelable:true,detail:{proceed}});await act(async()=>{window.dispatchEvent(event)});expect(event.defaultPrevented).toBe(true);expect(proceed).not.toHaveBeenCalled();await click('Keep editing');expect(proceed).not.toHaveBeenCalled();await act(async()=>{window.dispatchEvent(new CustomEvent('paige:sales-before-navigation',{cancelable:true,detail:{proceed}}))});await click('Discard entries');expect(proceed).toHaveBeenCalledOnce()});
it('captures sidebar SPA navigation before router handlers and preserves entries on cancellation',async()=>{await render();await click('Create collection');await click('Edit plan fixture');const nav=document.createElement('nav');nav.className='tcs-nav-links';const link=document.createElement('a');link.href='/solo/example/clients';link.textContent='Clients';nav.append(link);document.body.append(nav);const routed=vi.fn();link.addEventListener('click',routed);await act(async()=>link.click());expect(routed).not.toHaveBeenCalled();await click('Keep editing');expect(document.body.textContent).toContain('Edit plan fixture');nav.remove()});
