import {readReceiptConsequence} from './consequence';
import React from 'react';
import {supabase} from '@/integrations/supabase/client';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {useTheme} from 'next-themes';
import {UUID,object,parseCollectionCommand,type CollectionCommand} from '../../../../supabase/functions/_shared/sales-collections/contract';
import {collectionMoney} from './presentation';
type Result=Record<string,unknown>;
type Props={tenantId:string;command:CollectionCommand;onComplete(result:Result):void;onClose():void};
export function CollectionCommandReview(props:Props){
 const [actor,setActor]=React.useState<string|null>(null),[ready,setReady]=React.useState(false);
 React.useEffect(()=>{let alive=true,epoch=0;const started=epoch;void supabase.auth.getSession().then(({data})=>{if(alive&&started===epoch){setActor(data.session?.user.id??null);setReady(true)}}).catch(()=>{if(alive)setReady(true)});const {data}=supabase.auth.onAuthStateChange((_event,session)=>{epoch++;if(alive){setActor(session?.user.id??null);setReady(true)}});return()=>{alive=false;data.subscription.unsubscribe()}},[]);
 if(!ready)return <p role="status">Checking your account…</p>;if(!actor)return <p role="alert">Sign in to review this collection action.</p>;
 return <ActorReview key={`${actor}:${props.tenantId}`} {...props} actorId={actor}/>;
}
function ActorReview({tenantId,command,onComplete,onClose,actorId}:Props&{actorId:string}){
 const {resolvedTheme}=useTheme(),key=`paige:collection-operation:${actorId}:${tenantId}`;
 const captured=React.useRef({actorId,tenantId,command:parseCollectionCommand(command),operationId:crypto.randomUUID()}),initialized=React.useRef(false),restored=React.useRef(false);
 if(!initialized.current){initialized.current=true;try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(saved?.actorId===actorId&&saved?.tenantId===tenantId&&UUID.test(saved.operationId)){captured.current={actorId,tenantId,command:parseCollectionCommand(saved.command),operationId:saved.operationId};restored.current=true}}catch{/* Invalid browser state is never authority. */}}
 const [busy,setBusy]=React.useState(false),[unknown,setUnknown]=React.useState(restored.current),[proposal,setProposal]=React.useState<Result|null>(null),[notice,setNotice]=React.useState(''),unresolved=React.useRef(restored.current),alive=React.useRef(true),latest=React.useRef(tenantId),primary=React.useRef<HTMLButtonElement>(null);latest.current=tenantId;
 React.useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);React.useEffect(()=>{if(!busy)primary.current?.focus()},[busy,proposal]);
 React.useEffect(()=>{if(!busy&&!unknown)return;const prevent=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent)},[busy,unknown]);
 const forget=()=>{try{sessionStorage.removeItem(key)}catch{/* Same operation remains in memory. */}};
 const execute=async(approved:boolean)=>{if(busy||latest.current!==captured.current.tenantId)return;setBusy(true);setNotice('');const original=captured.current;try{try{sessionStorage.setItem(key,JSON.stringify(original))}catch{/* No alternate operation is created. */}let {data,error}=await supabase.functions.invoke('sales-collection-command',{body:{expected_tenant_id:original.tenantId,operation_id:original.operationId,command:original.command,...(approved&&proposal?{approved_fingerprint:proposal.fingerprint}:{})}});if(error&&'context' in error&&error.context instanceof Response){try{data=await error.context.json();error=null}catch{/* Outcome remains unknown. */}}if(!alive.current||latest.current!==original.tenantId)return;
 if(data?.outcome==='approval_required'&&typeof data.fingerprint==='string'){setProposal(data);setUnknown(false);unresolved.current=false}else if(data?.ok===true){forget();onComplete(data)}else{const uncertain=unresolved.current||!!error||data?.outcome==='outcome_unknown';setUnknown(uncertain);unresolved.current=uncertain;if(!uncertain)forget();setNotice(uncertain?'Recover this original operation before starting another action.':typeof data?.message==='string'?data.message:'The collection action was refused. Refresh the saved record.');}}
 catch{if(alive.current&&latest.current===original.tenantId){setUnknown(true);unresolved.current=true;setNotice('The result is unknown. Recover the same operation.')}}finally{if(alive.current)setBusy(false)}};
 const saved=captured.current.command,envelope=object(proposal?.preview)?proposal.preview:null,preview=readReceiptConsequence(envelope?.consequence,saved),financial=['collection.record_receipt','collection.reverse_receipt'].includes(saved.action);
 return <Dialog open onOpenChange={open=>{if(!open&&!busy&&!unknown){forget();onClose()}}}><DialogContent className="paige-solo sc-command-dialog" data-theme={resolvedTheme==='dark'?'dark':'light'} onPointerDownOutside={e=>e.preventDefault()} onEscapeKeyDown={e=>{if(busy||unknown)e.preventDefault()}}><DialogHeader><DialogTitle>Review collection action</DialogTitle></DialogHeader>{restored.current&&<p role="status">Recovering the saved {saved.action.replace('collection.','').replace(/_/g,' ')} operation. The newly requested action has not started.</p>}
 {proposal&&saved.action==='collection.save_terms'&&<dl className="sc-consequence"><dt>Plan</dt><dd>{saved.terms.kind.replace(/_/g,' ')}</dd><dt>{saved.terms.kind==='recurring'?'Agreed amount per cycle':'Agreed total'}</dt><dd>{collectionMoney(saved.terms.total_cents,saved.terms.currency)}</dd><dt>Anchor date</dt><dd>{saved.terms.anchor_date}</dd><dt>Schedule</dt><dd>{saved.terms.cadence} · {saved.terms.count??'Ongoing'} amounts</dd><dt>Activation</dt><dd>None · terms metadata only</dd></dl>}
 {proposal&&saved.action==='collection.record_receipt'&&<dl className="sc-consequence"><dt>Invoice</dt><dd>{typeof preview?.invoice_number==='string'?preview.invoice_number:saved.invoice_id}</dd><dt>Received amount</dt><dd>{collectionMoney(saved.amount_cents,saved.currency)}</dd><dt>Method</dt><dd>{saved.method.replace(/_/g,' ')}</dd><dt>Date received</dt><dd>{new Date(saved.received_at).toLocaleDateString(undefined,{timeZone:'UTC'})}</dd>{typeof preview?.remaining_cents==='number'&&<><dt>Current outstanding</dt><dd>{collectionMoney(preview.remaining_cents,saved.currency)}</dd><dt>After recording</dt><dd>{collectionMoney(typeof preview.resulting_remaining_cents==='number'?preview.resulting_remaining_cents:preview.remaining_cents-saved.amount_cents,saved.currency)}</dd></>}<dt>Verification</dt><dd>Human recorded · no provider verification</dd></dl>}
 {proposal&&saved.action==='collection.reverse_receipt'&&<dl className="sc-consequence"><dt>Invoice</dt><dd>{typeof preview?.invoice_number==='string'?preview.invoice_number:saved.invoice_id}</dd>{typeof preview?.amount_cents==='number'&&typeof preview.currency==='string'&&<><dt>Receipt correction</dt><dd>{collectionMoney(preview.amount_cents,preview.currency)}</dd></>}<dt>Reason</dt><dd>{saved.reason}</dd><dt>Money movement</dt><dd>None · original receipt retained</dd></dl>}
 {proposal&&saved.action==='collection.stage_import'&&<dl className="sc-consequence"><dt>Source</dt><dd>{saved.source_account}</dd><dt>Rows for review</dt><dd>{saved.rows.length}</dd><dt>Financial writes</dt><dd>None · staging only</dd></dl>}
 {proposal&&financial&&!preview&&<p role="alert">The authoritative financial consequence could not be read. Cancel and refresh this record before approval.</p>}<p>{typeof proposal?.summary==='string'?proposal.summary:'Prepare a review of the saved agreement or import before approving.'}</p>{notice&&<p role="alert">{notice}</p>}<div className="sc-actions"><button ref={primary} className="sc-primary" disabled={busy||!!proposal&&financial&&!preview&&!unknown} onClick={()=>execute(!!proposal&&!unknown)}>{busy?'Checking…':unknown?'Recover original operation':proposal?'Approve action':'Prepare review'}</button><button disabled={busy||unknown} onClick={()=>{forget();onClose()}}>Cancel</button></div></DialogContent></Dialog>;
}
