import React,{act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {CollectionsWorkspace} from './CollectionsWorkspace';
import type {CollectionInvoice,CollectionReceipt} from './api';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const fixture=vi.hoisted(()=>({tenant:'11111111-1111-4111-8111-111111111111',agreement:'88888888-8888-4888-8888-888888888888',invoices:[] as CollectionInvoice[],receipts:[] as CollectionReceipt[]}));
vi.mock('next-themes',()=>({useTheme:()=>({resolvedTheme:'light'})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:vi.fn()}}));
vi.mock('../../useSoloCommercialTerms',()=>({useSoloCommercialTerms:()=>({phase:'ready',tenantId:fixture.tenant,canManage:true})}));
vi.mock('./useCollections',()=>({useCollections:()=>({state:'ready',invoices:fixture.invoices,receipts:fixture.receipts,agreements:[{id:fixture.agreement,client_name:'Example client',title:'Exact saved plan',collection_terms:{kind:'installment'},collection_terms_version:1,terms_current:true}],error:'',retry:vi.fn(),more:vi.fn(),loadingMore:false,invoiceHasMore:false,receiptHasMore:false,agreementHasMore:false})}));
vi.mock('./CollectionPlanBuilder',()=>({CollectionPlanBuilder:({onDirty,initialAgreementId}:{onDirty(d:boolean):void;initialAgreementId?:string})=><div data-agreement={initialAgreementId}><button onClick={()=>onDirty(true)}>Edit plan fixture</button></div>}));
let host:HTMLDivElement,root:Root;
beforeEach(()=>{fixture.invoices=[];fixture.receipts=[];host=document.createElement('div');document.body.append(host);root=createRoot(host)});
afterEach(()=>{act(()=>root.unmount());host.remove()});
const render=async()=>act(async()=>root.render(<CollectionsWorkspace tenantId={fixture.tenant}/>));
const click=async(text:string)=>act(async()=>{[...document.querySelectorAll('button')].find(b=>b.textContent===text)!.click()});
it('identifies provider evidence in the primary Receipts register',async()=>{
 fixture.receipts=[{id:'44444444-4444-4444-8444-444444444444',tenant_id:fixture.tenant,invoice_id:'22222222-2222-4222-8222-222222222222',client_id:'33333333-3333-4333-8333-333333333333',client_name:'Example provider client',invoice_number:'INV-1',source_invoice_number:null,kind:'receipt',amount_cents:5000,currency:'usd',method:'stripe',provider:'stripe',received_at:'2026-01-01T12:00:00Z',created_at:'2026-01-01T12:00:00Z',reference:null,notes:null,reason:null,actor_user_id:'66666666-6666-4666-8666-666666666666',reverses_payment_id:null,provenance:'provider_verified'}];
 await render();await click('Receipts');
 expect(host.textContent).toContain('Provider confirmed');
 expect(host.textContent).not.toContain('Human recorded');
});
it('shows conserved mixed payments in the detail and excludes satisfied obligations from due counts',async()=>{
 fixture.invoices=[{id:'22222222-2222-4222-8222-222222222222',tenant_id:fixture.tenant,client_id:'33333333-3333-4333-8333-333333333333',client_name:'Example balance client',invoice_number:'INV-1',source_invoice_number:'SOURCE-1',status:'recorded',version:1,amount_cents:10000,currency:'usd',due_date:'2026-01-01',created_at:'2026-01-01T12:00:00Z',manual_recorded_cents:2500,provider_verified_cents:7500,allocated_cents:10000,remaining_cents:0,receipt_count:2,record_kind:'imported',provenance:'owner_imported_unverified'}];
 await render();
 const facts=[...host.querySelectorAll('.sc-facts article')];
 expect(facts.find(x=>x.textContent?.startsWith('Outstanding'))?.textContent).toContain('$0.00');
 expect(facts.find(x=>x.textContent?.startsWith('Past due'))?.querySelector('strong')?.textContent).toBe('0');
 await click('Open');
 expect(document.body.textContent).toContain('Manually recorded: $25.00');
 expect(document.body.textContent).toContain('Provider confirmed: $75.00');
 expect(document.body.textContent).toContain('Total applied: $100.00');
});
it('opens the exact selected saved agreement rather than the default builder row',async()=>{await render();await click('Plans');await click('Review plan terms');expect(document.querySelector('[data-agreement]')?.getAttribute('data-agreement')).toBe(fixture.agreement)});
it('protects shell navigation until explicit discard of dirty builder entries',async()=>{await render();await click('Create collection');await click('Edit plan fixture');const proceed=vi.fn();const event=new CustomEvent('paige:sales-before-navigation',{cancelable:true,detail:{proceed}});await act(async()=>{window.dispatchEvent(event)});expect(event.defaultPrevented).toBe(true);expect(proceed).not.toHaveBeenCalled();await click('Keep editing');expect(proceed).not.toHaveBeenCalled();await act(async()=>{window.dispatchEvent(new CustomEvent('paige:sales-before-navigation',{cancelable:true,detail:{proceed}}))});await click('Discard entries');expect(proceed).toHaveBeenCalledOnce()});
it('captures sidebar SPA navigation before router handlers and preserves entries on cancellation',async()=>{await render();await click('Create collection');await click('Edit plan fixture');const nav=document.createElement('nav');nav.className='tcs-nav-links';const link=document.createElement('a');link.href='/solo/example/clients';link.textContent='Clients';nav.append(link);document.body.append(nav);const routed=vi.fn();link.addEventListener('click',routed);await act(async()=>link.click());expect(routed).not.toHaveBeenCalled();await click('Keep editing');expect(document.body.textContent).toContain('Edit plan fixture');nav.remove()});
