import React,{act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {describe,it,expect,vi,afterEach,beforeEach} from 'vitest';
import {CollectionPlanBuilder} from './CollectionPlanBuilder';
import type {Agreement} from './api';
import {parseCollectionTerms} from '../../../../supabase/functions/_shared/sales-collections/contract';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let root:Root,host:HTMLDivElement;
beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host)});
afterEach(()=>{act(()=>root.unmount());host.remove()});
const render=(node:React.ReactNode)=>act(()=>root.render(node));
const screen={getByLabelText:(text:string|RegExp)=>Array.from(host.querySelectorAll('label')).find(l=>typeof text==='string'?l.firstChild?.textContent===text:text.test(l.firstChild?.textContent??''))!.querySelector('input,select,textarea')!,getByRole:(role:string,options?:{name:string;exact?:boolean})=>role==='alert'?host.querySelector('[role="alert"]')!:Array.from(host.querySelectorAll('button')).find(b=>b.textContent===options?.name)!,getByText:(text:string)=>Array.from(host.querySelectorAll('small')).find(e=>e.textContent?.trim()===text)!};
const fireEvent={change:(element:Element,event:{target:{value:string}})=>act(()=>{const proto=element instanceof HTMLSelectElement?HTMLSelectElement.prototype:element instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(element,event.target.value);element.dispatchEvent(new Event(element instanceof HTMLSelectElement?'change':'input',{bubbles:true}));}),click:(element:Element)=>act(()=>(element as HTMLElement).click()),submit:(element:Element)=>act(()=>element.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})))};
const agreement:Agreement={id:'11111111-1111-4111-8111-111111111111',tenant_id:'22222222-2222-4222-8222-222222222222',client_id:'33333333-3333-4333-8333-333333333333',client_name:'Example client',title:'Website agreement',status:'active',agreed_amount_minor:10001,agreed_currency:'usd',collection_terms:null,collection_terms_version:3,terms_current:true};
function mount(canManage=true){const review=vi.fn(),back=vi.fn(),dirty=vi.fn();render(<CollectionPlanBuilder agreements={[agreement]} initialKind="installment" canManage={canManage} onReview={review} onBack={back} onDirty={dirty}/>);fireEvent.change(screen.getByLabelText('Saved agreement'),{target:{value:agreement.id}});return {review,back,dirty}}
describe('Agreement-backed collection builder',()=>{
  // The builder's anchor defaults to today and the fixtures use fixed 2026 dates, so pin the clock:
  // otherwise the custom-schedule case starts failing the day those dates fall into the past.
  beforeEach(()=>{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-10-04T12:00:00Z'))});
  afterEach(()=>{vi.useRealTimers()});
 it('calculates optional agreed charges separately without adding them to the principal schedule or saved debt',()=>{const {review}=mount();fireEvent.change(screen.getByLabelText('Annual interest rate (%)'),{target:{value:'10'}});fireEvent.change(screen.getByLabelText('Interest agreement basis'),{target:{value:'Signed repayment agreement section 4'}});fireEvent.change(screen.getByLabelText('Fixed late fee'),{target:{value:'5'}});fireEvent.change(screen.getByLabelText('Late fee rate (%)'),{target:{value:'2'}});fireEvent.change(screen.getByLabelText('Grace days'),{target:{value:'5'}});fireEvent.change(screen.getByLabelText('Late fee agreement basis'),{target:{value:'Signed agreement section 5'}});fireEvent.change(screen.getByLabelText(/^Preview outstanding principal/),{target:{value:'100'}});fireEvent.change(screen.getByLabelText('Preview days overdue'),{target:{value:'365'}});expect(host.querySelector('[data-testid="interest-preview"]')?.textContent).toBe('$10.00');expect(host.querySelector('[data-testid="late-fee-preview"]')?.textContent).toBe('$7.00');expect(host.querySelector('[data-testid="charges-preview"]')?.textContent).toBe('$17.00');expect(host.textContent).toContain('Signed repayment agreement section 4');fireEvent.click(screen.getByRole('button',{name:'Review and save terms'}));expect(review.mock.calls[0][0].terms.total_cents).toBe(10001);expect(review.mock.calls[0][0].terms).not.toHaveProperty('preview_remaining');fireEvent.change(screen.getByLabelText('Preview days overdue'),{target:{value:'5'}});expect(host.querySelector('[data-testid="late-fee-preview"]')?.textContent).toBe('$0.00')});
 it('shows zero charges by default and rejects missing basis or invalid preview precision without rounding',()=>{mount();expect(host.querySelector('[data-testid="charges-preview"]')?.textContent).toBe('$0.00');fireEvent.change(screen.getByLabelText('Annual interest rate (%)'),{target:{value:'10'}});expect(host.querySelector('[data-testid="charges-preview"]')).toBeNull();expect(host.textContent).toContain('Missing agreement basis');fireEvent.change(screen.getByLabelText('Interest agreement basis'),{target:{value:'Agreed provision'}});fireEvent.change(screen.getByLabelText(/^Preview outstanding principal/),{target:{value:'1.234'}});expect(host.querySelector('[data-testid="charges-preview"]')).toBeNull();expect((screen.getByLabelText(/^Preview outstanding principal/) as HTMLInputElement).value).toBe('1.234')});
 it('opens the exact selected saved agreement and current terms instead of another row',()=>{const other={...agreement,id:'44444444-4444-4444-8444-444444444444',title:'Other agreement',collection_terms:parseCollectionTerms({schema_version:1,kind:'full',currency:'usd',total_cents:10001,anchor_date:'2026-09-19',cadence:'monthly',count:1,dates:[],deposit_cents:null,late_fee:{fixed_cents:0,rate_bps:0,grace_days:0,agreement_basis:null},interest:{annual_bps:0,agreement_basis:null}})};const review=vi.fn();render(<CollectionPlanBuilder agreements={[agreement,other]} initialAgreementId={other.id} initialKind="installment" canManage onReview={review} onBack={()=>undefined} onDirty={()=>undefined}/>);expect((screen.getByLabelText('Saved agreement') as HTMLSelectElement).value).toBe(other.id);expect((screen.getByLabelText('Anchor date') as HTMLInputElement).value).toBe('2026-09-19');fireEvent.click(screen.getByRole('button',{name:'Review and save terms'}));expect(review.mock.calls[0][0].agreement_id).toBe(other.id);expect(review.mock.calls[0][0].terms.kind).toBe('full')});
 it('uses canonical agreed amount/version and conserves cents without activation',()=>{const {review}=mount();fireEvent.change(screen.getByLabelText('Anchor date'),{target:{value:'2026-01-31'}});fireEvent.click(screen.getByRole('button',{name:'Review and save terms'}));expect(review).toHaveBeenCalledOnce();const command=review.mock.calls[0][0];expect(command.agreement_id).toBe(agreement.id);expect(command.expected_version).toBe(3);expect(command.terms.total_cents).toBe(10001);expect(command.terms.interest.annual_bps).toBe(0);expect(screen.getByText('2 · 2026-02-28')).toBeTruthy()});
 it('refuses non-zero finance metadata without agreed basis and preserves input',()=>{const {review}=mount();fireEvent.change(screen.getByLabelText('Annual interest rate (%)'),{target:{value:'5'}});fireEvent.submit(screen.getByRole('button',{name:'Review and save terms'}).closest('form')!);expect(review).not.toHaveBeenCalled();expect((screen.getByLabelText('Annual interest rate (%)') as HTMLInputElement).value).toBe('5');expect(screen.getByRole('alert')).toBeTruthy()});
 it('keeps read-only review disabled and reports dirty edits',()=>{const {review,dirty}=mount(false);expect((screen.getByRole('button',{name:'Review and save terms'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText('Anchor date'),{target:{value:'2026-10-11'}});expect(dirty).toHaveBeenCalledWith(true);fireEvent.submit(screen.getByRole('button',{name:'Review and save terms'}).closest('form')!);expect(review).not.toHaveBeenCalled()});
 it('requires explicit custom dates and conserved custom amounts',()=>{const {review}=mount();fireEvent.click(screen.getByRole('button',{name:'Custom',exact:true}));fireEvent.change(screen.getByLabelText(/Custom schedule/),{target:{value:'2026-10-04, 50.00, First\n2026-11-04, 50.01, Final'}});fireEvent.submit(screen.getByRole('button',{name:'Review and save terms'}).closest('form')!);expect(review).toHaveBeenCalledOnce();expect(review.mock.calls[0][0].terms.dates.map((d:{amount_cents:number})=>d.amount_cents)).toEqual([5000,5001])});
});
