import {useSalesDraftExit} from '../../sales-dialog';
import React from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {useTheme} from 'next-themes';
import type {CollectionCommand} from '../../../../supabase/functions/_shared/sales-collections/contract';
import type {CollectionInvoice,CollectionReceipt} from './api';
import {collectionMoney,currencyDigits,minorInput} from './presentation';
export function ImportedReceiptActions({row,receipts,hasMore,canManage,reviewing,onDirty,onReview}:{row:CollectionInvoice;receipts:CollectionReceipt[];hasMore:boolean;canManage:boolean;reviewing:boolean;onDirty(dirty:boolean):void;onReview(command:CollectionCommand):void}){
 const {resolvedTheme}=useTheme();const [form,setForm]=React.useState(false),[amount,setAmount]=React.useState(''),[method,setMethod]=React.useState('cash'),[date,setDate]=React.useState(()=>new Date().toISOString().slice(0,10)),[reference,setReference]=React.useState(''),[notes,setNotes]=React.useState(''),[reason,setReason]=React.useState(''),[notice,setNotice]=React.useState('');
 const exit=useSalesDraftExit(form?{amount,method,date,reference,notes}:null,reviewing,()=>{setForm(false);onDirty(false)});
 const close=exit.close;
 return <section className="sc-imported-actions"><h3>Received payments</h3><p>Record money you received against this imported obligation. No provider verification or customer invoice publication is implied.</p><button className="sc-primary" disabled={!canManage||row.status!=='recorded'||!row.version||row.remaining_cents===0||currencyDigits(row.currency)===null} onClick={()=>setForm(true)}>Record received payment</button>
 <Dialog open={form} onOpenChange={open=>{if(!open)close()}}><DialogContent className="paige-solo sc-command-dialog" data-theme={resolvedTheme==='dark'?'dark':'light'} onPointerDownOutside={e=>e.preventDefault()}><DialogHeader><DialogTitle>Record received payment</DialogTitle></DialogHeader>{exit.confirmation}<p>{row.client_name??'Unnamed client'} · {row.invoice_number} · {collectionMoney(row.remaining_cents,row.currency)} outstanding</p><form className="sc-form" onChange={()=>onDirty(true)} onSubmit={e=>{e.preventDefault();if(!canManage||!row.version)return;const cents=minorInput(amount,row.currency);if(cents===null||cents>row.remaining_cents){setNotice('Enter a positive amount within the balance using the supported currency decimal precision.');return}const stamp=`${date}T12:00:00Z`;if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(stamp))||new Date(stamp).toISOString().slice(0,10)!==date){setNotice('Choose a valid received date.');return}onReview({action:'collection.record_receipt',invoice_id:row.id,expected_version:row.version,amount_cents:cents,currency:row.currency,method:method as 'cash',received_at:new Date(stamp).toISOString(),reference:reference||null,notes:notes||null})}}><label>Amount received ({row.currency.toUpperCase()})<input inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}>{['zelle','cash','wire','check','bank_transfer','other'].map(m=><option key={m} value={m}>{m.replace(/_/g,' ')}</option>)}</select></label><label>Date received<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Reference<input maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="sc-wide">Notes<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><p className="sc-wide">Human recorded, never provider verified. The original obligation remains unchanged.</p>{notice&&<p role="alert" className="sc-wide">{notice}</p>}<div className="sc-actions sc-wide"><button className="sc-primary" disabled={!canManage}>Review received payment</button><button type="button" onClick={close}>Cancel</button></div></form></DialogContent></Dialog>
 <h3>Receipt trail</h3>{receipts.map(r=><article className="sc-trail" key={r.id}><strong>{collectionMoney(r.amount_cents,r.currency)} · {r.kind==='reversal'?'Reversal':r.method.replace(/_/g,' ')}</strong><span>{new Date(r.received_at).toLocaleDateString(undefined,{timeZone:'UTC'})} · {r.reference??'No reference'}</span><small>{r.provenance==='owner_imported_unverified'?'Imported historical receipt · unverified':'Human recorded'}</small>{r.reason&&<p>Correction reason: {r.reason}</p>}{r.kind==='receipt'&&!receipts.some(x=>x.reverses_payment_id===r.id)&&<button disabled={!canManage||!row.version||!reason.trim()} onClick={()=>{if(row.version)onReview({action:'collection.reverse_receipt',invoice_id:row.id,expected_version:row.version,payment_id:r.id,reason})}}>Review correction by reversal</button>}</article>)}{!receipts.length&&<p>No receipt facts in the loaded register.</p>}{hasMore&&<p>Additional receipt history is available in the Receipts register. This trail includes loaded records only.</p>}<label>Correction reason<textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required to reverse a mistaken receipt"/></label><p>A correction appends a traceable reversal. It does not erase history or refund money.</p></section>;
}
