import {UUID,object} from '../../../../supabase/functions/_shared/sales-collections/contract';
export type Batch={id:string;content_digest:string;state:string;review:{rows:{row:number;entity:string;entity_id:string;already_imported:boolean;target_invoice_id:string|null}[];conflicts:{row:number;entity:string;entity_id:string;code:string}[];eligible_commit:boolean;provenance:string}};
export function decodeImportBatch(value:unknown):Batch|null{
 if(!object(value))return null;const b=value,r=b.review;if(typeof b.id!=='string'||!UUID.test(b.id)||typeof b.content_digest!=='string'||!/^[a-f0-9]{64}$/.test(b.content_digest)||!['staged','committed'].includes(String(b.state))||!object(r))return null;
 if(!Array.isArray(r.rows)||r.rows.length>200||!Array.isArray(r.conflicts)||r.conflicts.length>200||typeof r.eligible_commit!=='boolean'||r.provenance!=='owner_imported_unverified')return null;
 for(const row of r.rows){if(!object(row)||!Number.isSafeInteger(row.row)||Number(row.row)<0||!['invoice','receipt'].includes(String(row.entity))||typeof row.entity_id!=='string'||typeof row.already_imported!=='boolean'||!(row.target_invoice_id===null||typeof row.target_invoice_id==='string'&&UUID.test(row.target_invoice_id)))return null}
 for(const row of r.conflicts){if(!object(row)||!Number.isSafeInteger(row.row)||Number(row.row)<0||typeof row.entity!=='string'||typeof row.entity_id!=='string'||typeof row.code!=='string')return null}
 if(r.conflicts.length>0&&r.eligible_commit)return null;return b as unknown as Batch;
}
export function parseCsv(text:string):string[][]{if(text.length>250000)throw Error('CSV exceeds 250 KB.');const rows:string[][]=[],row:string[]=[];let field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else if(quoted||field==='')quoted=!quoted;else throw Error('Unexpected quote in CSV.')}else if(!quoted&&(c===','||c==='\n'||c==='\r')){row.push(field);field='';if(c!==','){if(c==='\r'&&text[i+1]==='\n')i++;if(row.some(x=>x.trim()))rows.push([...row]);row.length=0;}}else field+=c;}if(quoted)throw Error('CSV has an unclosed quote.');row.push(field);if(row.some(x=>x.trim()))rows.push(row);if(rows.length<2||rows.length>201)throw Error('Import requires 1–200 rows.');if(rows.some(r=>r.length!==rows[0].length))throw Error('CSV rows do not have matching columns.');return rows}
