import React from 'react';
import {readRegister,readAgreements,decodeInvoice,decodeReceipt,type CollectionInvoice,type CollectionReceipt,type Agreement,type RegisterCursor} from './api';
export function useCollections(tenantId:string){
 const [invoices,setInvoices]=React.useState<CollectionInvoice[]>([]),[receipts,setReceipts]=React.useState<CollectionReceipt[]>([]),[agreements,setAgreements]=React.useState<Agreement[]>([]),[state,setState]=React.useState<'loading'|'ready'|'error'>('loading'),[error,setError]=React.useState(''),[refresh,setRefresh]=React.useState(0);
 const [invoiceCursor,setInvoiceCursor]=React.useState<RegisterCursor|null>(null),[receiptCursor,setReceiptCursor]=React.useState<RegisterCursor|null>(null),[agreementCursor,setAgreementCursor]=React.useState<string|null>(null),[loadingMore,setLoadingMore]=React.useState(false);
 const epoch=React.useRef(0),scope=React.useRef(tenantId);scope.current=tenantId;
 React.useEffect(()=>{const run=++epoch.current;let alive=true;setInvoices([]);setReceipts([]);setAgreements([]);setInvoiceCursor(null);setReceiptCursor(null);setAgreementCursor(null);setLoadingMore(false);setState('loading');setError('');
 void Promise.all([readRegister(tenantId,'invoice',null,decodeInvoice),readRegister(tenantId,'receipt',null,decodeReceipt),readAgreements(tenantId)]).then(([i,r,a])=>{if(!alive||run!==epoch.current)return;setInvoices(i.rows);setReceipts(r.rows);setAgreements(a.rows);setInvoiceCursor(i.next_cursor);setReceiptCursor(r.next_cursor);setAgreementCursor(a.next_cursor);setState('ready')}).catch(()=>{if(alive&&run===epoch.current){setState('error');setError('Collections could not be read. Retry this workspace.')}});return()=>{alive=false};
 },[tenantId,refresh]);
 const more=async(entity:'invoice'|'receipt'|'agreement')=>{if(loadingMore||state!=='ready')return;const opened=tenantId,run=epoch.current;setLoadingMore(true);setError('');try{if(entity==='agreement'){if(!agreementCursor)return;const result=await readAgreements(opened,agreementCursor);if(scope.current!==opened||run!==epoch.current)return;setAgreements(old=>[...old,...result.rows.filter(row=>!old.some(x=>x.id===row.id))]);setAgreementCursor(result.next_cursor)}else if(entity==='invoice'){if(!invoiceCursor)return;const result=await readRegister(opened,entity,invoiceCursor,decodeInvoice);if(scope.current!==opened||run!==epoch.current)return;setInvoices(old=>[...old,...result.rows.filter(row=>!old.some(x=>x.id===row.id))]);setInvoiceCursor(result.next_cursor)}else{if(!receiptCursor)return;const result=await readRegister(opened,entity,receiptCursor,decodeReceipt);if(scope.current!==opened||run!==epoch.current)return;setReceipts(old=>[...old,...result.rows.filter(row=>!old.some(x=>x.id===row.id))]);setReceiptCursor(result.next_cursor)}}catch{if(scope.current===opened&&run===epoch.current)setError('More records could not be read. Existing records remain visible.')}finally{if(scope.current===opened&&run===epoch.current)setLoadingMore(false)}};
 return {invoices,receipts,agreements,state,error,invoiceHasMore:!!invoiceCursor,receiptHasMore:!!receiptCursor,agreementHasMore:!!agreementCursor,loadingMore,more,retry:()=>setRefresh(n=>n+1)};
}
