// Local component/network fixtures only. They do not establish authenticated/provider capability.
import {useState} from 'react';
import {aggregateInvoiceItems,type InvoiceSnapshot} from '../../../../src/solo/sales/invoiceDraftSnapshot';
import type {InvoiceDraftSaveRequest} from '../../../../src/solo/sales/invoiceDraftApi';
const tenantId='11111111-1111-4111-8111-111111111111',clientId='33333333-3333-4333-8333-333333333333';
const exactDeposit=new URLSearchParams(location.search).get('exact-deposit')==='true';
const snapshot:InvoiceSnapshot={schema_version:exactDeposit?3 as const:2 as const,client_id:clientId,items:[{price_id:null,item:'Discovery and service delivery',description:'A detailed statement of work.\nUnicode and multiline descriptions are preserved 日本語.',unit_minor:exactDeposit?350000:10000,quantity:exactDeposit?1:2,price_snapshot:null}],kind:'deposit' as const,deposit_basis_points:exactDeposit?null:2500,...(exactDeposit?{deposit_minor:50000}:{}),currency:'usd' as const,cadence:null,recipient_email:'client@example.test',recipient_phone:null,email_source_method_id:null,phone_source_method_id:null,billing_address:{line1:'10 Example Street',line2:'Suite 2',city:'Example City',region:'CA',postal_code:'90210',country:null},agreement_id:null,agreement_snapshot:null,processor_intent:null,payment_method_intents:['cash','wire'],delivery_channel_intents:['email'],due_date:'2026-10-10',memo:'Synthetic fixture only. No invoice or email is sent.',total_minor:exactDeposit?350000:20000,due_now_minor:exactDeposit?50000:5000,remainder_minor:exactDeposit?300000:15000};
const issuedId='22222222-2222-4222-8222-222222222222',draftId='44444444-4444-4444-8444-444444444444';
const base=(id:string,status:string)=>({id,tenant_id:tenantId,invoice_number:status==='draft'?'DRAFT-02':'INV-01',status,billing_draft_version:1,version:status==='draft'?1:2,amount_total_cents:snapshot.total_minor,billing_draft:snapshot,issued_snapshot_version:status==='draft'?null:1,document:status==='draft'?null:{renderer_version:'paige-invoice-html-v1',snapshot,invoice_number:'INV-01',issuer_name:'Fixture workspace',client_name:'Fixture client',total_cents:snapshot.total_minor,currency:'usd'},document_input_digest:status==='draft'?null:'a'.repeat(64),manual_recorded_cents:status==='draft'?0:5000,remaining_cents:status==='draft'?snapshot.total_minor:snapshot.total_minor-5000,payments:status==='draft'?[]:[{id:'55555555-5555-4555-8555-555555555555',kind:'receipt',amount_cents:5000,currency:'usd',method:'cash',received_at:'2026-10-01T12:00:00Z',reference:'Receipt example',notes:'Synthetic human record',actor_user_id:'66666666-6666-4666-8666-666666666666',reverses_payment_id:null,reason:null}],payments_count:status==='draft'?0:1,payments_has_more:false});
const records=[base(issuedId,'issued'),base(draftId,'draft')];
export const invoiceLifecycleFixtureRow=base;
const toView=(r:ReturnType<typeof base>)=>({...r,tenantId,version:r.version,schemaVersion:r.billing_draft.schema_version,number:r.invoice_number,totalMinor:r.amount_total_cents,manualRecordedMinor:r.manual_recorded_cents,remainingMinor:r.remaining_cents,snapshot:r.billing_draft});
export function useSalesInvoiceDrafts(){const [revision,retry]=useState(0);return {tenantId,phase:'ready' as const,rows:records.map(toView),hasMore:false,nextCursor:null,message:'',pageMessage:'',loadingMore:false,retry:()=>retry(revision+1),loadMore:()=>undefined,save:async(request:InvoiceDraftSaveRequest)=>{const items=request.draft.items.map(line=>({...line,unit_minor:line.unit_minor??0,price_snapshot:null}));const amounts=aggregateInvoiceItems(items,request.draft.schema_version===2&&request.draft.kind==='deposit'?request.draft.deposit_basis_points??0:undefined,request.draft.schema_version===3?request.draft.deposit_minor:undefined);const saved=base(request.invoiceId,'draft');saved.billing_draft={...request.draft,items,agreement_snapshot:null,total_minor:amounts.totalMinor,due_now_minor:amounts.dueNowMinor,remainder_minor:amounts.remainderMinor};saved.amount_total_cents=amounts.totalMinor;saved.version=request.expectedVersion+1;saved.billing_draft_version=saved.version;const index=records.findIndex(row=>row.id===saved.id);if(index<0)records.push(saved);else records[index]=saved;retry(v=>v+1);return {ok:true as const,value:toView(saved)}}};}
export function useSoloCommercialTerms(){return {tenantId,phase:'ready' as const,canManage:true,clientsReadable:true,clients:[{id:clientId,name:'Fixture client',primaryEmail:'client@example.test'}],terms:[],templates:[],defaultTerms:null,pending:[],retry:()=>undefined};}
export function useCatalogOffers(){return {tenantId,phase:'ready' as const,offers:[],referencedOffers:[],hasMore:false,retry:()=>undefined};}
export function useInvoiceBillingSources(){return {tenantId,phase:'ready' as const,customers:[{id:clientId,name:'Fixture client',address:snapshot.billing_address,methods:[]}],agreements:[],customersHasMore:false,agreementsHasMore:false,retry:()=>undefined};}
export const supabase={
 auth:{getSession:async()=>({data:{session:{user:{id:'66666666-6666-4666-8666-666666666666'},access_token:'local-fixture-not-a-real-token'}}}),getUser:async()=>({data:{user:null}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},
 rpc:async(name:string,args:Record<string,unknown>)=>({data:name==='read_sales_invoice'?records.find(r=>r.id===args._invoice_id):name==='list_sales_invoice_senders'?[{id:'77777777-7777-4777-8777-777777777777',provider:'resend',from_address:'business@example.test'}]:null,error:null}),
 functions:{invoke:async(name:string,{body}:{body:Record<string,unknown>})=>{if(name==='sales-invoice-delivery')return {data:{ok:true,eligible:true,summary:'Fixture eligible connection. Provider execution UNVERIFIED.'},error:null};const command=body.command as Record<string,unknown>;const row=records.find(r=>r.id===command.invoice_id)??records[0];return {data:{ok:false,outcome:'approval_required',fingerprint:'0123456789abcdef',summary:'Review the synthetic invoice action. No external action occurs in this fixture.',preview:{invoice_number:row.invoice_number,remaining_cents:row.remaining_cents}},error:null};}},
 from:()=>{const result={data:[],error:null};const chain:Record<string,unknown>={then:(resolve:(v:unknown)=>void)=>Promise.resolve(result).then(resolve)};for(const name of ['select','eq','is','order','limit','maybeSingle','single'])chain[name]=()=>chain;return chain;},
 channel:()=>({on(){return this},subscribe(){return this}}),removeChannel:()=>undefined,
};
